### ISSUE TITLE
在训练过程中突然出现shutdown错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleClas#1015]
- PaddlePaddle 2.1.1
 - Python 3.7
 - Ubuntu 18.04
 - PaddleClas 2.2
 - num_workers: 4

错误日志如下，前面已经训练了好多轮了。
```
Traceback (most recent call last):
  File "train.py", line 27, in <module>
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/ppcls/engine/trainer.py", line 158, in train
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/reader.py", line 429, in __call__
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/reader.py", line 426, in __iter__
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 283, in __init__
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _init_workers
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/context.py", line 102, in Queue
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/queues.py", line 42, in __init__
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/context.py", line 67, in Lock
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/synchronize.py", line 162, in __init__
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/multiprocessing/synchronize.py", line 59, in __init__
OSError: [Errno 24] Too many open files
W0707 01:56:58.796609 29835 default_variables.cpp:78] Fail to open /proc/self/stat: Too many open files [24]
W0707 01:56:58.796720 29835 default_variables.cpp:331] Fail to open /proc/self/fd: Too many open files [24]
W0707 01:56:58.796741 29835 default_variables.cpp:209] Fail to open /proc/self/statm: Too many open files [24]
W0707 01:56:58.796766 29835 default_variables.cpp:276] Fail to open /proc/loadavg: Too many open files [24]
W0707 01:56:58.796782 29835 default_variables.cpp:429] Fail to open /proc/self/io: Too many open files [24]


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1625594218 (unix time) try "date -d @1625594218" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800007482) received by PID 3400 (TID 0x7f3b0d2fb740) from PID 29826 ***]



--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle::framework::SignalHandle(char const*, int)
1   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: `Termination signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1625594218 (unix time) try "date -d @1625594218" if you are using GNU date ***]
  [SignalInfo: *** SIGTERM (@0x3e800007482) received by PID 3401 (TID 0x7f3b0d2fb740) from PID 29826 ***]

Exception ignored in: <function _DataLoaderIterMultiProcess.__del__ at 0x7f3ab040bb00>
Traceback (most recent call last):
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 566, in __del__
    self._try_shutdown_all()
  File "/home/fg010/anaconda3/envs/PaddlePaddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 371, in _try_shutdown_all
    if not self._shutdown:
AttributeError: '_DataLoaderIterMultiProcess' object has no attribute '_shutdown'
```

**Comment by cuicheng01** [comment]
这个问题是必现的吗？如果不是，目前可能不太好定位是哪里出了问题，建议加载当前的checkpoints重新run，加载方式是在yaml中的Global.checkpoints中设置模型的路径，注意去掉.pdparams。

**Comment by yeyupiaoling** [comment]
@cuicheng01 必定出现的，就是出现的时候要训练比较久才行，要6到10个小时才行，不仅是PaddleClas，PaddleDetection也出现已有的问题。就算resume了，还是会出现。Ubuntu才会出现，Windows倒不会

**Comment by cuicheng01** [comment]
现在这样确实不太好定位，如果Detection也遇到这个问题像是环境哪里出了问题，或者你在https://github.com/PaddlePaddle/Paddle/issues，提个issue问一下？

**Comment by heavengate** [comment]
这个是操作系统的报错，原因是打开了的太多的文件，你是否自定义的数据读取相关的有打开文件没有关闭的情况，或者试下 https://blog.csdn.net/qq_40244755/article/details/103973572

**Comment by yeyupiaoling** [comment]
@heavengate 这个已经改过为2048了，有同学说这个是PaddlePaddle 2.1.1的dataloader多次初始化导致的。
