### ISSUE TITLE
基于PaddleHub Serving的服务部署

### ISSUE THREAD

**Issue by zhujiebing** [PaddlePaddle/PaddleClas#1049]
启动服务出现error日志。
Python 3.9.6
pip 21.1.3 
paddle 2.1.1

```java
[zjbing@v-zhujiebing-test-137 deploy]$ hub serving start -m clas_system
/usr/local/python3.9.6/lib/python3.9/site-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
/usr/local/python3.9.6/lib/python3.9/site-packages/pip/_vendor/packaging/version.py:127: DeprecationWarning: Creating a LegacyVersion has been deprecated and will be removed in the next major release
  warnings.warn(
Use CPU
Traceback (most recent call last):
  File "/home/zjbing/.local/bin/hub", line 8, in <module>
    sys.exit(execute())
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/commands/utils.py", line 69, in execute
    return com['_entry']().execute(sys.argv[idx:])
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 349, in execute
    self.start_serving()
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 242, in start_serving
    self.start_single_app_with_args()
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 218, in start_single_app_with_args
    self.preinstall_modules()
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/commands/serving.py", line 149, in preinstall_modules
    m = hub.Module(**init_args)
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/module/module.py", line 171, in __new__
    module = cls.init_with_name(
  File "/home/zjbing/.local/lib/python3.9/site-packages/paddlehub/module/module.py", line 281, in init_with_name
    return user_module_cls(**kwargs)
  File "/home/zjbing/.paddlehub/modules/clas_system/module.py", line 45, in __init__
    self.cls_predictor = ClsPredictor(self._config)
  File "/home/zjbing/paddlecls/PaddleClas/deploy/./python/predict_cls.py", line 42, in __init__
    self.postprocess = build_postprocess(config["PostProcess"])
  File "/home/zjbing/paddlecls/PaddleClas/deploy/./python/postprocess.py", line 38, in build_postprocess
    func_list.append(getattr(mod, func)(**config[func]))
AttributeError: module 'python.postprocess' has no attribute 'name'

```

**Comment by TingquanGao** [comment]
感谢反馈，我们尽快修复该问题。

**Comment by TingquanGao** [comment]
您好，该问题已修复：
https://github.com/PaddlePaddle/PaddleClas/pull/1056
https://github.com/PaddlePaddle/PaddleClas/pull/1055

https://github.com/PaddlePaddle/PaddleClas/pull/1056/commits/8a1c92d1e64b6c3a3d7d0da9298b0710ca9098fd
https://github.com/PaddlePaddle/PaddleClas/pull/1055/commits/9231572effb2084221fa6af374f07836256d0375
