### ISSUE TITLE
训练自己模型进行识别的问题：

### ISSUE THREAD

**Issue by jackie8310** [PaddlePaddle/PaddleClas#1061]
识别中在paddledetection中训练了自己的模型，并导出为
![image](https://user-images.githubusercontent.com/63913709/126421307-4b5625b8-67cc-4aa0-8c10-43d520b68fff.png)
，另外，训练了自己的特征提取模型，并导出为：
![image](https://user-images.githubusercontent.com/63913709/126421379-054fc0aa-a3b6-4ef7-8838-872248f98f41.png)
识别时的yaml文件如下：
Global:
  infer_imgs: "./recognition_demo_data_v1.0/test_product/test/"
  det_inference_model_dir: "./models/cascade_rcnn_r50_vd_fpn_infer"
  rec_inference_model_dir: "./models/MobileNetV1_infer"
  rec_nms_thresold: 0.05
  
  batch_size: 1
  image_shape: [3, 1024, 1280]
  threshold: 0.5
  max_det_results: 5
  labe_list:
  - foreground

  # inference engine config
  use_gpu: True
  enable_mkldnn: False
  cpu_num_threads: 100
  enable_benchmark: True
  use_fp16: False
  ir_optim: True
  use_tensorrt: False
  gpu_mem: 8000
  enable_profile: False

DetPreProcess:
  transform_ops:
    - DetResize:
        interp: 2
        keep_ratio: false
        target_size: [800, 1333]
    - DetNormalizeImage:
        is_scale: true
        mean: [0.331,0.374,0.413]
        std: [0.182, 0.206,0.23]
    - DetPermute: {}
DetPostProcess: {}

RecPreProcess:
  transform_ops:
    - ResizeImage:
        size: 224
    - NormalizeImage:
        scale: 0.00392157
        mean: [0.356, 0.398, 0.431]
        std: [0.104, 0.114, 0.124]
        order: ''
    - ToCHWImage:

RecPostProcess: null

# indexing engine config
IndexProcess:
  index_path: "./recognition_demo_data_v1.0/gallery_product/index_update"
  search_budget: 100
  return_k: 5
  dist_type: "IP"
  score_thres: 0.5
问题：predict_system.py后出现如下错误：
Traceback (most recent call last):
  File "deploy\python\predict_system.py", line 134, in <module>
    main(config)
  File "deploy\python\predict_system.py", line 125, in main
    output = system_predictor.predict(img)
  File "deploy\python\predict_system.py", line 89, in predict
    results = self.det_predictor.predict(img)
  File "G:\paddle\PaddleClas-release-2.2\deploy\python\predict_det.py", line 121, in predict
    self.paddle_predictor.run()
ValueError: In user code:

    File "/home/aistudio/PaddleDetection2.1/tools/export_model.py", line 105, in <module>
      main()
    File "/home/aistudio/PaddleDetection2.1/tools/export_model.py", line 101, in main
      run(FLAGS, cfg)
    File "/home/aistudio/PaddleDetection2.1/tools/export_model.py", line 69, in run
      trainer.export(FLAGS.output_dir)
    File "/home/aistudio/PaddleDetection2.1/ppdet/engine/trainer.py", line 507, in export
      input_spec, static_model.forward.main_program,
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 534, in main_program
      concrete_program = self.concrete_program
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 454, in concrete_program
      return self.concrete_program_specify_input_spec(input_spec=None)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
      *desired_input_spec)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
      concrete_program, partial_program_layer = self._program_cache[cache_key]
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
      self._caches[item] = self._build_once(item)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
      class_instance=cache_key.class_instance)
    File "<decorator-gen-65>", line 2, in from_func_spec

    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
      return wrapped_func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 40, in __impl__
      return func(*args, **kwargs)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 652, in from_func_spec
      outputs = static_func(*inputs)
    File "/tmp/tmpo73widhr.py", line 27, in forward
      false_fn_1, (), (), (out,))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/aistudio/PaddleDetection2.1/ppdet/modeling/architectures/meta_arch.py", line 29, in forward
      out = self.get_pred()
    File "/home/aistudio/PaddleDetection2.1/ppdet/modeling/architectures/cascade_rcnn.py", line 136, in get_pred
      bbox_pred, bbox_num, mask_pred = self._forward()
    File "/tmp/tmpubvgfkvq.py", line 21, in _forward
      true_fn_3, false_fn_3, (body_feats,), (body_feats,), (body_feats,))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 210, in convert_ifelse
      return _run_py_ifelse(pred, true_fn, false_fn, true_args, false_args)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 235, in _run_py_ifelse
      return true_fn(*true_args) if pred else false_fn(*false_args)
    File "/home/aistudio/PaddleDetection2.1/ppdet/modeling/architectures/cascade_rcnn.py", line 89, in _forward
      body_feats = self.neck(body_feats)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
      outputs = self.forward(*inputs, **kwargs)
    File "/tmp/tmpl1hvmjm4.py", line 31, in forward
      for_loop_condition_4, for_loop_body_4, [i, laterals, num_levels])
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 44, in convert_while_loop
      loop_vars = _run_py_while(cond, body, loop_vars)
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_operators.py", line 58, in _run_py_while
      loop_vars = body(*loop_vars)
    File "/home/aistudio/PaddleDetection2.1/ppdet/modeling/necks/fpn.py", line 199, in forward
      laterals[lvl - 1] += upsample
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/math_op_patch.py", line 305, in __impl__
      attrs={'axis': axis})
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3232, in append_op
      attrs=kwargs.get("attrs", None))
    File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2312, in __init__
      for frame in traceback.extract_stack():

    **InvalidArgumentError: Broadcast dimension mismatch. Operands could not be broadcast together with the shape of X = [1, 256, 100, 167] and the shape of Y = [1, 256, 100, 168]. Received [167] in X is not equal to [168] in Y at i:3.**
      [Hint: Expected x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1 == true, but received x_dims_array[i] == y_dims_array[i] || x_dims_array[i] <= 1 || y_dims_array[i] <= 1:0 != true:1.] (at C:\home
\workspace\Paddle_release2\paddle/fluid/operators/elementwise/elementwise_op_function.h:169)
      [operator < elementwise_add > error]
请指教什么问题？

**Comment by cuicheng01** [comment]
先可视化看下模型有没有问题呢？

**Comment by sinoboy168** [comment]
貌似你用PaddleDect来预测的吗？
