### ISSUE TITLE
小样本带查询集和支持集的图片分类有例子吗？

### ISSUE THREAD

**Issue by bbbxixixixi** [PaddlePaddle/PaddleClas#1180]
以前接触的图片分类，训练集和测试集中的类别是相同的，模型训练完在测试集上运行就能得到类别
但是这种有查询集和支持集的不一样，测试集中的类别可能在训练集中没有
paddlecls有这类问题的解决方案吗？

**Comment by cuicheng01** [comment]
PaddleClas提供的metric learning旨在学习图像的特征，所以只要把特征学习好之后，那么相似的图片在n维空间中的特征距离会比较接近，反之比较远。所以你提到的这个问题PaddleClas可以解决哈，淡然你需要提供一个Database供查询确定最终类别，具体可以查看：https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/tutorials/quick_start_recognition.md
这个demo里提供了如何添加新的类别。

**Comment by bbbxixixixi** [comment]
> PaddleClas提供的metric learning旨在学习图像的特征，所以只要把特征学习好之后，那么相似的图片在n维空间中的特征距离会比较接近，反之比较远。所以你提到的这个问题PaddleClas可以解决哈，淡然你需要提供一个Database供查询确定最终类别，具体可以查看：https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/zh_CN/tutorials/quick_start_recognition.md
> 这个demo里提供了如何添加新的类别。

我试着操作了一下，报了以下的错误
2021-08-27 15:24:33 INFO:         ToCHWImage : None
  0%|                                                   | 0/400 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 101, in <module>
    main(config)
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 94, in main
    system_builder = GalleryBuilder(config)
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 61, in __init__
    self.build(config['IndexProcess'])
  File "/home/aistudio/PaddleClas-release-2.2/deploy/python/build_gallery.py", line 81, in build
    gallery_features[i, :] = rec_feat
ValueError: could not broadcast input array from shape (120,) into shape (512,)

我原本的类型有120个，配置文件中的embedding_size是512，这两个需要匹配吗？embedding_size感觉应该是中间过程的特征维度，如果要匹配，为何不直接从原始的model中获取？
