### ISSUE TITLE
classNum和batchsize相等时,labelsmooth报错

### ISSUE THREAD

**Issue by ShawnXsw** [PaddlePaddle/PaddleClas#1188]
1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.2
 3. 训练环境信息：
  a. 具体操作系统，如Linux
  b. Python版本号，如Python3.7
  c. CUDA/cuDNN版本， CUDA10.2/cuDNN 8.0

Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    trainer.train()
  File "/root/python/PaddleClas/ppcls/engine/trainer.py", line 218, in train
    loss_dict = self.train_loss_func(out, batch[1:])
  File "/root/python/PaddleClas/ppcls/loss/__init__.py", line 45, in __call__
    loss = loss_func(input, batch)
  File "/root/python/PaddleClas/ppcls/loss/celoss.py", line 71, in __call__
    loss1 = super().forward(input, target1)["CELoss"]
  File "/root/python/PaddleClas/ppcls/loss/celoss.py", line 45, in forward
    label = self._labelsmoothing(label, class_num)
  File "/root/python/PaddleClas/ppcls/loss/celoss.py", line 36, in _labelsmoothing
    soft_target = F.label_smooth(one_hot_target, epsilon=self.epsilon)
  File "/root/miniconda3/envs/paddle_cls/lib/python3.7/site-packages/paddle/nn/functional/common.py", line 1547, in label_smooth
    float(epsilon))
RuntimeError: (NotFound) Operator label_smooth does not have kernel for data_type[int64_t]:data_layout[ANY_LAYOUT]:place[CUDAPlace(0)]:library_type[PLAIN].
  [Hint: Expected kernel_iter != kernels.end(), but received kernel_iter == kernels.end().] (at /paddle/paddle/fluid/imperative/prepared_operator.cc:135)
  [operator < label_smooth > error]

**Comment by littletomatodonkey** [comment]
你好，我这边设置了class num和batch size大小相同，都是flowers102，没有问题，方便提供下你的配置文件吗？

**Comment by ShawnXsw** [comment]
> 你好，我这边设置了class num和batch size大小相同，都是flowers102，没有问题，方便提供下你的配置文件吗？

@littletomatodonkey 
[ResNet101_vd.zip](https://github.com/PaddlePaddle/PaddleClas/files/7082321/ResNet101_vd.zip)

**Comment by littletomatodonkey** [comment]
你好，感谢反馈，已经在这个pr中修复：https://github.com/PaddlePaddle/PaddleClas/pull/1192

**Comment by ShawnXsw** [comment]
> 你好，感谢反馈，已经在这个pr中修复：#1192

@littletomatodonkey  你flowers102为什么正常呢
