### ISSUE TITLE
特征学习任务训练报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleClas#1238]
1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 训练环境信息(AIStudio)：
  a. 具体操作系统，Linux
  b. Python版本号，如Python3.7
  c. CUDA， CUDA10.1  cuDNN Version: 7.6
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

yaml: 

# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./output/
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 10
  epochs: 120
  print_batch_step: 10
  use_visualdl: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference
  eval_mode: classification

# model architecture
Arch:
  name: RecModel
  infer_output_key: features
  infer_add_softmax: False

  Backbone: 
    name: ResNet50_vd
    pretrained: True
  BackboneStopLayer:
    name: flatten_0
  Neck:
    name: FC
    embedding_size: 2048
    class_num: 357
  Head:
    name: FC  
    embedding_size: 512
    class_num: 230278
 
# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.0025
  regularizer:
    name: 'L2'
    coeff: 0.00007

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: /home/aistudio/dataset/
      cls_label_path: /home/aistudio/dataset/train_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - RandCropImage:
            size: 224
        - RandFlipImage:
            flip_code: 1
        - NormalizeImage:
            scale: 0.00392157
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''

    sampler:
      name: DistributedBatchSampler
      batch_size: 1
      drop_last: False
      shuffle: True
    loader:
      num_workers: 4
      use_shared_memory: True
  Eval:
    dataset: 
      name: ImageNetDataset
      image_root: /home/aistudio/dataset/
      cls_label_path: /home/aistudio/dataset/test_list.txt
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            resize_short: 256
        - CropImage:
            size: 224
        - NormalizeImage:
            scale: 0.00392157
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
    sampler:
      name: DistributedBatchSampler
      batch_size: 1
      drop_last: False
      shuffle: False
    loader:
      num_workers: 4
      use_shared_memory: True
Metric:
  Train:
    - TopkAcc:
        topk: [1, 5]
  Eval:
    - TopkAcc:
        topk: [1, 5]

错误信息：
Traceback (most recent call last):
  File "tools/train.py", line 30, in <module>
    trainer = Trainer(config, mode="train")
  File "/home/aistudio/PaddleClas/ppcls/engine/trainer.py", line 75, in __init__
    self.model = build_model(self.config["Arch"])
  File "/home/aistudio/PaddleClas/ppcls/arch/__init__.py", line 36, in build_model
    arch = getattr(mod, model_type)(**config)
  File "/home/aistudio/PaddleClas/ppcls/arch/__init__.py", line 58, in __init__
    self.backbone = eval(backbone_name)(**backbone_config)
  File "/home/aistudio/PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 229, in MobileNetV1
    model = MobileNet(scale=1.0, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 114, in __init__
    padding=1)
  File "/home/aistudio/PaddleClas/ppcls/arch/backbone/legendary_models/mobilenet_v1.py", line 58, in __init__
    bias_attr=False)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
    default_initializer)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2895, in create_parameter
    initializer(param, self)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 719, in __call__
    stop_gradient=True)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 2925, in append_op
    kwargs.get("stop_gradient", False))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
OSError: (External)  Cuda error(2), out of memory.
  [Advise: The API call failed because it was unable to allocate enough memory to perform the requested operation. ] (at /paddle/paddle/fluid/platform/stream/cuda_stream.cc:49)
  [operator < gaussian_random > error]

![image](https://user-images.githubusercontent.com/58030051/133478199-3a1a28ec-ee25-4d25-89a1-67391623cac6.png)

数据集概览：
![image](https://user-images.githubusercontent.com/58030051/133478827-d54fae9b-6673-4e94-b097-60b228c67a70.png)

**Comment by Intsigstephon** [comment]
OSError: (External) Cuda error(2), out of memory. 
看提示，是显存不够了；可以试试把batch_size调小

**Comment by thomas-yanxin** [comment]
batch_size已经调成1了，依旧是这个报错

**Comment by cuicheng01** [comment]
注意到一个问题，修改试一下，
`Neck:
name: FC
embedding_size: 2048
class_num: 357
Head:
name: FC
embedding_size: 512
class_num: 230278`
这里的`Neck`中的`class_num`要与Head中的`embedding_size`相等，这里的命名确实有些问题，我们会在新版本更正
