### ISSUE TITLE
paddle1.8 GPU版本提示ModuleNotFoundError: No module named 'paddle.inference'

### ISSUE THREAD

**Issue by QHANT** [PaddlePaddle/PaddleClas#1343]
Windows 
Python3.6
CUDA10/cuDNN 7.6
Paddle1.8 GPu   (安装CPU版本没有问题)
运行单张图像识别
python python/predict_system.py -c configs/inference_product.yaml

提示
Traceback (most recent call last):
  File "python/predict_system.py", line 26, in <module>
    from python.predict_rec import RecPredictor
  File "E:\python\PaddleClas\deploy\python\predict_rec.py", line 23, in <module>
    from utils import logger
  File "E:\python\PaddleClas\deploy\utils\__init__.py", line 4, in <module>
    from . import predictor
  File "E:\python\PaddleClas\deploy\utils\predictor.py", line 21, in <module>
    from paddle.inference import Config
ModuleNotFoundError: No module named 'paddle.inference'
  求教大佬

**Comment by weisy11** [comment]
请升级paddle版本，建议2.1.3
