### ISSUE TITLE
修改识别花的案例，修改class_num后报错

### ISSUE THREAD

**Issue by ljcljc** [PaddlePaddle/PaddleClas#1408]
我的任务只需要区分4个类别，我修改识别花的案例后准备训练后报错，请问应该怎么修改其他参数？
配置文件里，class_num=4
以下是报错信息，请问还需要改什么参数，谢谢

Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "/Users//Documents/zhipei/vin2/PaddleClas/ppcls/engine/engine.py", line 265, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/Users//Documents/zhipei/vin2/PaddleClas/ppcls/engine/train/train.py", line 66, in train_epoch
    update_metric(engine, out, batch, batch_size)
  File "/Users//Documents/zhipei/vin2/PaddleClas/ppcls/engine/train/utils.py", line 24, in update_metric
    metric_dict = trainer.train_metric_func(out, batch[-1])
  File "/Users//Documents/zhipei/vin2/PaddleClas/ppcls/metric/__init__.py", line 45, in __call__
    metric_dict.update(metric_func(*args, **kwargs))
  File "/Users//miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 902, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/Users//Documents/zhipei/vin2/PaddleClas/ppcls/metric/metrics.py", line 40, in forward
    metric_dict["top{}".format(k)] = paddle.metric.accuracy(
  File "/Users//miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/metric/metrics.py", line 800, in accuracy
    topk_out, topk_indices = topk(input, k=k)
  File "/Users//miniconda3/envs/paddle_env/lib/python3.8/site-packages/paddle/fluid/layers/nn.py", line 5249, in topk
    out, indices = core.ops.top_k(input, 'k', _k)
ValueError: (InvalidArgument) input must have >= k columns
  [Hint: Expected input_dims[input_dims.size() - 1] >= k, but received input_dims[input_dims.size() - 1]:4 < k:5.] (at /home/Paddle/paddle/fluid/operators/top_k_op.cc:48)
  [operator < top_k > error]

**Comment by ljcljc** [comment]
已经在微信群解决，谢谢
