### ISSUE TITLE
服务器版检测模型到底是什么格式的模型呢

### ISSUE THREAD

**Issue by afterimagex** [PaddlePaddle/PaddleClas#1412]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：PaddleClas release/2.3
 2. 涉及的其他产品使用的版本号：paddledetection2.2
 3. 训练环境信息：无
  a. 具体操作系统，Windows
  b. Python版本号，如Python3.9
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by afterimagex** [comment]
下载下来的 ppyolov2_r50vd_dcn_mainbody_v1.0_infer.tar 解压后得到的文件没有后缀，用paddle.load无法读取

Traceback (most recent call last):
  File "D:\Coding\PaddlePaddle\PaddleDetection\tools\export_model.py", line 115, in <module>
    main()
  File "D:\Coding\PaddlePaddle\PaddleDetection\tools\export_model.py", line 111, in main
    run(FLAGS, cfg)
  File "D:\Coding\PaddlePaddle\PaddleDetection\tools\export_model.py", line 74, in run
    trainer.load_weights(cfg.weights)
  File "D:\Coding\PaddlePaddle\PaddleDetection\ppdet\engine\trainer.py", line 310, in load_weights
    load_pretrain_weight(self.model, weights)
  File "D:\Coding\PaddlePaddle\PaddleDetection\ppdet\utils\checkpoint.py", line 193, in load_pretrain_weight
    param_state_dict = paddle.load(weights_path)
  File "d:\Miniconda3\envs\paddle\lib\site-packages\paddle\framework\io.py", line 980, in load
    raise ValueError(
ValueError: `paddle.load` can not parse the file:D:\\Coding\\PaddlePaddle\\Weights\\ppyolov2_r50vd_dcn_mainbody_v1.0_infer\\ppyolov2_r50vd_dcn_mainbody_v1.0_infer.pdparams.

**Comment by cuicheng01** [comment]
您好，解压后的文件是什么样子呢？方便截图下吗？

**Comment by weisy11** [comment]
下载的文件是Inference预测部署模型，不是pretrained模型

**Comment by TingquanGao** [comment]
是在Windows下解压的吗？

**Comment by afterimagex** [comment]
@cuicheng01 
解压后是这样的
![image](https://user-images.githubusercontent.com/17892974/141236977-53ffd8ce-74d5-4de0-b782-a0b12a1b67d9.png)

下载下来后是这样的
![image](https://user-images.githubusercontent.com/17892974/141237014-ad1e76b0-7d7b-4cff-a4a6-0daaea70b9d9.png)

**Comment by afterimagex** [comment]
@TingquanGao 
是的

**Comment by TingquanGao** [comment]
您好！我们发现这个问题是因为部分解压缩软件无法正常解压 `.tar` 格式压缩包，我们在linux等平台上验证了使用命令 `tar xf xxx.tar` 是没问题的。

同时，我们也上传 `.zip` 格式压缩包，您可以再尝试一下：[ppyolov2_r50vd_dcn_mainbody_v1.0_infer](https://paddle-imagenet-models-name.bj.bcebos.com/dygraph/rec/models/inference/ppyolov2_r50vd_dcn_mainbody_v1.0_infer.zip)。
