### ISSUE TITLE
替换了自己训练的主体检测inference模型后报错

### ISSUE THREAD

**Issue by lululu86** [PaddlePaddle/PaddleClas#1489]
前辈们，请问paddleClasrelease/2.3替换了自己训练的主体检测inference模型报了这个错误怎么解决呢？（导出的主体检测的模型已验证无误，识别的索引库也重新建立了）

**Comment by lululu86** [comment]
Traceback (most recent call last):
  File "python/predict_system.py", line 144, in <module>
    main(config)
  File "python/predict_system.py", line 135, in main
    output = system_predictor.predict(img)
  File "python/predict_system.py", line 101, in predict
    results = self.det_predictor.predict(img)
  File "/PaddleClas/deploy/python/predict_det.py", line 144, in predict
    self.config["Global"]["labe_list"])
  File "/PaddleClas/deploy/python/predict_det.py", line 96, in parse_det_results
    label_name = label_list[class_id]
IndexError: list index out of range

**Comment by lululu86** [comment]
我自己训练了两类图A、B后导出为主体检测模型供paddleclas使用，其中A在paddleClas/deploy下执行python3 python/predict_system.py可正确输出结果，但B就会报上面那个错误。烦请各位前辈帮忙看看。

**Comment by Intsigstephon** [comment]
可以打印看下class_id值是多少，以及配置文件中Global.label_list值是否正确

**Comment by lululu86** [comment]
> 可以打印看下class_id值是多少，以及配置文件中Global.label_list值是否正确

修改label_list后正确，非常感谢。
