### ISSUE TITLE
ResNet50分布式训练遇到错误 Communicator of ring id 0 has not been initialized

### ISSUE THREAD

**Issue by Wong4j** [PaddlePaddle/PaddleClas#1567]
我在DGX上测试PaddleClas中的resnet50多卡训练。命令是python3 -m paddle.distributed.launch --gpus=0,1,2,3,4,5,6,7 ppcls/static/train.py -c ./ppcls/configs/ImageNet/ResNet/ResNet50_fp16.yaml

这个可以正常跑。但是相比NVIDIA DeeplearningExample中的Pytorch和MxNet的报告速度相差较大。所以我在找影响性能的原因。

我发现默认实现中，[这一行代码](https://github.com/PaddlePaddle/PaddleClas/blob/6b88819bd6aef7724b7778fcda80a3c5f6ddbba1/ppcls/static/train.py#L169)的if-else分支判断是走的else，也就是没有对train_prog进行compile。

所以我把这一部分改成了另一个分支，也就是需要对train_prog进行compile。

修改之后，train的ips速度确实提升了，但是在第一个train epoch结束后，开始第一次eval的时候会报错，`InvalidArgumentError: Communicator of ring id 0 has not been initialized.
      [Hint: Expected comm_map_.count(ring_id) > 0, but received comm_map_.count(ring_id):0 <= 0:0.] (at /paddle/paddle/fluid/platform/collective_helper.h:107)`

错误的意思应该是在eval阶段，在create_fetch中收集top1 top5 acc等metrics的时候，需要计算所有GPU的全局top acc求和。但是调用Allreduce的时候ring id没有初始化。

具体报错log如下，前半部分正常，截取了后半部分：

[2021/12/15 20:41:56] root INFO: epoch:0   train step:1230 lr: 0.100000, loss:  6.7377 top1:  0.0078 top5:  0.0391 batch_cost: 0.15717 s, reader_cost: 0.04373 s, ips: 814.41191 images/sec.
[2021/12/15 20:41:58] root INFO: epoch:0   train step:1240 lr: 0.100000, loss:  6.6998 top1:  0.0000 top5:  0.0391 batch_cost: 0.15721 s, reader_cost: 0.04367 s, ips: 814.18969 images/sec.
[2021/12/15 20:41:59] root INFO: epoch:0   train step:1250 lr: 0.100000, loss:  6.7115 top1:  0.0078 top5:  0.0156 batch_cost: 0.15700 s, reader_cost: 0.04344 s, ips: 815.29861 images/sec.
[2021/12/15 20:41:59] root INFO: END epoch:0   train  loss:  6.8997 top1:  0.0024 top5:  0.0102 batch_cost: 0.15695 s, reader_cost: 0.04337 s, batch_cost_sum: 195.87163 s, ips: 815.55457 images/sec.
I1215 20:41:59.617884 67119 fuse_pass_base.cc:57] ---  detected 16 subgraphs
Traceback (most recent call last):
  File "ppcls/static/train.py", line 272, in <module>
    main(args)
  File "ppcls/static/train.py", line 235, in main
    top1_acc = program.run(eval_dataloader, exe, compiled_eval_prog,
  File "/paddle/ppcls/static/program.py", line 394, in run
    metrics = exe.run(program=program,
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1246, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/lib/python3.8/dist-packages/six.py", line 719, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1234, in run
    return self._run_impl(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1380, in _run_impl
    return self._run_parallel(
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/executor.py", line 1049, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
ValueError: In user code:

    File "ppcls/static/train.py", line 272, in <module>
      main(args)
    File "ppcls/static/train.py", line 166, in main
      eval_fetchs, _, eval_feeds, _ = program.build(
    File "/paddle/ppcls/static/program.py", line 266, in build
      fetchs = create_fetchs(
    File "/paddle/ppcls/static/program.py", line 126, in create_fetchs
      paddle.distributed.all_reduce(
    File "/usr/local/lib/python3.8/dist-packages/paddle/distributed/collective.py", line 487, in all_reduce
      helper.append_op(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/layer_helper.py", line 43, in append_op
      return self.main_program.current_block().append_op(*args, **kwargs)
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 3178, in append_op
      op = Operator(
    File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 2224, in __init__
      for frame in traceback.extract_stack():

    InvalidArgumentError: Communicator of ring id 0 has not been initialized.
      [Hint: Expected comm_map_.count(ring_id) > 0, but received comm_map_.count(ring_id):0 <= 0:0.] (at /paddle/paddle/fluid/platform/collective_helper.h:107)
      [operator < c_allreduce_sum > error]
INFO 2021-12-15 20:42:00,821 launch_utils.py:319] terminate process group gid:67119
INFO 2021-12-15 20:42:00,821 launch_utils.py:319] terminate process group gid:67129
INFO 2021-12-15 20:42:00,821 launch_utils.py:319] terminate process group gid:67134
INFO 2021-12-15 20:42:00,821 launch_utils.py:319] terminate process group gid:67139
INFO 2021-12-15 20:42:00,821 launch_utils.py:319] terminate process group gid:67144
INFO 2021-12-15 20:42:00,821 launch_utils.py:319] terminate process group gid:67154
INFO 2021-12-15 20:42:04,826 launch_utils.py:340] terminate all the procs
ERROR 2021-12-15 20:42:04,826 launch_utils.py:601] ABORT!!! Out of all 8 trainers, the trainer process with rank=[1, 6] was aborted. Please check its log.
INFO 2021-12-15 20:42:08,830 launch_utils.py:340] terminate all the procs
INFO 2021-12-15 20:42:08,830 launch.py:304] Local processes completed.

**Comment by Intsigstephon** [comment]
好的，感谢反馈；我们后续会先复现一下您提的问题；动态图的方式有试过吗

**Comment by weisy11** [comment]
速度相差大是因为没有开dali，修复PR已提，过CI中
https://github.com/PaddlePaddle/PaddleClas/pull/1590

**Comment by Intsigstephon** [comment]
> 速度相差大是因为没有开dali，修复PR已提，过CI中

OK，了解

**Comment by zty-king** [comment]
> InvalidArgumentError: Communicator of ring id 0 has not been initialized.
>   [Hint: Expected comm_map_.count(ring_id) > 0, but received comm_map_.count(ring_id):0 <= 0:0.] (at /paddle/paddle/fluid/platform/collective_helper.h:107)
>   [operator < c_allreduce_sum > error]

请问你解决了吗
