### ISSUE TITLE
PP-shitu训练特征提取部分报错

### ISSUE THREAD

**Issue by zuoyou121** [PaddlePaddle/PaddleClas#1618]
1. PaddleClas release/2.3
 2. 训练环境信息：
  a. 具体操作系统，如Linux
  b. Python版本号，如Python3.7
 3. 报错如下：Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    engine = Engine(config, mode="train")
  File "/home/aistudio/PaddleClas/ppcls/engine/engine.py", line 138, in __init__
    self.device, self.use_dali)
  File "/home/aistudio/PaddleClas/ppcls/data/__init__.py", line 81, in build_dataloader
    dataset = eval(dataset_name)(**config_dataset)
  File "/home/aistudio/PaddleClas/ppcls/data/dataloader/vehicle_dataset.py", line 102, in __init__
    self._load_anno()
  File "/home/aistudio/PaddleClas/ppcls/data/dataloader/vehicle_dataset.py", line 116, in _load_anno
    self.cameras.append(np.int64(l[2]))
IndexError: list index out of range

**Comment by Intsigstephon** [comment]
错误提示是index越界了； vehicle dataset的数据格式，每行必须有3个值： imgpath, lable,  camera_id
