### ISSUE TITLE
KeyError: None

### ISSUE THREAD

**Issue by looooooooosee** [PaddlePaddle/PaddleClas#1675]
[2022/02/07 17:00:49] root INFO: Arch :
[2022/02/07 17:00:49] root INFO:     class_num : 200
[2022/02/07 17:00:49] root INFO:     name : MobileNetV3_large_x1_0
[2022/02/07 17:00:49] root INFO:     pretrained : False
[2022/02/07 17:00:49] root INFO: DataLoader :
[2022/02/07 17:00:49] root INFO:     Eval :
[2022/02/07 17:00:49] root INFO:         dataset :
[2022/02/07 17:00:49] root INFO:             cls_label_path : ./dataset/chengyu/val_list.txt
[2022/02/07 17:00:49] root INFO:             image_root : ./dataset/chengyu/
[2022/02/07 17:00:49] root INFO:             name : ImageNetDataset
[2022/02/07 17:00:49] root INFO:             transform_ops :
[2022/02/07 17:00:49] root INFO:                 DecodeImage :
[2022/02/07 17:00:49] root INFO:                     channel_first : False
[2022/02/07 17:00:49] root INFO:                     to_rgb : True
[2022/02/07 17:00:49] root INFO:                 ResizeImage :
[2022/02/07 17:00:49] root INFO:                     resize_short : 256
[2022/02/07 17:00:49] root INFO:                 CropImage :
[2022/02/07 17:00:49] root INFO:                     size : 224
[2022/02/07 17:00:49] root INFO:                 NormalizeImage :
[2022/02/07 17:00:49] root INFO:                     mean : [0.485, 0.456, 0.406]
[2022/02/07 17:00:49] root INFO:                     order :
[2022/02/07 17:00:49] root INFO:                     scale : 1.0/255.0
[2022/02/07 17:00:49] root INFO:                     std : [0.229, 0.224, 0.225]
[2022/02/07 17:00:49] root INFO:         loader :
[2022/02/07 17:00:49] root INFO:             num_workers : 0
[2022/02/07 17:00:49] root INFO:             use_shared_memory : True
[2022/02/07 17:00:49] root INFO:         sampler :
[2022/02/07 17:00:49] root INFO:             batch_size : 64
[2022/02/07 17:00:49] root INFO:             drop_last : False
[2022/02/07 17:00:49] root INFO:             name : DistributedBatchSampler
[2022/02/07 17:00:49] root INFO:             shuffle : False
[2022/02/07 17:00:49] root INFO:     Train :
[2022/02/07 17:00:49] root INFO:         dataset :
[2022/02/07 17:00:49] root INFO:             cls_label_path : ./dataset/chengyu/train_list.txt
[2022/02/07 17:00:49] root INFO:             image_root : ./dataset/chengyu/
[2022/02/07 17:00:49] root INFO:             name : ImageNetDataset
[2022/02/07 17:00:49] root INFO:             transform_ops :
[2022/02/07 17:00:49] root INFO:                 DecodeImage :
[2022/02/07 17:00:49] root INFO:                     channel_first : False
[2022/02/07 17:00:49] root INFO:                     to_rgb : True
[2022/02/07 17:00:49] root INFO:                 RandCropImage :
[2022/02/07 17:00:49] root INFO:                     size : 224
[2022/02/07 17:00:49] root INFO:                 RandFlipImage :
[2022/02/07 17:00:49] root INFO:                     flip_code : 1
[2022/02/07 17:00:49] root INFO:                 NormalizeImage :
[2022/02/07 17:00:49] root INFO:                     mean : [0.485, 0.456, 0.406]
[2022/02/07 17:00:49] root INFO:                     order :
[2022/02/07 17:00:49] root INFO:                     scale : 1.0/255.0
[2022/02/07 17:00:49] root INFO:                     std : [0.229, 0.224, 0.225]
[2022/02/07 17:00:49] root INFO:         loader :
[2022/02/07 17:00:49] root INFO:             num_workers : 0
[2022/02/07 17:00:49] root INFO:             use_shared_memory : True
[2022/02/07 17:00:49] root INFO:         sampler :
[2022/02/07 17:00:49] root INFO:             batch_size : 32
[2022/02/07 17:00:49] root INFO:             drop_last : False
[2022/02/07 17:00:49] root INFO:             name : DistributedBatchSampler
[2022/02/07 17:00:49] root INFO:             shuffle : True
[2022/02/07 17:00:49] root INFO: Global :
[2022/02/07 17:00:49] root INFO:     checkpoints : None
[2022/02/07 17:00:49] root INFO:     device : gpu
[2022/02/07 17:00:49] root INFO:     epochs : 80
[2022/02/07 17:00:49] root INFO:     eval_during_train : True
[2022/02/07 17:00:49] root INFO:     eval_interval : 1
[2022/02/07 17:00:49] root INFO:     image_shape : [3, 224, 224]
[2022/02/07 17:00:49] root INFO:     output_dir : ./output/
[2022/02/07 17:00:49] root INFO:     pretrained_model : None
[2022/02/07 17:00:49] root INFO:     print_batch_step : 10
[2022/02/07 17:00:49] root INFO:     save_inference_dir : ./inference
[2022/02/07 17:00:49] root INFO:     save_interval : 1
[2022/02/07 17:00:49] root INFO:     use_visualdl : False
[2022/02/07 17:00:49] root INFO: Infer :
[2022/02/07 17:00:49] root INFO:     PostProcess :
[2022/02/07 17:00:49] root INFO:         class_id_map_file : ./dataset/chengyu/flowers102_label_list.txt
[2022/02/07 17:00:49] root INFO:         name : Topk
[2022/02/07 17:00:49] root INFO:         topk : 5
[2022/02/07 17:00:49] root INFO:     batch_size : 10
[2022/02/07 17:00:49] root INFO:     infer_imgs : docs/images/whl/demo.jpg
[2022/02/07 17:00:49] root INFO:     transforms :
[2022/02/07 17:00:49] root INFO:         DecodeImage :
[2022/02/07 17:00:49] root INFO:             channel_first : False
[2022/02/07 17:00:49] root INFO:             to_rgb : True
[2022/02/07 17:00:49] root INFO:         ResizeImage :
[2022/02/07 17:00:49] root INFO:             resize_short : 256
[2022/02/07 17:00:49] root INFO:         CropImage :
[2022/02/07 17:00:49] root INFO:             size : 224
[2022/02/07 17:00:49] root INFO:         NormalizeImage :
[2022/02/07 17:00:49] root INFO:             mean : [0.485, 0.456, 0.406]
[2022/02/07 17:00:49] root INFO:             order :
[2022/02/07 17:00:49] root INFO:             scale : 1.0/255.0
[2022/02/07 17:00:49] root INFO:             std : [0.229, 0.224, 0.225]
[2022/02/07 17:00:49] root INFO:         ToCHWImage : None
[2022/02/07 17:00:49] root INFO: Loss :
[2022/02/07 17:00:49] root INFO:     Eval :
[2022/02/07 17:00:49] root INFO:         CELoss :
[2022/02/07 17:00:49] root INFO:             weight : 1.0
[2022/02/07 17:00:49] root INFO:     Train :
[2022/02/07 17:00:49] root INFO:         CELoss :
[2022/02/07 17:00:49] root INFO:             weight : 1.0
[2022/02/07 17:00:49] root INFO: Metric :
[2022/02/07 17:00:49] root INFO:     Eval :
[2022/02/07 17:00:49] root INFO:         TopkAcc :
[2022/02/07 17:00:49] root INFO:             topk : [1, 5]
[2022/02/07 17:00:49] root INFO:     Train :
[2022/02/07 17:00:49] root INFO:         TopkAcc :
[2022/02/07 17:00:49] root INFO:             topk : [1, 5]
[2022/02/07 17:00:49] root INFO: Optimizer :
[2022/02/07 17:00:49] root INFO:     lr :
[2022/02/07 17:00:49] root INFO:         last_epoch : -1
[2022/02/07 17:00:49] root INFO:         learning_rate : 0.00375
[2022/02/07 17:00:49] root INFO:         name : Cosine
[2022/02/07 17:00:49] root INFO:         warmup_epoch : 5
[2022/02/07 17:00:49] root INFO:     momentum : 0.9
[2022/02/07 17:00:49] root INFO:     name : Momentum
[2022/02/07 17:00:49] root INFO:     regularizer :
[2022/02/07 17:00:49] root INFO:         coeff : 1e-06
[2022/02/07 17:00:49] root INFO:         name : L2
[2022/02/07 17:00:49] root INFO: profiler_options : None
[2022/02/07 17:00:49] root INFO: train with paddle 2.2.1 and device CUDAPlace(0)
W0207 17:00:49.699499 75104 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.5, Runtime API Version: 11.2
W0207 17:00:49.708310 75104 device_context.cc:465] device: 0, cuDNN Version: 8.1.
W0207 17:00:50.710325 75104 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compa
tible CUDNN version.
[2022/02/07 17:00:51] root INFO: [Train][Epoch 1/80][Iter: 0/19]lr: 0.00004, top1: 0.00000, top5: 0.00000, CELoss: 5.37058, loss: 5.37058, batch_cost: 0.60833s, reader_cost: 0.06835, ips: 52.60268 images/sec, eta: 0:15:24
[2022/02/07 17:00:53] root INFO: [Train][Epoch 1/80][Iter: 10/19]lr: 0.00043, top1: 0.00852, top5: 0.03409, CELoss: 5.33000, loss: 5.33000, batch_cost: 0.17235s, reader_cost: 0.00000, ips: 185.66441 images/sec, eta: 0:04:20
[2022/02/07 17:00:54] root INFO: [Train][Epoch 1/80][Avg]top1: 0.00868, top5: 0.03299, CELoss: 5.31905, loss: 5.31905
True
1
[2022/02/07 17:00:54] root INFO: [Eval][Epoch 1][Avg]
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "D:\A_paddle\PaddleClas\ppcls\engine\engine.py", line 283, in train
    acc = self.eval(epoch_id)
  File "D:\Anaconda\envs\paddledet\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda\envs\paddledet\lib\site-packages\paddle\fluid\dygraph\base.py", line 331, in _decorate_function
    return func(*args, **kwargs)
  File "D:\A_paddle\PaddleClas\ppcls\engine\engine.py", line 329, in eval
    eval_result = self.eval_func(self, epoch_id)
  File "D:\A_paddle\PaddleClas\ppcls\engine\evaluation\classification.py", line 149, in classification_eval
    return output_info[metric_key].avg
KeyError: None

上面的问题可能性有哪些？  分类任务  我的flowers102_label_list.txt 对应的是中文的  不是  0 apple 是 0 苹果

**Comment by looooooooosee** [comment]
> [2022/02/07 17:00:49] root INFO: Arch : [2022/02/07 17:00:49] root INFO: class_num : 200 [2022/02/07 17:00:49] root INFO: name : MobileNetV3_large_x1_0 [2022/02/07 17:00:49] root INFO: pretrained : False [2022/02/07 17:00:49] root INFO: DataLoader : [2022/02/07 17:00:49] root INFO: Eval : [2022/02/07 17:00:49] root INFO: dataset : [2022/02/07 17:00:49] root INFO: cls_label_path : ./dataset/chengyu/val_list.txt [2022/02/07 17:00:49] root INFO: image_root : ./dataset/chengyu/ [2022/02/07 17:00:49] root INFO: name : ImageNetDataset [2022/02/07 17:00:49] root INFO: transform_ops : [2022/02/07 17:00:49] root INFO: DecodeImage : [2022/02/07 17:00:49] root INFO: channel_first : False [2022/02/07 17:00:49] root INFO: to_rgb : True [2022/02/07 17:00:49] root INFO: ResizeImage : [2022/02/07 17:00:49] root INFO: resize_short : 256 [2022/02/07 17:00:49] root INFO: CropImage : [2022/02/07 17:00:49] root INFO: size : 224 [2022/02/07 17:00:49] root INFO: NormalizeImage : [2022/02/07 17:00:49] root INFO: mean : [0.485, 0.456, 0.406] [2022/02/07 17:00:49] root INFO: order : [2022/02/07 17:00:49] root INFO: scale : 1.0/255.0 [2022/02/07 17:00:49] root INFO: std : [0.229, 0.224, 0.225] [2022/02/07 17:00:49] root INFO: loader : [2022/02/07 17:00:49] root INFO: num_workers : 0 [2022/02/07 17:00:49] root INFO: use_shared_memory : True [2022/02/07 17:00:49] root INFO: sampler : [2022/02/07 17:00:49] root INFO: batch_size : 64 [2022/02/07 17:00:49] root INFO: drop_last : False [2022/02/07 17:00:49] root INFO: name : DistributedBatchSampler [2022/02/07 17:00:49] root INFO: shuffle : False [2022/02/07 17:00:49] root INFO: Train : [2022/02/07 17:00:49] root INFO: dataset : [2022/02/07 17:00:49] root INFO: cls_label_path : ./dataset/chengyu/train_list.txt [2022/02/07 17:00:49] root INFO: image_root : ./dataset/chengyu/ [2022/02/07 17:00:49] root INFO: name : ImageNetDataset [2022/02/07 17:00:49] root INFO: transform_ops : [2022/02/07 17:00:49] root INFO: DecodeImage : [2022/02/07 17:00:49] root INFO: channel_first : False [2022/02/07 17:00:49] root INFO: to_rgb : True [2022/02/07 17:00:49] root INFO: RandCropImage : [2022/02/07 17:00:49] root INFO: size : 224 [2022/02/07 17:00:49] root INFO: RandFlipImage : [2022/02/07 17:00:49] root INFO: flip_code : 1 [2022/02/07 17:00:49] root INFO: NormalizeImage : [2022/02/07 17:00:49] root INFO: mean : [0.485, 0.456, 0.406] [2022/02/07 17:00:49] root INFO: order : [2022/02/07 17:00:49] root INFO: scale : 1.0/255.0 [2022/02/07 17:00:49] root INFO: std : [0.229, 0.224, 0.225] [2022/02/07 17:00:49] root INFO: loader : [2022/02/07 17:00:49] root INFO: num_workers : 0 [2022/02/07 17:00:49] root INFO: use_shared_memory : True [2022/02/07 17:00:49] root INFO: sampler : [2022/02/07 17:00:49] root INFO: batch_size : 32 [2022/02/07 17:00:49] root INFO: drop_last : False [2022/02/07 17:00:49] root INFO: name : DistributedBatchSampler [2022/02/07 17:00:49] root INFO: shuffle : True [2022/02/07 17:00:49] root INFO: Global : [2022/02/07 17:00:49] root INFO: checkpoints : None [2022/02/07 17:00:49] root INFO: device : gpu [2022/02/07 17:00:49] root INFO: epochs : 80 [2022/02/07 17:00:49] root INFO: eval_during_train : True [2022/02/07 17:00:49] root INFO: eval_interval : 1 [2022/02/07 17:00:49] root INFO: image_shape : [3, 224, 224] [2022/02/07 17:00:49] root INFO: output_dir : ./output/ [2022/02/07 17:00:49] root INFO: pretrained_model : None [2022/02/07 17:00:49] root INFO: print_batch_step : 10 [2022/02/07 17:00:49] root INFO: save_inference_dir : ./inference [2022/02/07 17:00:49] root INFO: save_interval : 1 [2022/02/07 17:00:49] root INFO: use_visualdl : False [2022/02/07 17:00:49] root INFO: Infer : [2022/02/07 17:00:49] root INFO: PostProcess : [2022/02/07 17:00:49] root INFO: class_id_map_file : ./dataset/chengyu/flowers102_label_list.txt [2022/02/07 17:00:49] root INFO: name : Topk [2022/02/07 17:00:49] root INFO: topk : 5 [2022/02/07 17:00:49] root INFO: batch_size : 10 [2022/02/07 17:00:49] root INFO: infer_imgs : docs/images/whl/demo.jpg [2022/02/07 17:00:49] root INFO: transforms : [2022/02/07 17:00:49] root INFO: DecodeImage : [2022/02/07 17:00:49] root INFO: channel_first : False [2022/02/07 17:00:49] root INFO: to_rgb : True [2022/02/07 17:00:49] root INFO: ResizeImage : [2022/02/07 17:00:49] root INFO: resize_short : 256 [2022/02/07 17:00:49] root INFO: CropImage : [2022/02/07 17:00:49] root INFO: size : 224 [2022/02/07 17:00:49] root INFO: NormalizeImage : [2022/02/07 17:00:49] root INFO: mean : [0.485, 0.456, 0.406] [2022/02/07 17:00:49] root INFO: order : [2022/02/07 17:00:49] root INFO: scale : 1.0/255.0 [2022/02/07 17:00:49] root INFO: std : [0.229, 0.224, 0.225] [2022/02/07 17:00:49] root INFO: ToCHWImage : None [2022/02/07 17:00:49] root INFO: Loss : [2022/02/07 17:00:49] root INFO: Eval : [2022/02/07 17:00:49] root INFO: CELoss : [2022/02/07 17:00:49] root INFO: weight : 1.0 [2022/02/07 17:00:49] root INFO: Train : [2022/02/07 17:00:49] root INFO: CELoss : [2022/02/07 17:00:49] root INFO: weight : 1.0 [2022/02/07 17:00:49] root INFO: Metric : [2022/02/07 17:00:49] root INFO: Eval : [2022/02/07 17:00:49] root INFO: TopkAcc : [2022/02/07 17:00:49] root INFO: topk : [1, 5] [2022/02/07 17:00:49] root INFO: Train : [2022/02/07 17:00:49] root INFO: TopkAcc : [2022/02/07 17:00:49] root INFO: topk : [1, 5] [2022/02/07 17:00:49] root INFO: Optimizer : [2022/02/07 17:00:49] root INFO: lr : [2022/02/07 17:00:49] root INFO: last_epoch : -1 [2022/02/07 17:00:49] root INFO: learning_rate : 0.00375 [2022/02/07 17:00:49] root INFO: name : Cosine [2022/02/07 17:00:49] root INFO: warmup_epoch : 5 [2022/02/07 17:00:49] root INFO: momentum : 0.9 [2022/02/07 17:00:49] root INFO: name : Momentum [2022/02/07 17:00:49] root INFO: regularizer : [2022/02/07 17:00:49] root INFO: coeff : 1e-06 [2022/02/07 17:00:49] root INFO: name : L2 [2022/02/07 17:00:49] root INFO: profiler_options : None [2022/02/07 17:00:49] root INFO: train with paddle 2.2.1 and device CUDAPlace(0) W0207 17:00:49.699499 75104 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.5, Runtime API Version: 11.2 W0207 17:00:49.708310 75104 device_context.cc:465] device: 0, cuDNN Version: 8.1. W0207 17:00:50.710325 75104 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compa tible CUDNN version. [2022/02/07 17:00:51] root INFO: [Train][Epoch 1/80][Iter: 0/19]lr: 0.00004, top1: 0.00000, top5: 0.00000, CELoss: 5.37058, loss: 5.37058, batch_cost: 0.60833s, reader_cost: 0.06835, ips: 52.60268 images/sec, eta: 0:15:24 [2022/02/07 17:00:53] root INFO: [Train][Epoch 1/80][Iter: 10/19]lr: 0.00043, top1: 0.00852, top5: 0.03409, CELoss: 5.33000, loss: 5.33000, batch_cost: 0.17235s, reader_cost: 0.00000, ips: 185.66441 images/sec, eta: 0:04:20 [2022/02/07 17:00:54] root INFO: [Train][Epoch 1/80][Avg]top1: 0.00868, top5: 0.03299, CELoss: 5.31905, loss: 5.31905 True 1 [2022/02/07 17:00:54] root INFO: [Eval][Epoch 1][Avg] Traceback (most recent call last): File "tools/train.py", line 32, in engine.train() File "D:\A_paddle\PaddleClas\ppcls\engine\engine.py", line 283, in train acc = self.eval(epoch_id) File "D:\Anaconda\envs\paddledet\lib\site-packages\decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "D:\Anaconda\envs\paddledet\lib\site-packages\paddle\fluid\dygraph\base.py", line 331, in _decorate_function return func(*args, **kwargs) File "D:\A_paddle\PaddleClas\ppcls\engine\engine.py", line 329, in eval eval_result = self.eval_func(self, epoch_id) File "D:\A_paddle\PaddleClas\ppcls\engine\evaluation\classification.py", line 149, in classification_eval return output_info[metric_key].avg KeyError: None
> 
> 上面的问题可能性有哪些？ 分类任务 我的flowers102_label_list.txt 对应的是中文的 不是 0 apple 是 0 苹果



> [2022/02/07 17:00:49] root INFO: Arch : [2022/02/07 17:00:49] root INFO: class_num : 200 [2022/02/07 17:00:49] root INFO: name : MobileNetV3_large_x1_0 [2022/02/07 17:00:49] root INFO: pretrained : False [2022/02/07 17:00:49] root INFO: DataLoader : [2022/02/07 17:00:49] root INFO: Eval : [2022/02/07 17:00:49] root INFO: dataset : [2022/02/07 17:00:49] root INFO: cls_label_path : ./dataset/chengyu/val_list.txt [2022/02/07 17:00:49] root INFO: image_root : ./dataset/chengyu/ [2022/02/07 17:00:49] root INFO: name : ImageNetDataset [2022/02/07 17:00:49] root INFO: transform_ops : [2022/02/07 17:00:49] root INFO: DecodeImage : [2022/02/07 17:00:49] root INFO: channel_first : False [2022/02/07 17:00:49] root INFO: to_rgb : True [2022/02/07 17:00:49] root INFO: ResizeImage : [2022/02/07 17:00:49] root INFO: resize_short : 256 [2022/02/07 17:00:49] root INFO: CropImage : [2022/02/07 17:00:49] root INFO: size : 224 [2022/02/07 17:00:49] root INFO: NormalizeImage : [2022/02/07 17:00:49] root INFO: mean : [0.485, 0.456, 0.406] [2022/02/07 17:00:49] root INFO: order : [2022/02/07 17:00:49] root INFO: scale : 1.0/255.0 [2022/02/07 17:00:49] root INFO: std : [0.229, 0.224, 0.225] [2022/02/07 17:00:49] root INFO: loader : [2022/02/07 17:00:49] root INFO: num_workers : 0 [2022/02/07 17:00:49] root INFO: use_shared_memory : True [2022/02/07 17:00:49] root INFO: sampler : [2022/02/07 17:00:49] root INFO: batch_size : 64 [2022/02/07 17:00:49] root INFO: drop_last : False [2022/02/07 17:00:49] root INFO: name : DistributedBatchSampler [2022/02/07 17:00:49] root INFO: shuffle : False [2022/02/07 17:00:49] root INFO: Train : [2022/02/07 17:00:49] root INFO: dataset : [2022/02/07 17:00:49] root INFO: cls_label_path : ./dataset/chengyu/train_list.txt [2022/02/07 17:00:49] root INFO: image_root : ./dataset/chengyu/ [2022/02/07 17:00:49] root INFO: name : ImageNetDataset [2022/02/07 17:00:49] root INFO: transform_ops : [2022/02/07 17:00:49] root INFO: DecodeImage : [2022/02/07 17:00:49] root INFO: channel_first : False [2022/02/07 17:00:49] root INFO: to_rgb : True [2022/02/07 17:00:49] root INFO: RandCropImage : [2022/02/07 17:00:49] root INFO: size : 224 [2022/02/07 17:00:49] root INFO: RandFlipImage : [2022/02/07 17:00:49] root INFO: flip_code : 1 [2022/02/07 17:00:49] root INFO: NormalizeImage : [2022/02/07 17:00:49] root INFO: mean : [0.485, 0.456, 0.406] [2022/02/07 17:00:49] root INFO: order : [2022/02/07 17:00:49] root INFO: scale : 1.0/255.0 [2022/02/07 17:00:49] root INFO: std : [0.229, 0.224, 0.225] [2022/02/07 17:00:49] root INFO: loader : [2022/02/07 17:00:49] root INFO: num_workers : 0 [2022/02/07 17:00:49] root INFO: use_shared_memory : True [2022/02/07 17:00:49] root INFO: sampler : [2022/02/07 17:00:49] root INFO: batch_size : 32 [2022/02/07 17:00:49] root INFO: drop_last : False [2022/02/07 17:00:49] root INFO: name : DistributedBatchSampler [2022/02/07 17:00:49] root INFO: shuffle : True [2022/02/07 17:00:49] root INFO: Global : [2022/02/07 17:00:49] root INFO: checkpoints : None [2022/02/07 17:00:49] root INFO: device : gpu [2022/02/07 17:00:49] root INFO: epochs : 80 [2022/02/07 17:00:49] root INFO: eval_during_train : True [2022/02/07 17:00:49] root INFO: eval_interval : 1 [2022/02/07 17:00:49] root INFO: image_shape : [3, 224, 224] [2022/02/07 17:00:49] root INFO: output_dir : ./output/ [2022/02/07 17:00:49] root INFO: pretrained_model : None [2022/02/07 17:00:49] root INFO: print_batch_step : 10 [2022/02/07 17:00:49] root INFO: save_inference_dir : ./inference [2022/02/07 17:00:49] root INFO: save_interval : 1 [2022/02/07 17:00:49] root INFO: use_visualdl : False [2022/02/07 17:00:49] root INFO: Infer : [2022/02/07 17:00:49] root INFO: PostProcess : [2022/02/07 17:00:49] root INFO: class_id_map_file : ./dataset/chengyu/flowers102_label_list.txt [2022/02/07 17:00:49] root INFO: name : Topk [2022/02/07 17:00:49] root INFO: topk : 5 [2022/02/07 17:00:49] root INFO: batch_size : 10 [2022/02/07 17:00:49] root INFO: infer_imgs : docs/images/whl/demo.jpg [2022/02/07 17:00:49] root INFO: transforms : [2022/02/07 17:00:49] root INFO: DecodeImage : [2022/02/07 17:00:49] root INFO: channel_first : False [2022/02/07 17:00:49] root INFO: to_rgb : True [2022/02/07 17:00:49] root INFO: ResizeImage : [2022/02/07 17:00:49] root INFO: resize_short : 256 [2022/02/07 17:00:49] root INFO: CropImage : [2022/02/07 17:00:49] root INFO: size : 224 [2022/02/07 17:00:49] root INFO: NormalizeImage : [2022/02/07 17:00:49] root INFO: mean : [0.485, 0.456, 0.406] [2022/02/07 17:00:49] root INFO: order : [2022/02/07 17:00:49] root INFO: scale : 1.0/255.0 [2022/02/07 17:00:49] root INFO: std : [0.229, 0.224, 0.225] [2022/02/07 17:00:49] root INFO: ToCHWImage : None [2022/02/07 17:00:49] root INFO: Loss : [2022/02/07 17:00:49] root INFO: Eval : [2022/02/07 17:00:49] root INFO: CELoss : [2022/02/07 17:00:49] root INFO: weight : 1.0 [2022/02/07 17:00:49] root INFO: Train : [2022/02/07 17:00:49] root INFO: CELoss : [2022/02/07 17:00:49] root INFO: weight : 1.0 [2022/02/07 17:00:49] root INFO: Metric : [2022/02/07 17:00:49] root INFO: Eval : [2022/02/07 17:00:49] root INFO: TopkAcc : [2022/02/07 17:00:49] root INFO: topk : [1, 5] [2022/02/07 17:00:49] root INFO: Train : [2022/02/07 17:00:49] root INFO: TopkAcc : [2022/02/07 17:00:49] root INFO: topk : [1, 5] [2022/02/07 17:00:49] root INFO: Optimizer : [2022/02/07 17:00:49] root INFO: lr : [2022/02/07 17:00:49] root INFO: last_epoch : -1 [2022/02/07 17:00:49] root INFO: learning_rate : 0.00375 [2022/02/07 17:00:49] root INFO: name : Cosine [2022/02/07 17:00:49] root INFO: warmup_epoch : 5 [2022/02/07 17:00:49] root INFO: momentum : 0.9 [2022/02/07 17:00:49] root INFO: name : Momentum [2022/02/07 17:00:49] root INFO: regularizer : [2022/02/07 17:00:49] root INFO: coeff : 1e-06 [2022/02/07 17:00:49] root INFO: name : L2 [2022/02/07 17:00:49] root INFO: profiler_options : None [2022/02/07 17:00:49] root INFO: train with paddle 2.2.1 and device CUDAPlace(0) W0207 17:00:49.699499 75104 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 6.1, Driver API Version: 11.5, Runtime API Version: 11.2 W0207 17:00:49.708310 75104 device_context.cc:465] device: 0, cuDNN Version: 8.1. W0207 17:00:50.710325 75104 device_context.h:397] WARNING: device: 0. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compa tible CUDNN version. [2022/02/07 17:00:51] root INFO: [Train][Epoch 1/80][Iter: 0/19]lr: 0.00004, top1: 0.00000, top5: 0.00000, CELoss: 5.37058, loss: 5.37058, batch_cost: 0.60833s, reader_cost: 0.06835, ips: 52.60268 images/sec, eta: 0:15:24 [2022/02/07 17:00:53] root INFO: [Train][Epoch 1/80][Iter: 10/19]lr: 0.00043, top1: 0.00852, top5: 0.03409, CELoss: 5.33000, loss: 5.33000, batch_cost: 0.17235s, reader_cost: 0.00000, ips: 185.66441 images/sec, eta: 0:04:20 [2022/02/07 17:00:54] root INFO: [Train][Epoch 1/80][Avg]top1: 0.00868, top5: 0.03299, CELoss: 5.31905, loss: 5.31905 True 1 [2022/02/07 17:00:54] root INFO: [Eval][Epoch 1][Avg] Traceback (most recent call last): File "tools/train.py", line 32, in engine.train() File "D:\A_paddle\PaddleClas\ppcls\engine\engine.py", line 283, in train acc = self.eval(epoch_id) File "D:\Anaconda\envs\paddledet\lib\site-packages\decorator.py", line 232, in fun return caller(func, *(extras + args), **kw) File "D:\Anaconda\envs\paddledet\lib\site-packages\paddle\fluid\dygraph\base.py", line 331, in _decorate_function return func(*args, **kwargs) File "D:\A_paddle\PaddleClas\ppcls\engine\engine.py", line 329, in eval eval_result = self.eval_func(self, epoch_id) File "D:\A_paddle\PaddleClas\ppcls\engine\evaluation\classification.py", line 149, in classification_eval return output_info[metric_key].avg KeyError: None
> 
> 上面的问题可能性有哪些？ 分类任务 我的flowers102_label_list.txt 对应的是中文的 不是 0 apple 是 0 苹果

**Comment by KyleWang-Hunter** [comment]
我也遇到过同样的问题，请问你解决了吗？
