### ISSUE TITLE
训练reid在eval阶段异常

### ISSUE THREAD

**Issue by zouhan6806504** [PaddlePaddle/PaddleClas#1676]
用的是aistudio环境，ppcls2.3
报错信息

Traceback (most recent call last):
  File "/home/aistudio/PaddleClas-release-2.3/tools/train_reid.py", line 33, in <module>
    engine.train()
  File "/home/aistudio/PaddleClas-release-2.3/ppcls/engine/engine_reid.py", line 306, in train
    acc = self.eval(epoch_id)
  File "<decorator-gen-293>", line 2, in eval
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/PaddleClas-release-2.3/ppcls/engine/engine_reid.py", line 352, in eval
    eval_result = self.eval_func(self, epoch_id)
  File "/home/aistudio/PaddleClas-release-2.3/ppcls/engine/evaluation/retrieval.py", line 70, in retrieval_eval
    gallery_img_id, keep_mask)
  File "/home/aistudio/PaddleClas-release-2.3/ppcls/metric/__init__.py", line 45, in __call__
    metric_dict.update(metric_func(*args, **kwargs))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleClas-release-2.3/ppcls/metric/metrics.py", line 81, in forward       这里行数因为有print和原始不一样
    equal_flag = paddle.index_select(equal_flag, num_rel_index, axis=0)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/tensor/search.py", line 306, in index_select
    return _C_ops.index_select(x, index, 'dim', axis)
ValueError: (InvalidArgument) The length of Input(Index) can't be 0.
  [Hint: Expected index_dim[0] != 0 == true, but received index_dim[0] != 0:0 != true:1.] (at /paddle/paddle/fluid/operators/index_select_op.cc:59)
  [operator < index_select > error]

打印了metrics里面的num_rel_index.shape：得到输出num_rel_index [0]

print('num_rel_index', num_rel_index.shape)
equal_flag = paddle.index_select(equal_flag, num_rel_index, axis=0)

另外如果想计算mAP@100或者mAP@50，要如何配置？

**Comment by RainFrost1** [comment]
能否给一个demo，我们debug查一下。或者简单描述下数据准备方式及训练命令

**Comment by zouhan6806504** [comment]
> 能否给一个demo，我们debug查一下。或者简单描述下数据准备方式及训练命令

当equal_flag全部为False，也就是模型一个都没命中的时候，就会出现这种情况

**Comment by RainFrost1** [comment]
> 
能否指一下具体哪个文件的哪行呢？我debug一下

**Comment by zouhan6806504** [comment]
> > 
> 
> 能否指一下具体哪个文件的哪行呢？我debug一下

ppcls.metric.metrics.py
mAP函数
equal_flag = paddle.equal(choosen_label, query_img_id)
当equal_flag全false就会这样

**Comment by RainFrost1** [comment]
> 

好的，我们这几天debug修复下

**Comment by RainFrost1** [comment]
已经修复 #1684 
另外mAP@100， mAP@50的情况，暂时还没有统一支持，不过可以暂时修改代码得到。将[此行代码](https://github.com/RainFrost1/PaddleClas/blob/e6b1af1d29f2abf4a383d97e7ab976ab42f03fdd/ppcls/metric/metrics.py#L82)中acc_sum（第二个维度， axis=1）截断到100或者50就可以得到
