### ISSUE TITLE
多标签训练，MobileNetV1 改为 SE_ResNeXt50_vd_32x4d，Train环节正常，Eval环节报错。

### ISSUE THREAD

**Issue by ChrisMengxl** [PaddlePaddle/PaddleClas#1724]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如**Linux**/Windows/MacOS
  b. Python版本号，如Python3.6/**7**/8     **paddlepaddle 2.2.2.post101**  **PaddleClas 2.3**
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

[参考：多标签分类 quick start ](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_multilabel_classification.md)  仅 MobileNetV1 改为 SE_ResNeXt50_vd_32x4d ，使用预训练，batch_size : 128，在Aistudio训练，Train环节正常，Eval环节报错如下：

```
[2022/03/02 23:16:51] root INFO: [Train][Epoch 5/100][Iter: 130/137]lr: 0.09912, AccuracyScore: 0.95130, MultiLabelLoss: 0.12439, loss: 0.12439, batch_cost: 0.67130s, reader_cost: 0.00026, ips: 190.67534 images/sec, eta: 2:25:41
[2022/03/02 23:16:54] root INFO: [Train][Epoch 5/100][Avg]AccuracyScore: 0.95130, MultiLabelLoss: 0.12436, loss: 0.12436
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "/home/aistudio/PaddleClas/ppcls/engine/engine.py", line 306, in train
    acc = self.eval(epoch_id)
  File "<decorator-gen-293>", line 2, in eval
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 351, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/engine/engine.py", line 352, in eval
    eval_result = self.eval_func(self, epoch_id)
  File "/home/aistudio/PaddleClas/ppcls/engine/evaluation/classification.py", line 81, in classification_eval
    loss_dict = engine.eval_loss_func(out, batch[1])
  File "/home/aistudio/PaddleClas/ppcls/loss/__init__.py", line 51, in __call__
    loss = self.loss_func[0](input, batch)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/loss/multilabelloss.py", line 41, in forward
    loss = self._binary_crossentropy(x, target, class_num)
  File "/home/aistudio/PaddleClas/ppcls/loss/multilabelloss.py", line 33, in _binary_crossentropy
    logit=input, label=target)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/functional/loss.py", line 257, in binary_cross_entropy_with_logits
    out = _C_ops.sigmoid_cross_entropy_with_logits(logit, label)
ValueError: (InvalidArgument) The DataType of sigmoid_cross_entropy_with_logits Op's duplicable Variable X must be consistent. The current variable type is (float), but the previous variable type is (int64_t). (at /paddle/paddle/fluid/framework/operator.cc:1604)
  [operator < sigmoid_cross_entropy_with_logits > error]
```

**Comment by ChrisMengxl** [comment]
同样 改为 ResNeXt50_32x4d 和 ResNet50，其他一致，训练和评估正常。

**Comment by ChrisMengxl** [comment]
是我的问题，  漏掉 use_multilabel: True。现可正常运行。
