### ISSUE TITLE
MobileNetV1_retrieval 训练报错

### ISSUE THREAD

**Issue by lazyn1997** [PaddlePaddle/PaddleClas#1732]
使用MobileNetV1_retrieval.yaml进行图像识别训练时，按照官方配置进行训练，只修改了class_num，训练集路径等参数，会报如下的错误
![QQ截图20220306193316](https://user-images.githubusercontent.com/34644177/156921482-b6bd8769-7265-4174-86b4-d6f9463b67c1.jpg)

将配置文件进行如下修改可解决报错
![image](https://user-images.githubusercontent.com/34644177/156921521-6ae20b48-6d2f-4f4b-91a0-2a7921180f4a.png)
qin
请验证一下是否为bug，还有BackboneStopLayer设置为name: flatten_0和name: "flatten"有什么区别吗，我看release/2.2中设置为name: flatten_0，release/2.3中设置为name: "flatten"。
同样的还有ResNet50_ReID.yaml配置文件中的差异，release/2.2设置为name: "adaptive_avg_pool2d_0"，release/2.3设置为name: "avg_pool"，这两个有什么区别？

**Comment by lazyn1997** [comment]
使用name: "avg_pool"会报下面的错误

`Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "E:\Documents\postgraduate\PaddleClas\ppcls\engine\engine.py", line 265, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "E:\Documents\postgraduate\PaddleClas\ppcls\engine\train\train.py", line 49, in train_epoch
    out = forward(engine, batch)
  File "E:\Documents\postgraduate\PaddleClas\ppcls\engine\train\train.py", line 79, in forward
    return engine.model(batch[0], batch[1])
  File "D:\miniconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Documents\postgraduate\PaddleClas\ppcls\arch\__init__.py", line 77, in forward
    x = self.neck(x)
  File "D:\miniconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "E:\Documents\postgraduate\PaddleClas\ppcls\arch\gears\vehicle_neck.py", line 50, in forward
    x = self.conv(x)
  File "D:\miniconda3\envs\paddle_env\lib\site-packages\paddle\fluid\dygraph\layers.py", line 914, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "D:\miniconda3\envs\paddle_env\lib\site-packages\paddle\nn\layer\conv.py", line 677, in forward
    use_cudnn=self._use_cudnn)
  File "D:\miniconda3\envs\paddle_env\lib\site-packages\paddle\nn\functional\conv.py", line 123, in _conv_nd
    pre_bias = getattr(_C_ops, op_type)(x, weight, *attrs)
ValueError: (InvalidArgument) The input of Op(Conv) should be a 4-D or 5-D Tensor. But received: input's dimension is 2, input's shape is [64, 1000].
  [Hint: Expected in_dims.size() == 4 || in_dims.size() == 5 == true, but received in_dims.size() == 4 || in_dims.size() == 5:0 != true:1.] (at ..\paddle/fluid/operators/conv_op.cc:74)
  [operator < conv2d > error]`

**Comment by Intsigstephon** [comment]
注意：这儿的name不是随便设置的，而是依据原来的网络结构以及需要修改的网络结构来确定的；详情可以参考Theseylayer的说明文档： https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/advanced_tutorials/theseus_layer.md

**Comment by weisy11** [comment]
release/2.3更新了接口的参数解析方式，使用更加直接，具体可以参考文档。
https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/advanced_tutorials/theseus_layer.md

**Comment by lazyn1997** [comment]
更新到release/2.3分支后问题已解决，感谢回复
