### ISSUE TITLE
关于PaddleClas打包成Mac软件后异常有人遇到吗

### ISSUE THREAD

**Issue by linkangren** [PaddlePaddle/PaddleClas#1735]
1.
PaddleClas2.3
paddlepaddle2.2.2 cpu版、

 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统MacOS
  b. Python版本号，如Python3.7

在本地运行测试代码都正常，打包后出现的异常信息如下：
2022-03-07 18:43:59 INFO: Loading faiss with AVX2 support.
2022-03-07 18:43:59 INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2022-03-07 18:43:59 INFO: Loading faiss.
2022-03-07 18:44:00 INFO: Successfully loaded faiss.
Traceback (most recent call last):
  File "paddle/fluid/ir.py", line 23, in <module>
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "paddle/fluid/proto/pass_desc_pb2.py", line 16, in <module>
ModuleNotFoundError: No module named 'framework_pb2'

During handling of the above exception, another exception occurred:

**Comment by Intsigstephon** [comment]
您这边所谓的打包是指？ 是想把paddleclas打包成一个python下运行的whl包，然后做分发吗

**Comment by lilith-zy** [comment]
您好，我是百度飞桨PaddleClas的产品经理，想跟您了解一下您这边具体是什么场景需要打包软件, 如果方便的话可以添加一下微信不？ 我的微信号是 lilith_yy
