### ISSUE TITLE
PaddleClas2.3 损失函数脚本配置报错，度量学习。亟待回复。谢谢。

### ISSUE THREAD

**Issue by ChrisMengxl** [PaddlePaddle/PaddleClas#1812]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/**2.3**和**PaddlePaddle 2.2.2**
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如**Linux**/Windows/MacOS
  b. Python版本号，如Python3.6/**7**/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
参考 [PaddleClas 代码解析-2.3 损失函数](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/advanced_tutorials/code_overview.md)

`Loss:
  Train:
    - CELoss:
        weight: 1.0
    - TripletLossV2:
        weight: 1.0
        margin: 0.5
`

但是报错：
```
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "/home/aistudio/PaddleClas/ppcls/engine/engine.py", line 265, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/home/aistudio/PaddleClas/ppcls/engine/train/train.py", line 51, in train_epoch
    loss_dict = engine.train_loss_func(out, batch[1])
  File "/home/aistudio/PaddleClas/ppcls/loss/__init__.py", line 46, in __call__
    loss = loss_func(input, batch)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 917, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 907, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/PaddleClas/ppcls/loss/triplet.py", line 27, in forward
    inputs = input["features"]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 598, in __getitem__
    return self._getitem_index_not_tensor(item)
ValueError: (InvalidArgument) Currently, Tensor.__indices__() only allows indexing by Integers, Slices, Ellipsis, None, tuples of these types and list of Bool and Integers, but received str in 1th slice item (at /paddle/paddle/fluid/pybind/imperative.cc:645)
```

**Comment by weisy11** [comment]
你好，请问你具体修改了什么代码呢？或者是运行了哪个脚本出现这个报错呢

**Comment by ChrisMengxl** [comment]
> 你好，请问你具体修改了什么代码呢？或者是运行了哪个脚本出现这个报错呢

就是普通的ResNet50.yaml 修改 Loss: Train: - CELoss: weight: 1.0 - TripletLossV2: weight: 1.0 margin: 0.5，其他没变

**Comment by ChrisMengxl** [comment]
> 你好，请问你具体修改了什么代码呢？或者是运行了哪个脚本出现这个报错呢

或者 可以将我在AI Studio的工程发你。
