### ISSUE TITLE
[k200麒麟]'paddle.fluid.core_noavx.AnalysisConfig' object has no attribute 'set_mkldnn_cache_capacity

### ISSUE THREAD

**Issue by 1chang37** [PaddlePaddle/PaddleClas#1839]
[root@eaistation90 PaddleClas]# python3 deploy/python/predict_cls.py  -c deploy/configs/inference_cls.yaml
  
XPURT /usr/local/lib64/python3.7/site-packages/paddle/fluid/../libs/libxpurt.so loaded
2022-04-14 16:29:58 INFO:
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

2022-04-14 16:29:58 INFO: Global :
2022-04-14 16:29:58 INFO:     batch_size : 1
2022-04-14 16:29:58 INFO:     cpu_num_threads : 10
2022-04-14 16:29:58 INFO:     enable_benchmark : True
2022-04-14 16:29:58 INFO:     enable_mkldnn : True
2022-04-14 16:29:58 INFO:     enable_profile : False
2022-04-14 16:29:58 INFO:     gpu_mem : 8000
2022-04-14 16:29:58 INFO:     infer_imgs : ./images/
2022-04-14 16:29:58 INFO:     inference_model_dir : ./models/class_ResNet50_vd_ImageNet_infer

2022-04-14 16:29:58 INFO: Global :
2022-04-14 16:29:58 INFO:     batch_size : 1
2022-04-14 16:29:58 INFO:     cpu_num_threads : 10
2022-04-14 16:29:58 INFO:     enable_benchmark : True
2022-04-14 16:29:58 INFO:     enable_mkldnn : True
2022-04-14 16:29:58 INFO:     enable_profile : False
2022-04-14 16:29:58 INFO:     gpu_mem : 8000
2022-04-14 16:29:58 INFO:     infer_imgs : ./images/
2022-04-14 16:29:58 INFO:     inference_model_dir : ./models/class_ResNet50_vd_ImageNet_infer
2022-04-14 16:29:58 INFO:     ir_optim : True
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

2022-04-14 16:29:58 INFO: Global :
2022-04-14 16:29:58 INFO:     batch_size : 1
2022-04-14 16:29:58 INFO:     cpu_num_threads : 10
2022-04-14 16:29:58 INFO:     enable_benchmark : True
2022-04-14 16:29:58 INFO:     enable_mkldnn : True
2022-04-14 16:29:58 INFO:     enable_profile : False
2022-04-14 16:29:58 INFO:     gpu_mem : 8000
2022-04-14 16:29:58 INFO:     infer_imgs : ./images/
2022-04-14 16:29:58 INFO:     inference_model_dir : ./models/class_ResNet50_vd_ImageNet_infer
2022-04-14 16:29:58 INFO:     ir_optim : True
2022-04-14 16:29:58 INFO:     use_fp16 : False
2022-04-14 16:29:58 INFO:     use_gpu : False
2022-04-14 16:29:58 INFO:     use_tensorrt : False
2022-04-14 16:29:58 INFO: PostProcess :
2022-04-14 16:29:58 INFO:     SavePreLabel :
2022-04-14 16:29:58 INFO:         save_dir : ./pre_label/
2022-04-14 16:29:58 INFO:     Topk :
2022-04-14 16:29:58 INFO:         class_id_map_file : ./ppcls/utils/imagenet1k_label_list.txt
2022-04-14 16:29:58 INFO:         topk : 5
2022-04-14 16:29:58 INFO:     main_indicator : Topk
2022-04-14 16:29:58 INFO: PreProcess :
2022-04-14 16:29:58 INFO:     transform_ops :
2022-04-14 16:29:58 INFO:         ResizeImage :
2022-04-14 16:29:58 INFO:             resize_short : 256
2022-04-14 16:29:58 INFO:         CropImage :
2022-04-14 16:29:58 INFO:             size : 224
2022-04-14 16:29:58 INFO:         NormalizeImage :
2022-04-14 16:29:58 INFO:             channel_num : 3
2022-04-14 16:29:58 INFO:             mean : [0.485, 0.456, 0.406]
2022-04-14 16:29:58 INFO:             order :
2022-04-14 16:29:58 INFO:             scale : 0.00392157
2022-04-14 16:29:58 INFO:             std : [0.229, 0.224, 0.225]
2022-04-14 16:29:58 INFO:         ToCHWImage : None
Traceback (most recent call last):
  File "deploy/python/predict_cls.py", line 153, in <module>
    main(config)
  File "deploy/python/predict_cls.py", line 111, in main
    cls_predictor = ClsPredictor(config)
  File "deploy/python/predict_cls.py", line 33, in __init__
    super().__init__(config["Global"])
  File "/home/kunlun/tuili/xiazai/PaddleClas/deploy/utils/predictor.py", line 36, in __init__
    args, inference_model_dir)
  File "/home/kunlun/tuili/xiazai/PaddleClas/deploy/utils/predictor.py", line 54, in create_paddle_predictor
    config.set_mkldnn_cache_capacity(10)
AttributeError: 'paddle.fluid.core_noavx.AnalysisConfig' object has no attribute 'set_mkldnn_cache_capacity'
[root@eaistation90 PaddleClas]#

**Comment by fukai7722** [comment]
m1也有这个问题，不支持arm吗

**Comment by aaas19920513** [comment]
Intel 的mac 也遇到了

**Comment by weisy11** [comment]
你好，如果设备不支持mkldnn，请把配置里的enable_mkldnn设置成False
https://github.com/PaddlePaddle/PaddleClas/blob/d2bfa3a3ce7c6939444752bfcdde24069b6c8c9d/deploy/configs/inference_cls.yaml#L6

**Comment by fukai7722** [comment]
换下面那条命令是可以的。

tuihou ***@***.***> 于2022年4月24日周日 20:32写道：
