### ISSUE TITLE
[HOW TO]请问如何使用自带的ppam工具包实现推理可视化？

### ISSUE THREAD

**Issue by pynsigrid** [PaddlePaddle/PaddleClas#1850]
###  使用PPLCNet做图像检索，希望使用ppam自带的工具包cam实现推理可视化
参考的使用方法如[该链接](https://aistudio.baidu.com/paddle/forum/topic/show/990753)。

### 问题描述
改写推理脚本，使用自己数据集下训练好的模型，如（PPLCNet、ResNet50），对推理过程的Grad CAM可视化。在提取`target_layer`时出现如下错误：
```
Traceback (most recent call last):
  File "tools/gradcam.py", line 53, in <module>
    activation_map = cam_extractor(img_path, label=None)
  File "/home/pai/envs/paddle/lib/python3.8/site-packages/ppma/cam/grad_cam.py", line 70, in __call__
    return self.forward(input_tensor, label)
  File "/home/pai/envs/paddle/lib/python3.8/site-packages/ppma/cam/grad_cam.py", line 40, in forward
    out = paddle.nn.functional.softmax(out, axis=1)
  File "/home/pai/envs/paddle/lib/python3.8/site-packages/paddle/nn/functional/activation.py", line 913, in softmax
    return _C_ops.softmax(outs_cast, 'axis', axis, 'use_cudnn', use_cudnn)
ValueError: (InvalidArgument) softmax(): argument 'X' (position 0) must be Tensor, but got dict (at /paddle/paddle/fluid/pybind/op_function.h:816)
```
可视化的核心代码如下：
```
model = build_model(config)
# apply_to_static(config, model)

target_layer = model.backbone.last_conv                          
cam_extractor = cam.GradCAMPlusPlus(model, target_layer)   # 支持 GradCAM、XGradCAM、GradCAM++

activation_map = cam_extractor(img_path, label=None)   
plt.imsave(os.path.join(save_path+'cam_demo1.jpg'), activation_map)
```

想请教一下正确的制定模型网络层和实现CAM可视化的方法～最好可以是以PPLCNet为例，（不是paddle.vision.models模型库里面自带模型）

**Comment by pynsigrid** [comment]
应该解决了：`oftmax(): argument 'X' (position 0) must be Tensor, but got dict`是因为retrieval的输出包括三个部分：backbone、features和logits。在ppma源码处指定softmax的输出取哪一部分就行。
