### ISSUE TITLE
aistudio上跑paddleclas的官方示例

### ISSUE THREAD

**Issue by Sunyingbin** [PaddlePaddle/PaddleClas#204]
请问有没有一个能跑通的，给我个链接

**Comment by littletomatodonkey** [comment]
你好，可以参考这里：https://aistudio.baidu.com/aistudio/projectdetail/428501

**Comment by Sunyingbin** [comment]
这个我看了，我想具体一点，比如我如何在aistudio上跑SSLD模型微调-基于ResNet50_vd_ssld预训练模型，这样。我用给的例子跑是报错的在notebook上。
下面是我写的例子：
!export PYTHONPATH=$PWD:$PYTHONPATH &&  export CUDA_VISIBLE_DEVICES=0 && python -m paddle.distributed.launch --selected_gpus="0" tools/train.py -c ./configs/quick_start/ResNet50_vd_ssld_finetune.yaml

请问这个应该怎么改能在aistudio上跑通。

**Comment by littletomatodonkey** [comment]
您根据文档的说明在终端里跑有问题吗？或者贴一下报错信息？

**Comment by Sunyingbin** [comment]
API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler

        
W0707 11:07:43.719249  1261 device_context.cc:252] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 9.2, Runtime API Version: 9.0
W0707 11:07:43.723579  1261 device_context.cc:260] device: 0, cuDNN Version: 7.3.
Process Process-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 549, in _read_into_queue
    for sample in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 196, in reader
    with open(img_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/flowers102/jpg/image_05839.jpg'
Process Process-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 549, in _read_into_queue
    for sample in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 196, in reader
    with open(img_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/flowers102/jpg/image_07153.jpg'
Process Process-3:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 549, in _read_into_queue
    for sample in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 196, in reader
    with open(img_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/flowers102/jpg/image_06404.jpg'
2020-07-07 19:07:47 WARNING: Your reader has raised an exception!
Process Process-4:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1156, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1136, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1206, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 505, in __reader_creator__
    for item in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 281, in wrapper
    for idx, sample in enumerate(reader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 572, in queue_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 556, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 549, in _read_into_queue
    for sample in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 196, in reader
    with open(img_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: './dataset/flowers102/jpg/image_03181.jpg'
Traceback (most recent call last):
  File "tools/train.py", line 148, in <module>
    main(args)
  File "tools/train.py", line 113, in main
    epoch_id, 'train', config, vdl_writer)
  File "/home/aistudio/PaddleClas/tools/program.py", line 434, in run
    for idx, batch in enumerate(dataloader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1102, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)

INFO 2020-07-07 11:07:50,216 utils.py:272] terminate all the procs
ERROR 2020-07-07 11:07:50,216 utils.py:416] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2020-07-07 11:07:50,216 utils.py:272] terminate all the procs

**Comment by Sunyingbin** [comment]
终端也尝试跑了一下，也是同样报错

**Comment by littletomatodonkey** [comment]
您的数据是不是没有解压？
![image](https://user-images.githubusercontent.com/14270174/86722832-e1bb6b00-c059-11ea-82ff-b7214db13b5d.png)
