### ISSUE TITLE
ImportError: DLL load failed while importing core_avx: 找不到指定的模块。

### ISSUE THREAD

**Issue by asjh123** [PaddlePaddle/PaddleClas#2155]
(paddle) D:\a\PaddleClas\deploy>python\predict_system.py -c configs\inference_product.yaml
Error: Can not import avx core while this file exists: C:\ProgramData\Anaconda3\Lib\site-packages\paddle\fluid\core_avx.pyd
Traceback (most recent call last):
  File "D:\a\PaddleClas\deploy\python\predict_system.py", line 26, in <module>
    from python.predict_rec import RecPredictor
  File "D:\a\PaddleClas\deploy\python\predict_rec.py", line 23, in <module>
    from utils import logger
  File "D:\a\PaddleClas\deploy\utils\__init__.py", line 4, in <module>
    from . import predictor
  File "D:\a\PaddleClas\deploy\utils\predictor.py", line 22, in <module>
    from paddle.inference import Config
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\__init__.py", line 25, in <module>
    from .framework import monkey_patch_variable
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\framework\__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\framework\random.py", line 16, in <module>
    import paddle.fluid as fluid
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\fluid\__init__.py", line 36, in <module>
    from . import framework
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\fluid\framework.py", line 37, in <module>
    from . import core
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\fluid\core.py", line 298, in <module>
    raise e
  File "C:\ProgramData\Anaconda3\Lib\site-packages\paddle\fluid\core.py", line 256, in <module>
    from . import core_avx
ImportError: DLL load failed while importing core_avx: 找不到指定的模块。
用了很多办法都不行，重装paddle也不行。

**Comment by asjh123** [comment]
调用 import paddle.fluid 没有问题，但是执行 python\predict_system.py -c configs\inference_product.yaml 这条语句就会出现上面的错误。

**Comment by asjh123** [comment]
调用 import paddle.fluid 没有问题，但是执行 python\predict_system.py -c configs\inference_product.yaml 这条语句就会出现上面的错误。

**Comment by TingquanGao** [comment]
想问一下，目前问题解决了吗？paddlepaddle的whl包是从那里下载安装的呢？
