### ISSUE TITLE
我修改了模型之后为什么用paddle.summary显示正常，而在训练时却出错了。

### ISSUE THREAD

**Issue by qqwantu** [PaddlePaddle/PaddleClas#2299]
[2022/09/14 22:23:19] root INFO: 
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

[2022/09/14 22:23:19] root INFO: Arch : 
[2022/09/14 22:23:19] root INFO:     class_num : 7
[2022/09/14 22:23:19] root INFO:     name : DBSTDCNet1
[2022/09/14 22:23:19] root INFO: DataLoader : 
[2022/09/14 22:23:19] root INFO:     Eval : 
[2022/09/14 22:23:19] root INFO:         dataset : 
[2022/09/14 22:23:19] root INFO:             cls_label_path : ./dataset/yan/val.txt
[2022/09/14 22:23:19] root INFO:             image_root : ./dataset/yan/
[2022/09/14 22:23:19] root INFO:             name : ImageNetDataset
[2022/09/14 22:23:19] root INFO:             transform_ops : 
[2022/09/14 22:23:19] root INFO:                 DecodeImage : 
[2022/09/14 22:23:19] root INFO:                     channel_first : False
[2022/09/14 22:23:19] root INFO:                     to_rgb : True
[2022/09/14 22:23:19] root INFO:                 ResizeImage : 
[2022/09/14 22:23:19] root INFO:                     resize_short : 256
[2022/09/14 22:23:19] root INFO:                 CropImage : 
[2022/09/14 22:23:19] root INFO:                     size : 224
[2022/09/14 22:23:19] root INFO:                 NormalizeImage : 
[2022/09/14 22:23:19] root INFO:                     mean : [0.485, 0.456, 0.406]
[2022/09/14 22:23:19] root INFO:                     order : 
[2022/09/14 22:23:19] root INFO:                     scale : 1.0/255.0
[2022/09/14 22:23:19] root INFO:                     std : [0.229, 0.224, 0.225]
[2022/09/14 22:23:19] root INFO:         loader : 
[2022/09/14 22:23:19] root INFO:             num_workers : 1
[2022/09/14 22:23:19] root INFO:             use_shared_memory : True
[2022/09/14 22:23:19] root INFO:         sampler : 
[2022/09/14 22:23:19] root INFO:             batch_size : 8
[2022/09/14 22:23:19] root INFO:             drop_last : False
[2022/09/14 22:23:19] root INFO:             name : DistributedBatchSampler
[2022/09/14 22:23:19] root INFO:             shuffle : False
[2022/09/14 22:23:19] root INFO:     Train : 
[2022/09/14 22:23:19] root INFO:         dataset : 
[2022/09/14 22:23:19] root INFO:             batch_transform_ops : 
[2022/09/14 22:23:19] root INFO:                 MixupOperator : 
[2022/09/14 22:23:19] root INFO:                     alpha : 0.2
[2022/09/14 22:23:19] root INFO:             cls_label_path : ./dataset/yan/train.txt
[2022/09/14 22:23:19] root INFO:             image_root : ./dataset/yan/
[2022/09/14 22:23:19] root INFO:             name : ImageNetDataset
[2022/09/14 22:23:19] root INFO:             transform_ops : 
[2022/09/14 22:23:19] root INFO:                 DecodeImage : 
[2022/09/14 22:23:19] root INFO:                     channel_first : False
[2022/09/14 22:23:19] root INFO:                     to_rgb : True
[2022/09/14 22:23:19] root INFO:                 ResizeImage : 
[2022/09/14 22:23:19] root INFO:                     resize_short : 256
[2022/09/14 22:23:19] root INFO:                 RandCropImage : 
[2022/09/14 22:23:19] root INFO:                     size : 224
[2022/09/14 22:23:19] root INFO:                 RandFlipImage : 
[2022/09/14 22:23:19] root INFO:                     flip_code : 1
[2022/09/14 22:23:19] root INFO:                 NormalizeImage : 
[2022/09/14 22:23:19] root INFO:                     mean : [0.485, 0.456, 0.406]
[2022/09/14 22:23:19] root INFO:                     order : 
[2022/09/14 22:23:19] root INFO:                     scale : 1.0/255.0
[2022/09/14 22:23:19] root INFO:                     std : [0.229, 0.224, 0.225]
[2022/09/14 22:23:19] root INFO:         loader : 
[2022/09/14 22:23:19] root INFO:             num_workers : 1
[2022/09/14 22:23:19] root INFO:             use_shared_memory : True
[2022/09/14 22:23:19] root INFO:         sampler : 
[2022/09/14 22:23:19] root INFO:             batch_size : 128
[2022/09/14 22:23:19] root INFO:             drop_last : False
[2022/09/14 22:23:19] root INFO:             name : DistributedBatchSampler
[2022/09/14 22:23:19] root INFO:             shuffle : True
[2022/09/14 22:23:19] root INFO: Global : 
[2022/09/14 22:23:19] root INFO:     checkpoints : None
[2022/09/14 22:23:19] root INFO:     device : gpu
[2022/09/14 22:23:19] root INFO:     epochs : 100
[2022/09/14 22:23:19] root INFO:     eval_during_train : True
[2022/09/14 22:23:19] root INFO:     eval_interval : 1
[2022/09/14 22:23:19] root INFO:     image_shape : [1, 3, 224, 224]
[2022/09/14 22:23:19] root INFO:     output_dir : ./output/
[2022/09/14 22:23:19] root INFO:     pretrained_model : None
[2022/09/14 22:23:19] root INFO:     print_batch_step : 30
[2022/09/14 22:23:19] root INFO:     save_inference_dir : ./inference
[2022/09/14 22:23:19] root INFO:     save_interval : 10
[2022/09/14 22:23:19] root INFO:     use_visualdl : True
[2022/09/14 22:23:19] root INFO: Infer : 
[2022/09/14 22:23:19] root INFO:     PostProcess : 
[2022/09/14 22:23:19] root INFO:         class_id_map_file : dataset/yan/label.txt
[2022/09/14 22:23:19] root INFO:         name : Topk
[2022/09/14 22:23:19] root INFO:         topk : 5
[2022/09/14 22:23:19] root INFO:     batch_size : 10
[2022/09/14 22:23:19] root INFO:     infer_imgs : docs/images/inference_deployment/whl_demo.jpg
[2022/09/14 22:23:19] root INFO:     transforms : 
[2022/09/14 22:23:19] root INFO:         DecodeImage : 
[2022/09/14 22:23:19] root INFO:             channel_first : False
[2022/09/14 22:23:19] root INFO:             to_rgb : True
[2022/09/14 22:23:19] root INFO:         ResizeImage : 
[2022/09/14 22:23:19] root INFO:             resize_short : 256
[2022/09/14 22:23:19] root INFO:         CropImage : 
[2022/09/14 22:23:19] root INFO:             size : 224
[2022/09/14 22:23:19] root INFO:         NormalizeImage : 
[2022/09/14 22:23:19] root INFO:             mean : [0.485, 0.456, 0.406]
[2022/09/14 22:23:19] root INFO:             order : 
[2022/09/14 22:23:19] root INFO:             scale : 1.0/255.0
[2022/09/14 22:23:19] root INFO:             std : [0.229, 0.224, 0.225]
[2022/09/14 22:23:19] root INFO:         ToCHWImage : None
[2022/09/14 22:23:19] root INFO: Loss : 
[2022/09/14 22:23:19] root INFO:     Eval : 
[2022/09/14 22:23:19] root INFO:         CELoss : 
[2022/09/14 22:23:19] root INFO:             weight : 1.0
[2022/09/14 22:23:19] root INFO:     Train : 
[2022/09/14 22:23:19] root INFO:         CELoss : 
[2022/09/14 22:23:19] root INFO:             epsilon : 0.1
[2022/09/14 22:23:19] root INFO:             weight : 1.0
[2022/09/14 22:23:19] root INFO: Metric : 
[2022/09/14 22:23:19] root INFO:     Eval : 
[2022/09/14 22:23:19] root INFO:         TopkAcc : 
[2022/09/14 22:23:19] root INFO:             topk : [1, 5]
[2022/09/14 22:23:19] root INFO:     Train : None
[2022/09/14 22:23:19] root INFO: Optimizer : 
[2022/09/14 22:23:19] root INFO:     lr : 
[2022/09/14 22:23:19] root INFO:         learning_rate : 0.001
[2022/09/14 22:23:19] root INFO:         name : Cosine
[2022/09/14 22:23:19] root INFO:     momentum : 0.9
[2022/09/14 22:23:19] root INFO:     name : Momentum
[2022/09/14 22:23:19] root INFO:     regularizer : 
[2022/09/14 22:23:19] root INFO:         coeff : 1e-05
[2022/09/14 22:23:19] root INFO:         name : L2
[2022/09/14 22:23:19] root INFO: profiler_options : None
[2022/09/14 22:23:19] root INFO: train with paddle 2.2.2 and device CUDAPlace(0)
/home/aistudio/work/PaddleClas/ppcls/data/preprocess/ops/operators.py:44: DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead.
  'nearest': Image.NEAREST,
/home/aistudio/work/PaddleClas/ppcls/data/preprocess/ops/operators.py:45: DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
  'bilinear': Image.BILINEAR,
/home/aistudio/work/PaddleClas/ppcls/data/preprocess/ops/operators.py:46: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  'bicubic': Image.BICUBIC,
/home/aistudio/work/PaddleClas/ppcls/data/preprocess/ops/operators.py:47: DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead.
  'box': Image.BOX,
/home/aistudio/work/PaddleClas/ppcls/data/preprocess/ops/operators.py:48: DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead.
  'lanczos': Image.LANCZOS,
/home/aistudio/work/PaddleClas/ppcls/data/preprocess/ops/operators.py:49: DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead.
  'hamming': Image.HAMMING
W0914 22:23:20.629117   613 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.1
W0914 22:23:20.634636   613 device_context.cc:465] device: 0, cuDNN Version: 7.6.
### **summary的shape 是正常的 到训练阶段就不对了。**
[8, 32, 112, 112]
[8, 64, 112, 112]
out_eca [8, 128, 56, 56]
[8, 128, 56, 56]
out_eca [8, 256, 28, 28]
[8, 128, 28, 28]
out_eca [8, 256, 14, 14]
[8, 256, 14, 14]
out_eca [8, 512, 7, 7]
-------------------------------------------------------------------------------

===============================================================================
Total params: 221,699
Trainable params: 210,243
Non-trainable params: 11,456
-------------------------------------------------------------------------------
Input size (MB): 4.59
Forward/backward pass size (MB): 1034.44
Params size (MB): 0.85
Estimated Total Size (MB): 1039.88
-------------------------------------------------------------------------------

[2022/09/14 22:23:24] root WARNING: The training strategy in config files provided by PaddleClas is based on 4 gpus. But the number of gpus is 1 in current training. Please modify the stategy (learning rate, batch size and so on) if use config files in PaddleClas to train.
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py:653: UserWarning: When training, we now always track global mean and variance.
  "When training, we now always track global mean and variance.")
### [128, 32, 112, 112]
[128, 64, 112, 112]
out_eca [128, 128, 56, 56]
[128, 128, 56, 56]
out_eca [128, 256, 28, 28]
[128, 128, 28, 28]
out_eca [128, 256, 14, 14]
[128, 256, 14, 14]
out_eca [128, 512, 7, 7]
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "/home/aistudio/work/PaddleClas/ppcls/engine/engine.py", line 290, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/home/aistudio/work/PaddleClas/ppcls/engine/train/train.py", line 63, in train_epoch
    loss_dict["loss"].backward()
  File "<decorator-gen-128>", line 2, in backward
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 249, in backward
    framework._dygraph_tracer())
ValueError: (InvalidArgument)  shape should have the save dim with perm, but received shape size is:4, perm size is:3.
  [Hint: Expected shape.size() == perm.size(), but received shape.size():4 != perm.size():3.] (at /paddle/paddle/fluid/operators/transpose_op.cu.h:562)

**Comment by cuicheng01** [comment]
您好，问下问题解决了吗？
