### ISSUE TITLE
PaddleClas运行特征提取示例报错。

### ISSUE THREAD

**Issue by SunLoveSheep** [PaddlePaddle/PaddleClas#2333]
环境：
PaddlePaddle docker：2.3.2-gpu-cuda11.2-cudnn8
PaddleClas branch: release/2.5, installed from repo by `python setup.py install`

问题描述：
运行特征提取示例报错。
运行命令：
```bash
cd deploy  # Under /pth/to/PaddleClas/deploy/
python python/predict_rec.py -c configs/inference_rec.yaml -o Global.rec_inference_model_dir="../../deploy_cus/models/PPLCNetV2_base_ssld_infer
```
模型文件确认无误。
补充说明：似乎和系统环境有关系：
- 我在一台Ubuntu20.04的电脑上手动安装PaddlePaddle 2.3.2 + Python 3.7 + CUDA11.2 & cudnn8，用同样的PaddleClas分支，是可以正常运行上述命令的；
- 但是在一台基于CentOS7定制的Linux的服务器（公司内部系统，CUDA配置相同）上重复上述过程就会报下面的错误；
- 在同样的服务器上用上述PaddlePaddle docker，重复上述过程，依然会报下面的错误。

报错信息：
```bash
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
2022-09-21 15:14:15 INFO: Loading faiss with AVX2 support.
2022-09-21 15:14:15 INFO: Could not load library with AVX2 support due to:
ModuleNotFoundError("No module named 'faiss.swigfaiss_avx2'")
2022-09-21 15:14:15 INFO: Loading faiss.
2022-09-21 15:14:15 INFO: Successfully loaded faiss.
2022-09-21 15:14:15 INFO:
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

2022-09-21 15:14:15 INFO: Global :
2022-09-21 15:14:15 INFO:     batch_size : 1
2022-09-21 15:14:15 INFO:     cpu_num_threads : 10
2022-09-21 15:14:15 INFO:     enable_benchmark : True
2022-09-21 15:14:15 INFO:     enable_mkldnn : True
2022-09-21 15:14:15 INFO:     enable_profile : False
2022-09-21 15:14:15 INFO:     gpu_mem : 8000
2022-09-21 15:14:15 INFO:     infer_imgs : ./images/wangzai.jpg
2022-09-21 15:14:15 INFO:     ir_optim : True
2022-09-21 15:14:15 INFO:     rec_inference_model_dir : ../../deploy_cus/models/PPLCNetV2_base_ssld_infer
2022-09-21 15:14:15 INFO:     use_fp16 : False
2022-09-21 15:14:15 INFO:     use_gpu : False
2022-09-21 15:14:15 INFO:     use_tensorrt : False
2022-09-21 15:14:15 INFO: RecPostProcess : None
2022-09-21 15:14:15 INFO: RecPreProcess :
2022-09-21 15:14:15 INFO:     transform_ops :
2022-09-21 15:14:15 INFO:         ResizeImage :
2022-09-21 15:14:15 INFO:             backend : cv2
2022-09-21 15:14:15 INFO:             interpolation : bilinear
2022-09-21 15:14:15 INFO:             return_numpy : False
2022-09-21 15:14:15 INFO:             size : [224, 224]
2022-09-21 15:14:15 INFO:         NormalizeImage :
2022-09-21 15:14:15 INFO:             mean : [0.485, 0.456, 0.406]
2022-09-21 15:14:15 INFO:             order : hwc
2022-09-21 15:14:15 INFO:             scale : 1.0/255.0
2022-09-21 15:14:15 INFO:             std : [0.229, 0.224, 0.225]
2022-09-21 15:14:15 INFO:         ToCHWImage : None
Traceback (most recent call last):
  File "python/predict_rec.py", line 143, in <module>
    main(config)
  File "python/predict_rec.py", line 104, in main
    rec_predictor = RecPredictor(config)
  File "python/predict_rec.py", line 29, in __init__
    config["Global"]["rec_inference_model_dir"])
  File "/usr/local/lib/python3.7/dist-packages/paddleclas-0.0.0-py3.7.egg/paddleclas/deploy/utils/predictor.py", line 37, in __init__
    args, inference_model_dir)
  File "/usr/local/lib/python3.7/dist-packages/paddleclas-0.0.0-py3.7.egg/paddleclas/deploy/utils/predictor.py", line 100, in create_paddle_predictor
    predictor = create_predictor(config)
IndexError: basic_string::at: __n (which is 0) >= this->size() (which is 0)
```

**Comment by RainFrost1** [comment]
这个请使用PP-ShiTu的识别模型，[链接](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/quick_start/quick_start_recognition.md#22-%E5%9B%BE%E5%83%8F%E8%AF%86%E5%88%AB%E4%BD%93%E9%AA%8C)

**Comment by SunLoveSheep** [comment]
> 这个请使用PP-ShiTu的识别模型，[链接](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/quick_start/quick_start_recognition.md#22-%E5%9B%BE%E5%83%8F%E8%AF%86%E5%88%AB%E4%BD%93%E9%AA%8C)

这属于是答非所问了。。。 问题不在于用的什么模型，问题在于一模一样的代码和模型，Ubuntu20.04能跑，CentOS7上用了PaddlePaddle的docker都跑不了啊 = =

**Comment by sxk000** [comment]
> > 这个请使用PP-ShiTu的识别模型，[链接](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/quick_start/quick_start_recognition.md#22-%E5%9B%BE%E5%83%8F%E8%AF%86%E5%88%AB%E4%BD%93%E9%AA%8C)
> 
> 这属于是答非所问了。。。 问题不在于用的什么模型，问题在于一模一样的代码和模型，Ubuntu20.04能跑，CentOS7上用了PaddlePaddle的docker都跑不了啊 = =

你好，这个问题解决了吗？我也遇到同样的问题了，应该怎么解决呢？谢谢！
