### ISSUE TITLE
deploy 程序应在正确的位置 import 套件

### ISSUE THREAD

**Issue by hirortw101** [PaddlePaddle/PaddleClas#2364]
以 ONNX runtime deploy PULC 语种分类模型時

發現 python deploy 程序沒有在正确的位置 import 套件

## 实作流程

2022/10/07

使用 docker image `python:3.7`

使用最新 Release tag `v2.4.0`

```shell
git clone https://github.com/PaddlePaddle/PaddleClas.git
cd PaddleClas
git reset --hard v2.4.0
```

以 ONNX deploy
要避免安装 paddleclas 和他的一大包 requirements 

```shell
pip install opencv-contrib-python-headless
pip install requests tqdm prettytable pillow six PyYAML
pip install onnxruntime==1.12.1 paddle2onnx==1.0.1
```

### language_classification_infer 模型下载

```shell
cd deploy
mkdir models && cd models
wget -nc https://paddleclas.bj.bcebos.com/models/PULC/language_classification_infer.tar && tar xf language_classification_infer.tar
cd ..
```

### 转换 ONNX

```shell
paddle2onnx \
--model_dir=models/language_classification_infer/ \
--model_filename=inference.pdmodel \
--params_filename=inference.pdiparams \
--save_file=models/language_classification_infer/inference.onnx \
--opset_version=11 \
--enable_onnx_checker=True
```

### 预测

```shell
python python/predict_cls.py \
-c configs/PULC/language_classification/inference_language_classification.yaml \
-o Global.use_gpu=False \
-o Global.use_onnx=True
```

出错

```shell
Traceback (most recent call last):
  File "python/predict_cls.py", line 23, in <module>
    from utils import logger
  File "/root/PaddleClas/deploy/utils/__init__.py", line 4, in <module>
    from . import predictor
  File "/root/PaddleClas/deploy/utils/predictor.py", line 22, in <module>
    from paddle.inference import Config
ModuleNotFoundError: No module named 'paddle'
```

用 onnxruntime 时不需要 paddle

所以 import paddle 应该放在 `def create_paddle_predictor` 内

utils/predictor.py  # 22

https://github.com/PaddlePaddle/PaddleClas/blob/3a28ee29003621ecdb9fd4bb8633a681fb1f8ddf/deploy/utils/predictor.py#L22-L23

```python=22
# - from paddle.inference import Config
# - from paddle.inference import create_predictor
```

utils/predictor.py  # 42

https://github.com/PaddlePaddle/PaddleClas/blob/3a28ee29003621ecdb9fd4bb8633a681fb1f8ddf/deploy/utils/predictor.py#L42-L43

```python=42
    def create_paddle_predictor(self, args, inference_model_dir=None):
        from paddle.inference import Config
        from paddle.inference import create_predictor
        if inference_model_dir is None:
            inference_model_dir = args.inference_model_dir
```

多余的 import paddle

python/postprocess.py  # 21

https://github.com/PaddlePaddle/PaddleClas/blob/3a28ee29003621ecdb9fd4bb8633a681fb1f8ddf/deploy/python/postprocess.py#L21-L22

```python=21
# - import paddle
# - import paddle.nn.functional as F
```

### 再预测

```shell
python python/predict_cls.py \
-c configs/PULC/language_classification/inference_language_classification.yaml \
-o Global.use_gpu=False \
-o Global.use_onnx=True
```

```shell
2022-10-07 06:34:40 WARNING: A new filed (use_onnx) detected!
2022-10-07 06:34:40 INFO: 
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

2022-10-07 06:34:40 INFO: Global : 
2022-10-07 06:34:40 INFO:     batch_size : 1
2022-10-07 06:34:40 INFO:     cpu_num_threads : 10
2022-10-07 06:34:40 INFO:     enable_benchmark : True
2022-10-07 06:34:40 INFO:     enable_mkldnn : False
2022-10-07 06:34:40 INFO:     enable_profile : False
2022-10-07 06:34:40 INFO:     gpu_mem : 8000
2022-10-07 06:34:40 INFO:     infer_imgs : ./images/PULC/language_classification/word_35404.png
2022-10-07 06:34:40 INFO:     inference_model_dir : ./models/language_classification_infer
2022-10-07 06:34:40 INFO:     ir_optim : True
2022-10-07 06:34:40 INFO:     use_fp16 : False
2022-10-07 06:34:40 INFO:     use_gpu : False
2022-10-07 06:34:40 INFO:     use_onnx : True
2022-10-07 06:34:40 INFO:     use_tensorrt : False
2022-10-07 06:34:40 INFO: PostProcess : 
2022-10-07 06:34:40 INFO:     SavePreLabel : 
2022-10-07 06:34:40 INFO:         save_dir : ./pre_label/
2022-10-07 06:34:40 INFO:     Topk : 
2022-10-07 06:34:40 INFO:         class_id_map_file : ../ppcls/utils/PULC_label_list/language_classification_label_list.txt
2022-10-07 06:34:40 INFO:         topk : 2
2022-10-07 06:34:40 INFO:     main_indicator : Topk
2022-10-07 06:34:40 INFO: PreProcess : 
2022-10-07 06:34:40 INFO:     transform_ops : 
2022-10-07 06:34:40 INFO:         ResizeImage : 
2022-10-07 06:34:40 INFO:             size : [160, 80]
2022-10-07 06:34:40 INFO:         NormalizeImage : 
2022-10-07 06:34:40 INFO:             channel_num : 3
2022-10-07 06:34:40 INFO:             mean : [0.485, 0.456, 0.406]
2022-10-07 06:34:40 INFO:             order : 
2022-10-07 06:34:40 INFO:             scale : 0.00392157
2022-10-07 06:34:40 INFO:             std : [0.229, 0.224, 0.225]
2022-10-07 06:34:40 INFO:         ToCHWImage : None
Warning: If want to use your own label_dict, please input legal path!
Otherwise label_names will be empty!
Traceback (most recent call last):
  File "python/predict_cls.py", line 153, in <module>
    main(config)
  File "python/predict_cls.py", line 134, in main
    batch_results = cls_predictor.predict(batch_imgs)
  File "python/predict_cls.py", line 99, in predict
    input_feed={input_names: image})[0]
  File "/usr/local/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 200, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: x for the following indices
 index: 2 Got: 80 Expected: 160
 index: 3 Got: 160 Expected: 80
 Please fix either the inputs or the model.
```

修改後
不使用 paddle 顺利运行
到模型预测前
但是发现 onnx 的 input shape  有问题 #2365 

## 其他 

pillow 要求升级 API

deploy/python/preprocess.py  # 64

https://github.com/PaddlePaddle/PaddleClas/blob/3a28ee29003621ecdb9fd4bb8633a681fb1f8ddf/deploy/python/preprocess.py#L64-L71

```python=64
        _pil_interp_from_str = {
            'nearest': Image.Resampling.NEAREST,
            'bilinear': Image.Resampling.BILINEAR,
            'bicubic': Image.Resampling.BICUBIC,
            'box': Image.Resampling.BOX,
            'lanczos': Image.Resampling.LANCZOS,
            'hamming': Image.Resampling.HAMMING
        }
```

**Comment by TingquanGao** [comment]
谢谢反馈！我们会尽快解决该问题。
