### ISSUE TITLE
eval paddlepaddle，报错AssertionError: can't find PADDLE_TRAINER_ENDPOINTS

### ISSUE THREAD

**Issue by trollhe** [PaddlePaddle/PaddleClas#243]
报错背景:
在aistudio上，进行训练，完成后得到./output/ResNet50_vd/190/ppcls.*

在eval时报错:
eval命令:
!python tools/eval.py \
    -c ./configs/quick_start/ResNet50_vd_finetune_eval.yaml 
```
Traceback (most recent call last):
  File "tools/eval.py", line 82, in <module>
    main(args)
  File "tools/eval.py", line 55, in main
    fleet.init(role)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/incubate/fleet/base/fleet_base.py", line 198, in init
    self._role_maker.generate_role()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/incubate/fleet/base/role_maker.py", line 500, in generate_role
    assert self._worker_endpoints is not None, "can't find PADDLE_TRAINER_ENDPOINTS"
AssertionError: can't find PADDLE_TRAINER_ENDPOINTS
```

**Comment by littletomatodonkey** [comment]
你好，eval的话可以参考这个脚本

https://github.com/PaddlePaddle/PaddleClas/blob/master/tools/eval.sh

**Comment by trollhe** [comment]
非常感谢，已解决

eval命令如下(单gpu)
```
!export PYTHONPATH=$PWD:$PYTHONPATH

!python -m paddle.distributed.launch \
    --selected_gpus="0" \
    tools/eval.py \
        -c ./configs/quick_start/ResNet50_vd_finetune_eval.yaml 
```

**Comment by littletomatodonkey** [comment]
不客气～
