### ISSUE TITLE
UnboundLocalError: local variable 'fpr' referenced before assignment

### ISSUE THREAD

**Issue by dddrecall** [PaddlePaddle/PaddleClas#2432]
1. PaddleClas版本以及PaddlePaddle版本git 
   release/2.5
 3. 涉及的其他产品使用的版本号：
  无
 5. 训练环境信息：
  a. 具体操作系统=Linux 
  b. Python版本号=Python3.9
  c. CUDA/cuDNN版本=CUDA11.6、cuDNN 8.4

代码报错
```2022/10/31 14:35:12] ppcls INFO: [Train][Epoch 10/20][Avg]top1: 0.88217, top2: 1.00000, CELoss: 0.27312, loss: 0.27312
Traceback (most recent call last):
  File "/home/r1/PaddleClas/tools/train.py", line 32, in <module>
    engine.train()
  File "/home/r1/PaddleClas/ppcls/engine/engine.py", line 372, in train
    acc = self.eval(epoch_id)
  File "/home/r1/anaconda3/envs/paddle_env/lib/python3.9/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/r1/anaconda3/envs/paddle_env/lib/python3.9/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/r1/PaddleClas/ppcls/engine/engine.py", line 451, in eval
    eval_result = self.eval_func(self, epoch_id)
  File "/home/r1/PaddleClas/ppcls/engine/evaluation/classification.py", line 157, in classification_eval    metric_msg += ", {}".format(engine.eval_metric_func.avg_info)
  File "/home/r1/PaddleClas/ppcls/metric/__init__.py", line 53, in avg_info
    return ", ".join([metric.avg_info for metric in self.metric_func_list])
  File "/home/r1/PaddleClas/ppcls/metric/__init__.py", line 53, in <listcomp>
    return ", ".join([metric.avg_info for metric in self.metric_func_list])
  File "/home/r1/PaddleClas/ppcls/metric/metrics.py", line 208, in avg_info
    threshold, fpr, tpr)
```

问题代码截图(PaddleClas/ppcls/metric/metrics.py line 208, in avg_info)
![image](https://user-images.githubusercontent.com/8815759/198947813-ef81f57f-ac70-434b-91e4-5c64b68e42de.png)

**Comment by cuicheng01** [comment]
问题已收到，我们近期会看下

**Comment by cuicheng01** [comment]
bug已修复，请参考最新的代码,相关[PR](https://github.com/PaddlePaddle/PaddleClas/pull/2494)
