### ISSUE TITLE
预测时指定了模型依然会下载预训练模型、提示缺少sync_batch_norm

### ISSUE THREAD

**Issue by dium6i** [PaddlePaddle/PaddleClas#2455]
使用 ./ppcls/configs/PULC/person_exists/PPLCNet_x1_0_search.yaml 在 Ai Studio 使用PaddleClas 2.5 训练好的模型，放到本地机器，在使用如下命令进行推理时，指定了模型，但还是要下载预训练模型，怎么解决？（机器不联网）
!python tools/infer.py \
    -c ./ppcls/configs/PULC/person_exists/PPLCNet_x1_0_search.yaml \
    -o Global.pretrained_model=./output/PPLCNet_x1_0/best_model

同时在 Ai Studio 上使用如下代码测试的时候，报错，提示如下：
测试代码：
%cd /home/aistudio/work/PaddleClas/
!python tools/infer.py \
    -c ./ppcls/configs/PULC/person_exists/PPLCNet_x1_0_search.yaml \
    -o Global.device=cpu \
    -o Global.pretrained_model=./output/PPLCNet_x1_0/best_model

报错信息：
Traceback (most recent call last):
  File "tools/infer.py", line 31, in <module>
    engine.infer()
  File "<decorator-gen-551>", line 2, in infer
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/aistudio/work/PaddleClas/ppcls/engine/engine.py", line 486, in infer
    out = self.model(batch_tensor)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleClas/ppcls/arch/backbone/legendary_models/pp_lcnet.py", line 314, in forward
    x = self.conv1(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/home/aistudio/work/PaddleClas/ppcls/arch/backbone/legendary_models/pp_lcnet.py", line 112, in forward
    x = self.bn(x)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 930, in __call__
    return self._dygraph_call_func(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 915, in _dygraph_call_func
    outputs = self.forward(*inputs, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/nn/layer/norm.py", line 1096, in forward
    sync_batch_norm_out, _, _, _, _, _ = _C_ops.sync_batch_norm(
AttributeError: module 'paddle.fluid.core_avx.ops' has no attribute 'sync_batch_norm'

**Comment by weisy11** [comment]
推理模型跟预训练模型是不同的模型，用不同的代码，不能互换。https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_person_exists.md
分别对应文档的3.5节和6.1节
另外建议检查一下本地paddle的版本和aistudio是否一致。

**Comment by dium6i** [comment]
> 推理模型跟预训练模型是不同的模型，用不同的代码，不能互换。https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_person_exists.md 分别对应文档的3.5节和6.1节 另外建议检查一下本地paddle的版本和aistudio是否一致。

我的意思是，模型训练好了，我拿训练好的模型进行预测时，还是会联网下载训练模型时用的预训练模型，我在预测时指定的模型没用上。

**Comment by TingquanGao** [comment]
这个问题的话，可以试试下面的命令：

```bash
%cd /home/aistudio/work/PaddleClas/
!python tools/infer.py
-c ./ppcls/configs/PULC/person_exists/PPLCNet_x1_0_search.yaml
-o Global.device=cpu
-o Global.pretrained_model=./output/PPLCNet_x1_0/best_model
-o Arch.pretrained=False
```

其中，设置 `-o Arch.pretrained=False` 后就不会下载imagenet1k的pretrain了。

**Comment by TingquanGao** [comment]
另外，关于sync bn的报错已经修了，可以参考 #2485

**Comment by dium6i** [comment]
> 这个问题的话，可以试试下面的命令：
> 
> ```shell
> %cd /home/aistudio/work/PaddleClas/
> !python tools/infer.py
> -c ./ppcls/configs/PULC/person_exists/PPLCNet_x1_0_search.yaml
> -o Global.device=cpu
> -o Global.pretrained_model=./output/PPLCNet_x1_0/best_model
> -o Arch.pretrained=False
> ```
> 
> 其中，设置 `-o Arch.pretrained=False` 后就不会下载imagenet1k的pretrain了。

感谢！

**Comment by TingquanGao** [comment]
上面关于sync bn报错的修复pr已经合入了develop分支和release/2.5分支，可以拉取最新代码再试试。
