### ISSUE TITLE
在 Python 代码中预测报错

### ISSUE THREAD

**Issue by mark-chinese** [PaddlePaddle/PaddleClas#2561]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. paddlepaddle       2.4.1
 2. paddleclas         2.4.0
 3. 训练环境信息：
  a. 具体操作系统：Windows
  b. Python版本号：Python3.7
  c. 虚拟环境：Anaconda

源码如下：

from paddleclas import PaddleClas
import warnings

warnings.filterwarnings('ignore')
infer_imgs = r'D:\Files\python\images\fff587897edb4a49a2497fe10610d335.jpg'
clas = PaddleClas(
    model_name='PPLCNet_x0_25',
    inference_model_dir='D:/Project/My/python/paddleclas-demo/model/PPLCNet_x0_25',
    class_id_map_file='D:/Project/My/python/paddleclas-demo/model/ccj_label_list.txt',
    topk=2,
    use_gpu=False
)
result = clas.predict(infer_imgs)
print(next(result))

 报错代码：

Traceback (most recent call last):
  File "D:/Project/My/python/paddleclas-demo/main.py", line 37, in <module>
    print(next(result))
  File "D:\ProgramData\.conda\envs\paddleclas\lib\site-packages\paddleclas\paddleclas.py", line 573, in predict
    preds = self.cls_predictor.predict(img_list)
  File "D:\ProgramData\.conda\envs\paddleclas\lib\site-packages\paddleclas\deploy\python\predict_cls.py", line 109, in predict
    batch_output = self.postprocess(batch_output)
  File "D:\ProgramData\.conda\envs\paddleclas\lib\site-packages\paddleclas\deploy\python\postprocess.py", line 50, in __call__
    tmp = func(x, image_file)
  File "D:\ProgramData\.conda\envs\paddleclas\lib\site-packages\paddleclas\deploy\python\postprocess.py", line 127, in __call__
    label_name_list.append(self.class_id_map[i.item()])
KeyError: 605

ccj_label_list.txt
0 gun
1 signal

在源码postprocess.py第123行报错

            for i in index:
                clas_id_list.append(i.item())
                score_list.append(probs[i].item())
                if self.class_id_map is not None:
                    label_name_list.append(self.class_id_map[i.item()])

这里的index为[605,704]，正常应该是ccj_label_list.txt里[0,1]，请问是哪里配置错误？

**Comment by mark-chinese** [comment]
已经解决。
1. windows系统
   在"C:\Users\用户名\.paddleclas\inference_model\IMN\PPLCNet_x0_25"文件夹的inference.pdiparams、inference.pdiparams.info和inference.pdmodel三个文件替换自己的模型，这里的PPLCNet_x0_25对应训练使用的模型名称。

2. linux系统
   在"/root/.paddleclas/inference_model/IMN/PPLCNet_x0_25"文件夹的inference.pdiparams、inference.pdiparams.info和inference.pdmodel三个文件替换自己的模型，这里的PPLCNet_x0_25对应训练使用的模型名称。
