### ISSUE TITLE
Cannot train PULC Classification Model of Language: Illegal index value

### ISSUE THREAD

**Issue by AbitraryYu** [PaddlePaddle/PaddleClas#2597]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！

What happened?
I am following the instructions from [PULC offical ENG language language classification](https://github.com/PaddlePaddle/PaddleClas/blob/develop/docs/en/PULC/PULC_language_classification_en.md). Step 1 to 3.2 is fine. 

I use the original datasets provided from PaddleClas (example dataset) and the [Multi-lingual scene text detection and recognition](https://rrc.cvc.uab.es/?ch=15&com=downloads) (only Chinese word datasets, from Task 2: Cropped Word Script identification ) advised from the manual.

The original datasets are in the `img` folder and the multi-lingual dataset are in the `img2` folder (See point 4 `train.txt`)

Cannot train on step 3.3 (See Point number 4 for logs).

提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
    paddleclas (develop version), got it from `git clone https://github.com/PaddlePaddle/PaddleClas.git -b develop`

 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
    Nil. Just PaddleClas
 
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS:
       Google colab notebook

  b. Python版本号，如Python3.6/7/8
      python 3.8.16

  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
    CUDA 11.2/cudnn 8.1

 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
 No code changes in repo, but the file structure inside pulc have the following changes.
```
├── img
│   ├── word_1.png
│   ├── word_2.png
├── img2
│   ├── word_19866.png
│   ├── word_19867.png
...
│   ├── word_27634.png
...
├── train_list.txt
├── train_list_for_distill.txt
├── test_list.txt
└── label_list.txt
```

train_list.txt
```
...
img/word_6618.png 3
img/word_6619.png 3
img/word_6620.png 3
img/word_6621.png 3
img/word_6622.png 3
img/word_6623.png 3
img/word_6624.png 3
img2/word_19866.png 4
img2/word_19867.png 4
img2/word_19869.png 4
img2/word_19871.png 4
img2/word_19872.png 4
img2/word_19873.png 4
img2/word_19875.png 4
img2/word_19876.png 4
img2/word_19877.png 4
img2/word_19879.png 4
...
``` 
 
Logs:
```python
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: profile 'ICC Profile': 'RGB ': RGB color space not permitted on grayscale PNG
libpng warning: iCCP: known incorrect sRGB profile
W0116 04:19:18.195961  1664 gpu_resources.cc:217] WARNING: device: �. The installed Paddle is compiled with CUDNN 8.2, but CUDNN version in your machine is 8.1, which may cause serious incompatible bug. Please recompile or reinstall Paddle with compatible CUDNN version.
libpng warning: iCCP: known incorrect sRGB profile
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].

Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "/content/PaddleClas/ppcls/engine/engine.py", line 393, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/content/PaddleClas/ppcls/engine/train/train.py", line 72, in train_epoch
    loss.backward()
  File "<decorator-gen-157>", line 2, in backward
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)

LAUNCH INFO 2023-01-16 04:19:27,946 Pod failed
LAUNCH ERROR 2023-01-16 04:19:27,947 Container failed !!!
Container rank 0 status failed cmd ['/usr/bin/python3', '-u', 'tools/train.py', '-c', './ppcls/configs/PULC/language_classification/PPLCNet_x1_0.yaml', '-o', 'Arch.class_num=4'] code 1 log log/workerlog.0 
env {'NV_LIBCUBLAS_DEV_VERSION': '11.4.1.1043-1', 'NV_CUDA_COMPAT_PACKAGE': 'cuda-compat-11-2', '__EGL_VENDOR_LIBRARY_DIRS': '/usr/lib64-nvidia:/usr/share/glvnd/egl_vendor.d/', 'NV_CUDNN_PACKAGE_DEV': 'libcudnn8-dev=8.1.1.33-1+cuda11.2', 'PYDEVD_USE_FRAME_EVAL': 'NO', 'LD_LIBRARY_PATH': '/usr/local/lib/python3.8/dist-packages/cv2/../../lib64:/usr/lib64-nvidia', 'NV_LIBNCCL_DEV_PACKAGE': 'libnccl-dev=2.8.4-1+cuda11.2', 'TCLLIBPATH': '/usr/share/tcltk/tcllib1.19', 'CLOUDSDK_PYTHON': 'python3', 'LANG': 'en_US.UTF-8', 'NV_LIBNPP_DEV_PACKAGE': 'libnpp-dev-11-2=11.3.2.152-1', 'ENABLE_DIRECTORYPREFETCHER': '1', 'HOSTNAME': '7a273e6fecce', 'OLDPWD': '/', 'CLOUDSDK_CONFIG': '/content/.config', 'USE_AUTH_EPHEM': '1', 'KMP_EXTRA_ARGS': '--listen_host=172.28.0.2 --target_host=172.28.0.2 --tunnel_background_save_url=https://colab.research.google.com/tun/m/cc48301118ce562b961b3c22d803539adc1e0c19/gpu-t4-s-24inkprm8mait --tunnel_background_save_delay=10s --tunnel_periodic_background_save_frequency=30m0s --enable_output_coalescing=true --output_coalescing_required=true', 'NV_LIBNPP_VERSION': '11.3.2.152-1', 'NV_NVPROF_DEV_PACKAGE': 'cuda-nvprof-11-2=11.2.152-1', 'NVIDIA_VISIBLE_DEVICES': 'all', 'NV_NVPROF_VERSION': '11.2.152-1', 'NV_LIBCUSPARSE_VERSION': '11.4.1.1152-1', 'DATALAB_SETTINGS_OVERRIDES': '{"kernelManagerProxyPort":6000,"kernelManagerProxyHost":"172.28.0.2","jupyterArgs":["--ip=172.28.0.2"],"debugAdapterMultiplexerPath":"/usr/local/bin/dap_multiplexer","enableLsp":true}', 'NV_LIBCUBLAS_DEV_PACKAGE': 'libcublas-dev-11-2=11.4.1.1043-1', 'COLAB_RELEASE_TAG': 'release-colab-20230109-060104-RC00', 'ENV': '/root/.bashrc', 'PAGER': 'cat', 'NCCL_VERSION': '2.8.4-1', 'COLAB_BACKEND_VERSION': 'default', 'TF_FORCE_GPU_ALLOW_GROWTH': 'true', 'JPY_PARENT_PID': '89', 'NO_GCE_CHECK': 'False', 'PWD': '/content/PaddleClas', 'NVARCH': 'x86_64', 'NV_LIBCUSPARSE_DEV_VERSION': '11.4.1.1152-1', 'HOME': '/root', 'KMP_LISTEN_PORT': '6000', 'LAST_FORCED_REBUILD': '20221207', 'CLICOLOR': '1', 'NV_LIBNCCL_PACKAGE_VERSION': '2.8.4-1', 'NV_LIBNCCL_PACKAGE': 'libnccl2=2.8.4-1+cuda11.2', 'DEBIAN_FRONTEND': 'noninteractive', 'NV_LIBNCCL_DEV_PACKAGE_NAME': 'libnccl-dev', 'NV_CUDA_LIB_VERSION': '11.2.2-1', 'NV_LIBNPP_PACKAGE': 'libnpp-11-2=11.3.2.152-1', 'NV_LIBNCCL_PACKAGE_NAME': 'libnccl2', 'LIBRARY_PATH': '/usr/local/cuda/lib64/stubs', 'NV_NVTX_VERSION': '11.2.152-1', 'NV_LIBCUBLAS_VERSION': '11.4.1.1043-1', 'NV_LIBCUBLAS_PACKAGE': 'libcublas-11-2=11.4.1.1043-1', 'GCE_METADATA_TIMEOUT': '3', 'NV_CUDNN_VERSION': '8.1.1.33', 'VM_GCE_METADATA_HOST': '169.254.169.253', 'NV_CUDA_CUDART_DEV_VERSION': '11.2.152-1', 'KMP_TARGET_PORT': '9000', 'GLIBCPP_FORCE_NEW': '1', 'TBE_CREDS_ADDR': '172.28.0.1:8008', 'TERM': 'xterm-color', 'SHELL': '/bin/bash', 'GCS_READ_CACHE_BLOCK_SIZE_MB': '16', 'NV_NVML_DEV_VERSION': '11.2.152-1', 'PYTHONWARNINGS': 'ignore:::pip._internal.cli.base_command', 'MPLBACKEND': 'module://ipykernel.pylab.backend_inline', 'CUDA_VERSION': '11.2.2', 'NV_LIBCUBLAS_PACKAGE_NAME': 'libcublas-11-2', 'NVIDIA_DRIVER_CAPABILITIES': 'compute,utility', 'TBE_RUNTIME_ADDR': '172.28.0.1:8011', 'SHLVL': '1', 'PYTHONPATH': '/env/python', 'NV_LIBCUBLAS_DEV_PACKAGE_NAME': 'libcublas-dev-11-2', 'NVIDIA_REQUIRE_CUDA': 'cuda>=11.2 brand=tesla,driver>=418,driver<419 brand=tesla,driver>=450,driver<451', 'NV_LIBNPP_DEV_VERSION': '11.3.2.152-1', 'TBE_EPHEM_CREDS_ADDR': '172.28.0.1:8009', 'NV_CUDA_CUDART_VERSION': '11.2.152-1', 'NV_CUDNN_PACKAGE_NAME': 'libcudnn8', 'GLIBCXX_FORCE_NEW': '1', 'PATH': '/opt/bin:/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-sdk/bin', 'NV_LIBNCCL_DEV_PACKAGE_VERSION': '2.8.4-1', 'LD_PRELOAD': '/usr/lib/x86_64-linux-gnu/libtcmalloc.so.4', 'NV_CUDNN_PACKAGE': 'libcudnn8=8.1.1.33-1+cuda11.2', 'CGROUP_MEMORY_EVENTS': '/sys/fs/cgroup/memory.events /var/colab/cgroup/jupyter-children/memory.events', 'GIT_PAGER': 'cat', '_': '/usr/bin/python3', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/usr/local/lib/python3.8/dist-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/usr/local/lib/python3.8/dist-packages/cv2/qt/fonts', 'POD_NAME': 'qcnjek', 'PADDLE_MASTER': '172.28.0.2:37824', 'PADDLE_GLOBAL_SIZE': '1', 'PADDLE_LOCAL_SIZE': '1', 'PADDLE_GLOBAL_RANK': '0', 'PADDLE_LOCAL_RANK': '0', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '172.28.0.2:37825', 'PADDLE_CURRENT_ENDPOINT': '172.28.0.2:37825', 'PADDLE_TRAINER_ID': '0', 'PADDLE_TRAINERS_NUM': '1', 'PADDLE_RANK_IN_NODE': '0', 'FLAGS_selected_gpus': '0'}
LAUNCH INFO 2023-01-16 04:19:27,947 ------------------------- ERROR LOG DETAIL -------------------------
in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Error: /paddle/paddle/phi/kernels/gpu/one_hot_kernel.cu:38 Assertion `p_in_data[idx] >= 0 && p_in_data[idx] < depth` failed. Illegal index value, Input(input) value should be greater than or equal to 0, and less than depth [4], but received [4].
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "/content/PaddleClas/ppcls/engine/engine.py", line 393, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/content/PaddleClas/ppcls/engine/train/train.py", line 72, in train_epoch
    loss.backward()
  File "<decorator-gen-157>", line 2, in backward
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/paddle/fluid/dygraph/varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUBLAS error(13). 
  [Hint: Please search for the error code(13) on website (https://docs.nvidia.com/cuda/cublas/index.html#cublasstatus_t) to get Nvidia's official solution and advice about CUBLAS Error.] (at /paddle/paddle/phi/kernels/funcs/blas/blas_impl.cu.h:35)

LAUNCH INFO 2023-01-16 04:19:27,947 Exit code 1
```
Attached here are the full logs for reference
[full_logs.txt](https://github.com/PaddlePaddle/PaddleClas/files/10422568/full_logs.txt)

**Comment by cuicheng01** [comment]
请问您的训练命令是什么呢

**Comment by AbitraryYu** [comment]
```
!python3 -m paddle.distributed.launch \
    --gpus="0" \
    tools/train.py \
        -c ./ppcls/configs/PULC/language_classification/PPLCNet_x1_0.yaml \
        -o Arch.class_num=4
```

Since there's only one GPU in google colab, I specified --gpu="0"

**Comment by BuiTuanrbt** [comment]
did you solved this issue?
