### ISSUE TITLE
paddlecls 模型训练报错，前几天还好好的！

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/PaddleClas#2733]
工程师，您好，请问这为什么问题，前几天训练的时候还好好的！

Traceback (most recent call last):
  File "./tools/train.py", line 32, in <module>
    engine.train()
  File "D:\xiaoxiong-d\PaddleClas\ppcls\engine\engine.py", line 356, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "D:\xiaoxiong-d\PaddleClas\ppcls\engine\train\train.py", line 67, in train_epoch
    loss.backward()
  File "D:\Anaconda\envs\PaddleClas\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "D:\Anaconda\envs\PaddleClas\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 26, in __impl__
    return wrapped_func(*args, **kwargs)
  File "D:\Anaconda\envs\PaddleClas\lib\site-packages\paddle\fluid\framework.py", line 534, in __impl__
    return func(*args, **kwargs)
  File "D:\Anaconda\envs\PaddleClas\lib\site-packages\paddle\fluid\dygraph\varbase_patch_methods.py", line 297, in backward
    core.eager.run_backward([self], grad_tensor, retain_graph)
OSError: (External) CUDNN error(8), CUDNN_STATUS_EXECUTION_FAILED.
  [Hint: Please search for the error code(8) on website (https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnStatus_t) to get Nvidia's official soluti
on and advice about CUDNN Error.] (at C:\home\workspace\Paddle\paddle\phi\kernels\gpudnn\conv_grad_kernel.cu:502)

**Comment by cuicheng01** [comment]
应该是本地的环境出现了问题，建议重新配置环境

**Comment by happybear1015** [comment]
谢谢
