### ISSUE TITLE
本地训练模型不报错，在BML上训练就报错了

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/PaddleClas#2735]
![Snipaste_2023-04-03_12-20-37](https://user-images.githubusercontent.com/66996161/229419225-d35e83b7-ba20-45ae-a514-11500cbf641e.png)

**Comment by cuicheng01** [comment]
可能是共享内存不够，要们扩大共享内存，要么把nunmwoker改为0

**Comment by happybear1015** [comment]
您好，修改完后，能训练起来，但是刚训练开始，一会就报错了！

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/setuptools/depends.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/__init__.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import MutableMapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/rcsetup.py:20: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Iterable, Mapping
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/matplotlib/colors.py:53: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Sized
[2023/04/25 12:41:28] ppcls INFO: 
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

[2023/04/25 12:41:28] ppcls INFO: Arch : 
[2023/04/25 12:41:28] ppcls INFO:     class_num : 2
[2023/04/25 12:41:28] ppcls INFO:     name : ResNet101_vd
[2023/04/25 12:41:28] ppcls INFO: DataLoader : 
[2023/04/25 12:41:28] ppcls INFO:     Eval : 
[2023/04/25 12:41:28] ppcls INFO:         dataset : 
[2023/04/25 12:41:28] ppcls INFO:             cls_label_path : ./dataset/val_list.txt
[2023/04/25 12:41:28] ppcls INFO:             image_root : ./dataset/
[2023/04/25 12:41:28] ppcls INFO:             name : ImageNetDataset
[2023/04/25 12:41:28] ppcls INFO:             transform_ops : 
[2023/04/25 12:41:28] ppcls INFO:                 DecodeImage : 
[2023/04/25 12:41:28] ppcls INFO:                     channel_first : False
[2023/04/25 12:41:28] ppcls INFO:                     to_rgb : True
[2023/04/25 12:41:28] ppcls INFO:                 ResizeImage : 
[2023/04/25 12:41:28] ppcls INFO:                     resize_short : 448
[2023/04/25 12:41:28] ppcls INFO:                 CropImage : 
[2023/04/25 12:41:28] ppcls INFO:                     size : 448
[2023/04/25 12:41:28] ppcls INFO:                 NormalizeImage : 
[2023/04/25 12:41:28] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/04/25 12:41:28] ppcls INFO:                     order : 
[2023/04/25 12:41:28] ppcls INFO:                     scale : 1.0/255.0
[2023/04/25 12:41:28] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/04/25 12:41:28] ppcls INFO:         loader : 
[2023/04/25 12:41:28] ppcls INFO:             num_workers : 4
[2023/04/25 12:41:28] ppcls INFO:             use_shared_memory : True
[2023/04/25 12:41:28] ppcls INFO:         sampler : 
[2023/04/25 12:41:28] ppcls INFO:             batch_size : 32
[2023/04/25 12:41:28] ppcls INFO:             drop_last : False
[2023/04/25 12:41:28] ppcls INFO:             name : DistributedBatchSampler
[2023/04/25 12:41:28] ppcls INFO:             shuffle : False
[2023/04/25 12:41:28] ppcls INFO:     Train : 
[2023/04/25 12:41:28] ppcls INFO:         dataset : 
[2023/04/25 12:41:28] ppcls INFO:             batch_transform_ops : None
[2023/04/25 12:41:28] ppcls INFO:             cls_label_path : ./dataset/train_list.txt
[2023/04/25 12:41:28] ppcls INFO:             image_root : ./dataset/
[2023/04/25 12:41:28] ppcls INFO:             name : ImageNetDataset
[2023/04/25 12:41:28] ppcls INFO:             transform_ops : 
[2023/04/25 12:41:28] ppcls INFO:                 DecodeImage : 
[2023/04/25 12:41:28] ppcls INFO:                     channel_first : False
[2023/04/25 12:41:28] ppcls INFO:                     to_rgb : True
[2023/04/25 12:41:28] ppcls INFO:                 RandCropImage : 
[2023/04/25 12:41:28] ppcls INFO:                     size : 448
[2023/04/25 12:41:28] ppcls INFO:                 RandFlipImage : 
[2023/04/25 12:41:28] ppcls INFO:                     flip_code : 1
[2023/04/25 12:41:28] ppcls INFO:                 NormalizeImage : 
[2023/04/25 12:41:28] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/04/25 12:41:28] ppcls INFO:                     order : 
[2023/04/25 12:41:28] ppcls INFO:                     scale : 1.0/255.0
[2023/04/25 12:41:28] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/04/25 12:41:28] ppcls INFO:         loader : 
[2023/04/25 12:41:28] ppcls INFO:             num_workers : 0
[2023/04/25 12:41:28] ppcls INFO:             use_shared_memory : True
[2023/04/25 12:41:28] ppcls INFO:         sampler : 
[2023/04/25 12:41:28] ppcls INFO:             batch_size : 32
[2023/04/25 12:41:28] ppcls INFO:             drop_last : False
[2023/04/25 12:41:28] ppcls INFO:             name : DistributedBatchSampler
[2023/04/25 12:41:28] ppcls INFO:             shuffle : True
[2023/04/25 12:41:28] ppcls INFO: Global : 
[2023/04/25 12:41:28] ppcls INFO:     checkpoints : None
[2023/04/25 12:41:28] ppcls INFO:     device : gpu
[2023/04/25 12:41:28] ppcls INFO:     epochs : 200
[2023/04/25 12:41:28] ppcls INFO:     eval_during_train : True
[2023/04/25 12:41:28] ppcls INFO:     eval_interval : 1
[2023/04/25 12:41:28] ppcls INFO:     image_shape : [3, 448, 448]
[2023/04/25 12:41:28] ppcls INFO:     output_dir : ./output/
[2023/04/25 12:41:28] ppcls INFO:     pretrained_model : None
[2023/04/25 12:41:28] ppcls INFO:     print_batch_step : 10
[2023/04/25 12:41:28] ppcls INFO:     save_inference_dir : ./inference
[2023/04/25 12:41:28] ppcls INFO:     save_interval : 1
[2023/04/25 12:41:28] ppcls INFO:     use_visualdl : Ture
[2023/04/25 12:41:28] ppcls INFO: Infer : 
[2023/04/25 12:41:28] ppcls INFO:     PostProcess : 
[2023/04/25 12:41:28] ppcls INFO:         class_id_map_file : dataset/label_list.txt
[2023/04/25 12:41:28] ppcls INFO:         name : Topk
[2023/04/25 12:41:28] ppcls INFO:         topk : 5
[2023/04/25 12:41:28] ppcls INFO:     batch_size : 10
[2023/04/25 12:41:28] ppcls INFO:     infer_imgs : docs/images/inference_deployment/whl_demo.jpg
[2023/04/25 12:41:28] ppcls INFO:     transforms : 
[2023/04/25 12:41:28] ppcls INFO:         DecodeImage : 
[2023/04/25 12:41:28] ppcls INFO:             channel_first : False
[2023/04/25 12:41:28] ppcls INFO:             to_rgb : True
[2023/04/25 12:41:28] ppcls INFO:         ResizeImage : 
[2023/04/25 12:41:28] ppcls INFO:             resize_short : 448
[2023/04/25 12:41:28] ppcls INFO:         CropImage : 
[2023/04/25 12:41:28] ppcls INFO:             size : 448
[2023/04/25 12:41:28] ppcls INFO:         NormalizeImage : 
[2023/04/25 12:41:28] ppcls INFO:             mean : [0.485, 0.456, 0.406]
[2023/04/25 12:41:28] ppcls INFO:             order : 
[2023/04/25 12:41:28] ppcls INFO:             scale : 1.0/255.0
[2023/04/25 12:41:28] ppcls INFO:             std : [0.229, 0.224, 0.225]
[2023/04/25 12:41:28] ppcls INFO:         ToCHWImage : None
[2023/04/25 12:41:28] ppcls INFO: Loss : 
[2023/04/25 12:41:28] ppcls INFO:     Eval : 
[2023/04/25 12:41:28] ppcls INFO:         CELoss : 
[2023/04/25 12:41:28] ppcls INFO:             weight : 1.0
[2023/04/25 12:41:28] ppcls INFO:     Train : 
[2023/04/25 12:41:28] ppcls INFO:         CELoss : 
[2023/04/25 12:41:28] ppcls INFO:             epsilon : 0.1
[2023/04/25 12:41:28] ppcls INFO:             weight : 1.0
[2023/04/25 12:41:28] ppcls INFO: Metric : 
[2023/04/25 12:41:28] ppcls INFO:     Eval : 
[2023/04/25 12:41:28] ppcls INFO:         TopkAcc : 
[2023/04/25 12:41:28] ppcls INFO:             topk : [1, 5]
[2023/04/25 12:41:28] ppcls INFO:     Train : None
[2023/04/25 12:41:28] ppcls INFO: Optimizer : 
[2023/04/25 12:41:28] ppcls INFO:     lr : 
[2023/04/25 12:41:28] ppcls INFO:         learning_rate : 0.1
[2023/04/25 12:41:28] ppcls INFO:         name : Cosine
[2023/04/25 12:41:28] ppcls INFO:     momentum : 0.9
[2023/04/25 12:41:28] ppcls INFO:     name : Momentum
[2023/04/25 12:41:28] ppcls INFO:     regularizer : 
[2023/04/25 12:41:28] ppcls INFO:         coeff : 0.0001
[2023/04/25 12:41:28] ppcls INFO:         name : L2
[2023/04/25 12:41:28] ppcls INFO: profiler_options : None
[2023/04/25 12:41:28] ppcls INFO: train with paddle 2.3.0 and device Place(gpu:0)
W0425 12:41:28.190657  4764 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.2, Runtime API Version: 10.1
W0425 12:41:28.204097  4764 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
[2023/04/25 12:41:33] ppcls WARNING: The training strategy provided by PaddleClas is based on 4 gpus. But the number of gpu is 1 in current training. Please modify the stategy (learning rate, batch size and so on) if use this config to train.
[2023/04/25 12:41:34] ppcls INFO: [Train][Epoch 1/200][Iter: 0/3]lr(CosineAnnealingDecay): 0.09999863, CELoss: 0.75557, loss: 0.75557, batch_cost: 1.15992s, reader_cost: 0.53172, ips: 27.58820 samples/s, eta: 0:11:35
[2023/04/25 12:41:35] ppcls INFO: [Train][Epoch 1/200][Avg]CELoss: 22.12115, loss: 22.12115
[2023/04/25 12:41:36] ppcls WARNING: The output dims(2) is less than k(5), and the argument 5 of Topk has been removed.
[2023/04/25 12:41:36] ppcls INFO: [Eval][Epoch 1][Iter: 0/1]CELoss: 11064650724540416.00000, loss: 11064650724540416.00000, top1: 0.52381, batch_cost: 0.73126s, reader_cost: 0.58457, ips: 28.71756 images/sec
[2023/04/25 12:41:36] ppcls INFO: [Eval][Epoch 1][Avg]CELoss: 11064650724540416.00000, loss: 11064650724540416.00000, top1: 0.52381
[2023/04/25 12:41:37] ppcls INFO: Already save model in ./output/ResNet101_vd/best_model
[2023/04/25 12:41:37] ppcls INFO: [Eval][Epoch 1][best metric: 0.523809552192688]
[2023/04/25 12:41:38] ppcls INFO: Already save model in ./output/ResNet101_vd/epoch_1
[2023/04/25 12:41:39] ppcls INFO: Already save model in ./output/ResNet101_vd/latest
[2023/04/25 12:41:40] ppcls INFO: [Train][Epoch 2/200][Iter: 0/3]lr(CosineAnnealingDecay): 0.09998424, CELoss: 13.56066, loss: 13.56066, batch_cost: 0.79554s, reader_cost: 0.22954, ips: 40.22435 samples/s, eta: 0:07:54
[2023/04/25 12:41:41] ppcls INFO: [Train][Epoch 2/200][Avg]CELoss: 9.26015, loss: 9.26015
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 530, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 632, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 4857

Traceback (most recent call last):
  File "./tools/train.py", line 32, in <module>
    engine.train()
  File "/home/work/PaddleClas/ppcls/engine/engine.py", line 372, in train
    acc = self.eval(epoch_id)
  File "</opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/decorator.py:decorator-gen-548>", line 2, in eval
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 354, in _decorate_function
    return func(*args, **kwargs)
  File "/home/work/PaddleClas/ppcls/engine/engine.py", line 451, in eval
    eval_result = self.eval_func(self, epoch_id)
  File "/home/work/PaddleClas/ppcls/engine/evaluation/classification.py", line 44, in classification_eval
    for iter_id, batch in enumerate(engine.eval_dataloader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 742, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)
