### ISSUE TITLE
双卡训练报错 (External) CUDA error(2), out of memory.

### ISSUE THREAD

**Issue by happybear1015** [PaddlePaddle/PaddleClas#2749]
1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas 2.5和PaddlePaddle_gpu 2.4
 2. 涉及的其他产品使用的版本号：no
 3. 训练环境信息：
  a. 具体操作系统，如Linux
  b. Python版本号，如Python3.8
  c. CUDA/cuDNN版本， 如CUDA11.7/cuDNN 8.8等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log
(paddle_gpu) uvtec@uvtec-MS-7B98:~/桌面/PaddleClas$ python -m paddle.distributed.launch --gpus="0,1" tools/train.py -c ppcls/configs/ImageNet/ResNet/ResNet101_vd.yaml
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
LAUNCH INFO 2023-04-12 10:37:25,213 -----------  Configuration  ----------------------
LAUNCH INFO 2023-04-12 10:37:25,213 devices: 0,1
LAUNCH INFO 2023-04-12 10:37:25,213 elastic_level: -1
LAUNCH INFO 2023-04-12 10:37:25,213 elastic_timeout: 30
LAUNCH INFO 2023-04-12 10:37:25,213 gloo_port: 6767
LAUNCH INFO 2023-04-12 10:37:25,213 host: None
LAUNCH INFO 2023-04-12 10:37:25,213 ips: None
LAUNCH INFO 2023-04-12 10:37:25,213 job_id: default
LAUNCH INFO 2023-04-12 10:37:25,213 legacy: False
LAUNCH INFO 2023-04-12 10:37:25,213 log_dir: log
LAUNCH INFO 2023-04-12 10:37:25,213 log_level: INFO
LAUNCH INFO 2023-04-12 10:37:25,213 master: None
LAUNCH INFO 2023-04-12 10:37:25,213 max_restart: 3
LAUNCH INFO 2023-04-12 10:37:25,213 nnodes: 1
LAUNCH INFO 2023-04-12 10:37:25,213 nproc_per_node: None
LAUNCH INFO 2023-04-12 10:37:25,213 rank: -1
LAUNCH INFO 2023-04-12 10:37:25,213 run_mode: collective
LAUNCH INFO 2023-04-12 10:37:25,213 server_num: None
LAUNCH INFO 2023-04-12 10:37:25,213 servers: 
LAUNCH INFO 2023-04-12 10:37:25,213 start_port: 6070
LAUNCH INFO 2023-04-12 10:37:25,213 trainer_num: None
LAUNCH INFO 2023-04-12 10:37:25,213 trainers: 
LAUNCH INFO 2023-04-12 10:37:25,213 training_script: tools/train.py
LAUNCH INFO 2023-04-12 10:37:25,213 training_script_args: ['-c', 'ppcls/configs/ImageNet/ResNet/ResNet101_vd.yaml']
LAUNCH INFO 2023-04-12 10:37:25,213 with_gloo: 1
LAUNCH INFO 2023-04-12 10:37:25,213 --------------------------------------------------
LAUNCH INFO 2023-04-12 10:37:25,213 Job: default, mode collective, replicas 1[1:1], elastic False
LAUNCH INFO 2023-04-12 10:37:25,216 Run Pod: ghenbx, replicas 2, status ready
LAUNCH INFO 2023-04-12 10:37:25,223 Watching Pod: ghenbx, replicas 2, status running
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[2023/04/12 10:37:26] ppcls INFO: 
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

[2023/04/12 10:37:26] ppcls INFO: Arch : 
[2023/04/12 10:37:26] ppcls INFO:     class_num : 2
[2023/04/12 10:37:26] ppcls INFO:     name : ResNet101_vd
[2023/04/12 10:37:26] ppcls INFO: DataLoader : 
[2023/04/12 10:37:26] ppcls INFO:     Eval : 
[2023/04/12 10:37:26] ppcls INFO:         dataset : 
[2023/04/12 10:37:26] ppcls INFO:             cls_label_path : ./dataset/val_list.txt
[2023/04/12 10:37:26] ppcls INFO:             image_root : ./dataset/
[2023/04/12 10:37:26] ppcls INFO:             name : ImageNetDataset
[2023/04/12 10:37:26] ppcls INFO:             transform_ops : 
[2023/04/12 10:37:26] ppcls INFO:                 DecodeImage : 
[2023/04/12 10:37:26] ppcls INFO:                     channel_first : False
[2023/04/12 10:37:26] ppcls INFO:                     to_rgb : True
[2023/04/12 10:37:26] ppcls INFO:                 ResizeImage : 
[2023/04/12 10:37:26] ppcls INFO:                     resize_short : 448
[2023/04/12 10:37:26] ppcls INFO:                 CropImage : 
[2023/04/12 10:37:26] ppcls INFO:                     size : 448
[2023/04/12 10:37:26] ppcls INFO:                 NormalizeImage : 
[2023/04/12 10:37:26] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/04/12 10:37:26] ppcls INFO:                     order : 
[2023/04/12 10:37:26] ppcls INFO:                     scale : 1.0/255.0
[2023/04/12 10:37:26] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/04/12 10:37:26] ppcls INFO:         loader : 
[2023/04/12 10:37:26] ppcls INFO:             num_workers : 4
[2023/04/12 10:37:26] ppcls INFO:             use_shared_memory : True
[2023/04/12 10:37:26] ppcls INFO:         sampler : 
[2023/04/12 10:37:26] ppcls INFO:             batch_size : 8
[2023/04/12 10:37:26] ppcls INFO:             drop_last : False
[2023/04/12 10:37:26] ppcls INFO:             name : DistributedBatchSampler
[2023/04/12 10:37:26] ppcls INFO:             shuffle : False
[2023/04/12 10:37:26] ppcls INFO:     Train : 
[2023/04/12 10:37:26] ppcls INFO:         dataset : 
[2023/04/12 10:37:26] ppcls INFO:             batch_transform_ops : None
[2023/04/12 10:37:26] ppcls INFO:             cls_label_path : ./dataset/train_list.txt
[2023/04/12 10:37:26] ppcls INFO:             image_root : ./dataset/
[2023/04/12 10:37:26] ppcls INFO:             name : ImageNetDataset
[2023/04/12 10:37:26] ppcls INFO:             transform_ops : 
[2023/04/12 10:37:26] ppcls INFO:                 DecodeImage : 
[2023/04/12 10:37:26] ppcls INFO:                     channel_first : False
[2023/04/12 10:37:26] ppcls INFO:                     to_rgb : True
[2023/04/12 10:37:26] ppcls INFO:                 RandCropImage : 
[2023/04/12 10:37:26] ppcls INFO:                     size : 448
[2023/04/12 10:37:26] ppcls INFO:                 RandFlipImage : 
[2023/04/12 10:37:26] ppcls INFO:                     flip_code : -1
[2023/04/12 10:37:26] ppcls INFO:                 NormalizeImage : 
[2023/04/12 10:37:26] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/04/12 10:37:26] ppcls INFO:                     order : 
[2023/04/12 10:37:26] ppcls INFO:                     scale : 1.0/255.0
[2023/04/12 10:37:26] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/04/12 10:37:26] ppcls INFO:         loader : 
[2023/04/12 10:37:26] ppcls INFO:             num_workers : 4
[2023/04/12 10:37:26] ppcls INFO:             use_shared_memory : True
[2023/04/12 10:37:26] ppcls INFO:         sampler : 
[2023/04/12 10:37:26] ppcls INFO:             batch_size : 8
[2023/04/12 10:37:26] ppcls INFO:             drop_last : False
[2023/04/12 10:37:26] ppcls INFO:             name : DistributedBatchSampler
[2023/04/12 10:37:26] ppcls INFO:             shuffle : True
[2023/04/12 10:37:26] ppcls INFO: Global : 
[2023/04/12 10:37:26] ppcls INFO:     checkpoints : None
[2023/04/12 10:37:26] ppcls INFO:     device : gpu
[2023/04/12 10:37:26] ppcls INFO:     epochs : 300
[2023/04/12 10:37:26] ppcls INFO:     eval_during_train : True
[2023/04/12 10:37:26] ppcls INFO:     eval_interval : 1
[2023/04/12 10:37:26] ppcls INFO:     image_shape : [3, 448, 448]
[2023/04/12 10:37:26] ppcls INFO:     output_dir : ./output/
[2023/04/12 10:37:26] ppcls INFO:     pretrained_model : None
[2023/04/12 10:37:26] ppcls INFO:     print_batch_step : 10
[2023/04/12 10:37:26] ppcls INFO:     save_inference_dir : ./inference
[2023/04/12 10:37:26] ppcls INFO:     save_interval : 1
[2023/04/12 10:37:26] ppcls INFO:     use_visualdl : True
[2023/04/12 10:37:26] ppcls INFO: Infer : 
[2023/04/12 10:37:26] ppcls INFO:     PostProcess : 
[2023/04/12 10:37:26] ppcls INFO:         class_id_map_file : ./dataset/label_2.txt
[2023/04/12 10:37:26] ppcls INFO:         name : Topk
[2023/04/12 10:37:26] ppcls INFO:         topk : 5
[2023/04/12 10:37:26] ppcls INFO:     batch_size : 10
[2023/04/12 10:37:26] ppcls INFO:     infer_imgs : docs/images/inference_deployment/whl_demo.jpg
[2023/04/12 10:37:26] ppcls INFO:     transforms : 
[2023/04/12 10:37:26] ppcls INFO:         DecodeImage : 
[2023/04/12 10:37:26] ppcls INFO:             channel_first : False
[2023/04/12 10:37:26] ppcls INFO:             to_rgb : True
[2023/04/12 10:37:26] ppcls INFO:         ResizeImage : 
[2023/04/12 10:37:26] ppcls INFO:             resize_short : 448
[2023/04/12 10:37:26] ppcls INFO:         CropImage : 
[2023/04/12 10:37:26] ppcls INFO:             size : 448
[2023/04/12 10:37:26] ppcls INFO:         NormalizeImage : 
[2023/04/12 10:37:26] ppcls INFO:             mean : [0.485, 0.456, 0.406]
[2023/04/12 10:37:26] ppcls INFO:             order : 
[2023/04/12 10:37:26] ppcls INFO:             scale : 1.0/255.0
[2023/04/12 10:37:26] ppcls INFO:             std : [0.229, 0.224, 0.225]
[2023/04/12 10:37:26] ppcls INFO:         ToCHWImage : None
[2023/04/12 10:37:26] ppcls INFO: Loss : 
[2023/04/12 10:37:26] ppcls INFO:     Eval : 
[2023/04/12 10:37:26] ppcls INFO:         CELoss : 
[2023/04/12 10:37:26] ppcls INFO:             weight : 1.0
[2023/04/12 10:37:26] ppcls INFO:     Train : 
[2023/04/12 10:37:26] ppcls INFO:         CELoss : 
[2023/04/12 10:37:26] ppcls INFO:             epsilon : 0.1
[2023/04/12 10:37:26] ppcls INFO:             weight : 1.0
[2023/04/12 10:37:26] ppcls INFO: Metric : 
[2023/04/12 10:37:26] ppcls INFO:     Eval : 
[2023/04/12 10:37:26] ppcls INFO:         TopkAcc : 
[2023/04/12 10:37:26] ppcls INFO:             topk : [1, 5]
[2023/04/12 10:37:26] ppcls INFO:     Train : None
[2023/04/12 10:37:26] ppcls INFO: Optimizer : 
[2023/04/12 10:37:26] ppcls INFO:     lr : 
[2023/04/12 10:37:26] ppcls INFO:         learning_rate : 0.1
[2023/04/12 10:37:26] ppcls INFO:         name : Cosine
[2023/04/12 10:37:26] ppcls INFO:     momentum : 0.9
[2023/04/12 10:37:26] ppcls INFO:     name : Momentum
[2023/04/12 10:37:26] ppcls INFO:     regularizer : 
[2023/04/12 10:37:26] ppcls INFO:         coeff : 0.0001
[2023/04/12 10:37:26] ppcls INFO:         name : L2
[2023/04/12 10:37:26] ppcls INFO: profiler_options : None
[2023/04/12 10:37:26] ppcls INFO: train with paddle 2.4.2 and device Place(gpu:0)
W0412 10:37:28.252017 77017 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.7
W0412 10:37:28.252557 77017 gpu_resources.cc:91] device: 0, cuDNN Version: 8.8.
LAUNCH INFO 2023-04-12 10:37:29,228 Pod failed
LAUNCH ERROR 2023-04-12 10:37:29,228 Container failed !!!
Container rank 1 status failed cmd ['/home/uvtec/miniconda3/envs/paddle_gpu/bin/python', '-u', 'tools/train.py', '-c', 'ppcls/configs/ImageNet/ResNet/ResNet101_vd.yaml'] code 1 log log/workerlog.1 
env {'SHELL': '/bin/bash', 'SESSION_MANAGER': 'local/uvtec-MS-7B98:@/tmp/.ICE-unix/2449,unix/uvtec-MS-7B98:/tmp/.ICE-unix/2449', 'QT_ACCESSIBILITY': '1', 'SNAP_REVISION': '327', 'XDG_CONFIG_DIRS': '/etc/xdg/xdg-ubuntu:/etc/xdg', 'SSH_AGENT_LAUNCHER': 'gnome-keyring', 'XDG_MENU_PREFIX': 'gnome-', 'GNOME_DESKTOP_SESSION_ID': 'this-is-deprecated', 'GTK_IM_MODULE': 'fcitx', 'CONDA_EXE': '/home/uvtec/miniconda3/bin/conda', '_CE_M': '', 'SNAP_REAL_HOME': '/home/uvtec', 'TERMINAL_EMULATOR': 'JetBrains-JediTerm', 'SNAP_USER_COMMON': '/home/uvtec/snap/pycharm-community/common', 'LANGUAGE': 'zh_CN:en', 'LC_ADDRESS': 'zh_CN.UTF-8', 'GNOME_SHELL_SESSION_MODE': 'ubuntu', 'LC_NAME': 'zh_CN.UTF-8', 'SSH_AUTH_SOCK': '/run/user/1000/keyring/ssh', 'TERM_SESSION_ID': '57c2ec97-ef48-47f9-93f5-ff3bcb0fdbfb', 'SNAP_INSTANCE_KEY': '', 'XMODIFIERS': '@im=fcitx', 'DESKTOP_SESSION': 'ubuntu', 'LC_MONETARY': 'zh_CN.UTF-8', 'BAMF_DESKTOP_FILE_HINT': '/var/lib/snapd/desktop/applications/pycharm-community_pycharm-community.desktop', 'GTK_MODULES': 'gail:atk-bridge', 'PWD': '/home/uvtec/桌面/PaddleClas', 'XDG_SESSION_DESKTO: 'ubuntu', 'LOGNAME': 'uvtec', 'XDG_SESSION_TYPE': 'x11', 'CONDA_PREFIX': '/home/uvtec/miniconda3/envs/paddle_gpu', 'GPG_AGENT_INFO': '/run/user/1000/gnupg/S.gpg-agent:0:1', 'SYSTEMD_EXEC_PID': '2495', 'XAUTHORITY': '/run/user/1000/gdm/Xauthority', 'DESKTOP_STARTUP_ID': 'gnome-shell/PyCharm Community Edition/2495-5-uvtec-MS-7B98_TIME2911610', 'SNAP_CONTEXT': 'ZuJxgu1H3YdQT5tdItmx-E12K1RVMaIlPkc1wxfjrhKWDBj4BUYQ', 'GJS_DEBUG_TOPICS': 'JS ERROR;JS LOG', 'WINDOWPATH': '2', 'HOME': '/home/uvtec', 'USERNAME': 'uvtec', 'IM_CONFIG_PHASE': '1', 'LANG': 'zh_CN.UTF-8', 'LC_PAPER': 'zh_CN.UTF-8', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'XDG_CURRENT_DESKTOP': 'ubuntu:GNOME', 'SNAP_ARCH': 'amd64', 'SNAP_INSTANCE_NAME': 'pycharm-community', 'SNAP_USER_DATA': '/home/uvtec/snap/pycharm-community/327', 'CONDA_PROMPT_MODIFIER': '(paddle_gpu) ', 'INVOCATION_ID': '6d17a770a1b24382ae70cccd6d28034c', 'MANAGERPID': '2089', 'SNAP_REEXEC': '', 'CLUTTER_IM_MODULE': 'fcitx', 'GJS_DEBUG_OUTPUT': 'stderr', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'XDG_SESSION_CLASS': 'user', 'TERM': 'xterm-256color', 'LC_IDENTIFICATION': 'zh_CN.UTF-8', '_CE_CONDA': '', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'USER': 'uvtec', 'SNAP': '/snap/pycharm-community/327', 'CONDA_SHLVL': '2', 'SNAP_COMMON': '/var/snap/pycharm-community/common', 'SNAP_VERSION': '2023.1', 'DISPLAY': ':1', 'SHLVL': '1', 'SNAP_LIBRARY_PATH': '/var/lib/snapd/lib/gl:/var/lib/snapd/lib/gl32:/var/lib/snapd/void', 'SNAP_COOKIE': 'ZuJxgu1H3YdQT5tdItmx-E12K1RVMaIlPkc1wxfjrhKWDBj4BUYQ', 'LC_TELEPHONE': 'zh_CN.UTF-8', 'QT_IM_MODULE': 'fcitx', 'LC_MEASUREMENT': 'zh_CN.UTF-8', 'PAPERSIZE': 'a4', 'SNAP_DATA': '/var/snap/pycharm-community/327', 'CONDA_PYTHON_EXE': '/home/uvtec/miniconda3/bin/python', 'LD_LIBRARY_PATH': '/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/cv2/../../lib64:/usr/local/cuda-11.7/lib64:', 'XDG_RUNTIME_DIR': '/run/user/1000', 'CONDA_DEFAULT_ENV': 'paddle_gpu', 'LC_TIME': 'zh_CN.UTF-8', 'SNAP_NAME': 'pycharm-community', 'JOURNAL_STREAM': '8:30614', 'XDG_DATA_DIRS': '/usr/share/ubuntu:/usr/share/gnome:/usr/local/share/:/usr/share/:/var/lib/snapd/desktop', 'PATH': '/usr/local/cuda-11.7/bin:/home/uvtec/miniconda3/envs/paddle_gpu/bin:/home/uvtec/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin', 'GDMSESSION': 'ubuntu', 'DBUS_SESSION_BUS_ADDRESS': 'unix:path=/run/user/1000/bus', 'CONDA_PREFIX_1': '/home/uvtec/miniconda3', 'GIO_LAUNCHED_DESKTOP_FILE_PID': '48184', 'GIO_LAUNCHED_DESKTOP_FILE': '/var/lib/snapd/desktop/applications/pycharm-community_pycharm-community.desktop', 'LC_NUMERIC': 'zh_CN.UTF-8', '_': '/home/uvtec/miniconda3/envs/paddle_gpu/bin/python', 'CUSTOM_DEVICE_ROOT': '', 'OMP_NUM_THREADS': '1', 'QT_QPA_PLATFORM_PLUGIN_PATH': '/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/cv2/qt/plugins', 'QT_QPA_FONTDIR': '/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/cv2/qt/fonts', 'POD_NAME': 'ghenbx', 'PADDLE_MASTER': '127.0.1.1:52132', 'PADDLE_GLOBAL_SIZE': '2', 'PADDLE_LOCAL_SIZE': '2', 'PADDLE_GLOBAL_RANK': '1', 'PADDLE_LOCAL_RANK': '1', 'PADDLE_NNODES': '1', 'PADDLE_TRAINER_ENDPOINTS': '127.0.1.1:52133,127.0.1.1:52134', 'PADDLE_CURRENT_ENDPOINT': '127.0.1.1:52134', 'PADDLE_TRAINER_ID': '1', 'PADDLE_TRAINERS_NUM': '2', 'PADDLE_RANK_IN_NODE': '1', 'FLAGS_selected_gpus': '1'}
LAUNCH INFO 2023-04-12 10:37:29,228 ------------------------- ERROR LOG DETAIL -------------------------
.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
W0412 10:37:28.252017 77019 gpu_resources.cc:61] Please NOTE: device: 1, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.7
W0412 10:37:28.252559 77019 gpu_resources.cc:91] device: 1, cuDNN Version: 8.8.
Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    engine = Engine(config, mode="train")
  File "/home/uvtec/桌面/PaddleClas/ppcls/engine/engine.py", line 192, in __init__
    self.model = build_model(self.config, self.mode)
  File "/home/uvtec/桌面/PaddleClas/ppcls/arch/__init__.py", line 40, in build_model
    arch = getattr(mod, model_type)(**arch_config)
  File "/home/uvtec/桌面/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 554, in ResNet101_vd
    model = ResNet(
  File "/home/uvtec/桌面/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 331, in __init__
    self.stem = nn.Sequential(* [
  File "/home/uvtec/桌面/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 332, in <listcomp>
    ConvBNLayer(
  File "/home/uvtec/桌面/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 127, in __init__
    self.conv = Conv2D(
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 687, in __init__
    super(Conv2D, self).__init__(
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/nn/layer/conv.py", line 157, in __init__
    self.weight = self.create_parameter(
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/dygraph/layers.py", line 471, in create_parameter
    return self._helper.create_parameter(
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    return self.main_program.global_block().create_parameter(
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/framework.py", line 3988, in create_parameter
    initializer(param, self)
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 56, in __call__
    return self.forward(param, block)
  File "/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/initializer.py", line 382, in forward
    out_var = _C_ops.gaussian_random(var.shape, self._mean,
OSError: (External) CUDA error(2), out of memory. 
  [Hint: Please search for the error code(2) on website (https://docs.nvidia.com/cuda/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038) to get Nvidia's official solution and advice about CUDA Error.] (at /paddle/paddle/phi/core/cuda_stream.h:73)

LAUNCH INFO 2023-04-12 10:37:29,429 Exit code -15

**Comment by happybear1015** [comment]
finished by reboot computer!

**Comment by happybear1015** [comment]
(paddle_gpu) uvtec@uvtec-MS-7B98:~/桌面/PaddleClas$ python
Python 3.8.16 | packaged by conda-forge | (default, Feb  1 2023, 16:01:55) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
>>> paddle.utils.run_check()
Running verify PaddlePaddle program ... 
W0412 12:55:42.979866  6987 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 12.0, Runtime API Version: 11.7
this below must be wright!


W0412 12:55:43.052433  6987 gpu_resources.cc:91] device: 0, cuDNN Version: 8.8.
PaddlePaddle works well on 1 GPU.
/home/uvtec/miniconda3/envs/paddle_gpu/lib/python3.8/site-packages/paddle/fluid/executor.py:1583: UserWarning: Standalone executor is not used for data parallel
  warnings.warn(
W0412 12:56:03.507772  6987 parallel_executor.cc:666] Cannot enable P2P access from 0 to 1
W0412 12:56:03.507802  6987 parallel_executor.cc:666] Cannot enable P2P access from 1 to 0
W0412 12:56:05.044852  6987 fuse_all_reduce_op_pass.cc:79] Find all_reduce operators: 2. To make the speed faster, some all_reduce ops are fused during training, after fusion, the number of all_reduce ops is 2.
PaddlePaddle works well on 2 GPUs.
PaddlePaddle is installed successfully! Let's start deep learning with PaddlePaddle now.
>>>
