### ISSUE TITLE
IndexError: index 1262 is out of bounds for axis 0 with size 2

### ISSUE THREAD

**Issue by Bradly-s** [PaddlePaddle/PaddleClas#2773]
**1. PaddleClas develop以及paddle 2.3.2版本**
 train with paddle 2.3.2 and device Place(gpu:0)
[2023/04/28 14:30:15] ppcls WARNING: Unable to calculate accuracy when using "batch_transform_ops". The metric "{'TopkAcc': {'topk': [1, 1]}}" has been removed.
W0428 14:30:15.277129 929007 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.1
W0428 14:30:15.279021 929007 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
[2023/04/28 14:30:15] ppcls WARNING: The training strategy provided by PaddleClas is based on 4 gpus. But the number of gpu is 1 in current training. Please modify the stategy (learning rate, batch size and so on) if use this config to train.

 **2. 训练环境信息：**
  
a. Linux
  b. Python3.7.0
  c. CUDA/cuDNN版本， 如CUDA11.1/cuDNN8.7等

3. 详细的错误信息及相关log
(paddle2) dp504@504:/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas$ python3 tools/train.py -c ppcls/configs/practical_models/PPHGNet_tiny_calling_halfbody.yaml
/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
  warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('mpl_toolkits')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('google')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/pkg_resources/__init__.py:2870: DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('zope')`.
Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
  declare_namespace(pkg)
[2023/04/28 14:30:15] ppcls INFO: 
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================
[2023/04/28 14:30:15] ppcls INFO: Arch : 
[2023/04/28 14:30:15] ppcls INFO:     class_num : 2
[2023/04/28 14:30:15] ppcls INFO:     name : PPHGNet_tiny
[2023/04/28 14:30:15] ppcls INFO: DataLoader : 
[2023/04/28 14:30:15] ppcls INFO:     Eval : 
[2023/04/28 14:30:15] ppcls INFO:         dataset : 
[2023/04/28 14:30:15] ppcls INFO:             cls_label_path : /media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/dataset/phone_call/val_list.txt
[2023/04/28 14:30:15] ppcls INFO:             image_root : /media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/dataset/phone_call/
[2023/04/28 14:30:15] ppcls INFO:             name : ImageNetDataset
[2023/04/28 14:30:15] ppcls INFO:             transform_ops : 
[2023/04/28 14:30:15] ppcls INFO:                 DecodeImage : 
[2023/04/28 14:30:15] ppcls INFO:                     channel_first : False
[2023/04/28 14:30:15] ppcls INFO:                     to_rgb : True
[2023/04/28 14:30:15] ppcls INFO:                 ResizeImage : 
[2023/04/28 14:30:15] ppcls INFO:                     backend : pil
[2023/04/28 14:30:15] ppcls INFO:                     interpolation : bicubic
[2023/04/28 14:30:15] ppcls INFO:                     size : 224
[2023/04/28 14:30:15] ppcls INFO:                 NormalizeImage : 
[2023/04/28 14:30:15] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/04/28 14:30:15] ppcls INFO:                     order : 
[2023/04/28 14:30:15] ppcls INFO:                     scale : 1.0/255.0
[2023/04/28 14:30:15] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/04/28 14:30:15] ppcls INFO:         loader : 
[2023/04/28 14:30:15] ppcls INFO:             num_workers : 1
[2023/04/28 14:30:15] ppcls INFO:             use_shared_memory : True
[2023/04/28 14:30:15] ppcls INFO:         sampler : 
[2023/04/28 14:30:15] ppcls INFO:             batch_size : 2
[2023/04/28 14:30:15] ppcls INFO:             drop_last : False
[2023/04/28 14:30:15] ppcls INFO:             name : DistributedBatchSampler
[2023/04/28 14:30:15] ppcls INFO:             shuffle : False
[2023/04/28 14:30:15] ppcls INFO:     Train : 
[2023/04/28 14:30:15] ppcls INFO:         dataset : 
[2023/04/28 14:30:15] ppcls INFO:             batch_transform_ops : 
[2023/04/28 14:30:15] ppcls INFO:                 OpSampler : 
[2023/04/28 14:30:15] ppcls INFO:                     CutmixOperator : 
[2023/04/28 14:30:15] ppcls INFO:                         alpha : 1.0
[2023/04/28 14:30:15] ppcls INFO:                         prob : 0.5
[2023/04/28 14:30:15] ppcls INFO:                     MixupOperator : 
[2023/04/28 14:30:15] ppcls INFO:                         alpha : 0.2
[2023/04/28 14:30:15] ppcls INFO:                         prob : 0.5
[2023/04/28 14:30:15] ppcls INFO:             cls_label_path : /media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/dataset/phone_call/train_list.txt
[2023/04/28 14:30:15] ppcls INFO:             image_root : /media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/dataset/phone_call/
[2023/04/28 14:30:15] ppcls INFO:             name : ImageNetDataset
[2023/04/28 14:30:15] ppcls INFO:             transform_ops : 
[2023/04/28 14:30:15] ppcls INFO:                 DecodeImage : 
[2023/04/28 14:30:15] ppcls INFO:                     channel_first : False
[2023/04/28 14:30:15] ppcls INFO:                     to_rgb : True
[2023/04/28 14:30:15] ppcls INFO:                 ResizeImage : 
[2023/04/28 14:30:15] ppcls INFO:                     size : 224
[2023/04/28 14:30:15] ppcls INFO:                 RandFlipImage : 
[2023/04/28 14:30:15] ppcls INFO:                     flip_code : 1
[2023/04/28 14:30:15] ppcls INFO:                 TimmAutoAugment : 
[2023/04/28 14:30:15] ppcls INFO:                     config_str : rand-m7-mstd0.5-inc1
[2023/04/28 14:30:15] ppcls INFO:                     img_size : 224
[2023/04/28 14:30:15] ppcls INFO:                     interpolation : bicubic
[2023/04/28 14:30:15] ppcls INFO:                 NormalizeImage : 
[2023/04/28 14:30:15] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/04/28 14:30:15] ppcls INFO:                     order : 
[2023/04/28 14:30:15] ppcls INFO:                     scale : 1.0/255.0
[2023/04/28 14:30:15] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/04/28 14:30:15] ppcls INFO:                 RandomErasing : 
[2023/04/28 14:30:15] ppcls INFO:                     EPSILON : 0.25
[2023/04/28 14:30:15] ppcls INFO: ------------------------------------------------------------
[2023/04/28 14:30:15] ppcls INFO:                     attempt : 10
[2023/04/28 14:30:15] ppcls INFO:                     mode : pixel
[2023/04/28 14:30:15] ppcls INFO:                     r1 : 0.3
[2023/04/28 14:30:15] ppcls INFO:                     sh : 1.0/3.0
[2023/04/28 14:30:15] ppcls INFO:                     sl : 0.02
[2023/04/28 14:30:15] ppcls INFO:                     use_log_aspect : True
[2023/04/28 14:30:15] ppcls INFO:         loader : 
[2023/04/28 14:30:15] ppcls INFO:             num_workers : 1
[2023/04/28 14:30:15] ppcls INFO:             use_shared_memory : True
[2023/04/28 14:30:15] ppcls INFO:         sampler : 
[2023/04/28 14:30:15] ppcls INFO:             batch_size : 2
[2023/04/28 14:30:15] ppcls INFO:             drop_last : False
[2023/04/28 14:30:15] ppcls INFO:             name : DistributedBatchSampler
[2023/04/28 14:30:15] ppcls INFO:             shuffle : True
[2023/04/28 14:30:15] ppcls INFO: Global : 
[2023/04/28 14:30:15] ppcls INFO:     checkpoints : None
[2023/04/28 14:30:15] ppcls INFO:     device : gpu
[2023/04/28 14:30:15] ppcls INFO:     epochs : 50
[2023/04/28 14:30:15] ppcls INFO:     eval_during_train : True
[2023/04/28 14:30:15] ppcls INFO:     eval_interval : 1
[2023/04/28 14:30:15] ppcls INFO:     image_shape : [3, 224, 224]
[2023/04/28 14:30:15] ppcls INFO:     output_dir : ./output/
[2023/04/28 14:30:15] ppcls INFO:     pretrained_model : None
[2023/04/28 14:30:15] ppcls INFO:     print_batch_step : 10
[2023/04/28 14:30:15] ppcls INFO:     save_inference_dir : ./inference
[2023/04/28 14:30:15] ppcls INFO:     save_interval : 1
[2023/04/28 14:30:15] ppcls INFO:     to_static : False
[2023/04/28 14:30:15] ppcls INFO:     use_dali : False
[2023/04/28 14:30:15] ppcls INFO:     use_visualdl : False
[2023/04/28 14:30:15] ppcls INFO: Infer : 
[2023/04/28 14:30:15] ppcls INFO:     PostProcess : 
[2023/04/28 14:30:15] ppcls INFO:         class_id_map_file : /media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/dataset/phone_call/labels.txt
[2023/04/28 14:30:15] ppcls INFO:         name : Topk
[2023/04/28 14:30:15] ppcls INFO:         topk : 2
[2023/04/28 14:30:15] ppcls INFO:     batch_size : 1
[2023/04/28 14:30:15] ppcls INFO:     infer_imgs : docs/images/inference_deployment/whl_demo.jpg
[2023/04/28 14:30:15] ppcls INFO:     transforms : 
[2023/04/28 14:30:15] ppcls INFO:         DecodeImage : 
[2023/04/28 14:30:15] ppcls INFO:             channel_first : False
[2023/04/28 14:30:15] ppcls INFO:             to_rgb : True
[2023/04/28 14:30:15] ppcls INFO:         ResizeImage : 
[2023/04/28 14:30:15] ppcls INFO:             size : 224
[2023/04/28 14:30:15] ppcls INFO:         NormalizeImage : 
[2023/04/28 14:30:15] ppcls INFO:             mean : [0.485, 0.456, 0.406]
[2023/04/28 14:30:15] ppcls INFO:             order : 
[2023/04/28 14:30:15] ppcls INFO:             scale : 1.0/255.0
[2023/04/28 14:30:15] ppcls INFO:             std : [0.229, 0.224, 0.225]
[2023/04/28 14:30:15] ppcls INFO:         ToCHWImage : None
[2023/04/28 14:30:15] ppcls INFO: Loss : 
[2023/04/28 14:30:15] ppcls INFO:     Eval : 
[2023/04/28 14:30:15] ppcls INFO:         CELoss : 
[2023/04/28 14:30:15] ppcls INFO:             weight : 1.0
[2023/04/28 14:30:15] ppcls INFO:     Train : 
[2023/04/28 14:30:15] ppcls INFO:         CELoss : 
[2023/04/28 14:30:15] ppcls INFO:             epsilon : 0.1
[2023/04/28 14:30:15] ppcls INFO:             weight : 1.0
[2023/04/28 14:30:15] ppcls INFO: Metric : 
[2023/04/28 14:30:15] ppcls INFO:     Eval : 
[2023/04/28 14:30:15] ppcls INFO:         TopkAcc : 
[2023/04/28 14:30:15] ppcls INFO:             topk : [1, 1]
[2023/04/28 14:30:15] ppcls INFO:     Train : 
[2023/04/28 14:30:15] ppcls INFO:         TopkAcc : 
[2023/04/28 14:30:15] ppcls INFO:             topk : [1, 1]
[2023/04/28 14:30:15] ppcls INFO: Optimizer : 
[2023/04/28 14:30:15] ppcls INFO:     lr : 
[2023/04/28 14:30:15] ppcls INFO:         learning_rate : 0.0125
[2023/04/28 14:30:15] ppcls INFO:         name : Cosine
[2023/04/28 14:30:15] ppcls INFO:         warmup_epoch : 3
[2023/04/28 14:30:15] ppcls INFO:     momentum : 0.9
[2023/04/28 14:30:15] ppcls INFO:     name : Momentum
[2023/04/28 14:30:15] ppcls INFO:     regularizer : 
[2023/04/28 14:30:15] ppcls INFO:         coeff : 4e-05
[2023/04/28 14:30:15] ppcls INFO:         name : L2
[2023/04/28 14:30:15] ppcls INFO: profiler_options : None
[2023/04/28 14:30:15] ppcls INFO: train with paddle 2.3.2 and device Place(gpu:0)
[2023/04/28 14:30:15] ppcls WARNING: Unable to calculate accuracy when using "batch_transform_ops". The metric "{'TopkAcc': {'topk': [1, 1]}}" has been removed.
W0428 14:30:15.277129 929007 gpu_resources.cc:61] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.0, Runtime API Version: 11.1
W0428 14:30:15.279021 929007 gpu_resources.cc:91] device: 0, cuDNN Version: 8.7.
[2023/04/28 14:30:15] ppcls WARNING: The training strategy provided by PaddleClas is based on 4 gpus. But the number of gpu is 1 in current training. Please modify the stategy (learning rate, batch size and so on) if use this config to train.
---------------------------------------------------------------------------------labels[idx]: [  62 1262]
------------------------------------------self.class_num2
targets: [1262   62]
Traceback (most recent call last):
  File "tools/train.py", line 34, in <module>
    engine.train()
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/engine/engine.py", line 356, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/engine/train/train.py", line 24, in train_epoch
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 534, in _thread_loop
    batch = self._get_data()
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 671, in _get_data
    batch.reraise()
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 169, in reraise
    raise self.exc_type(msg)
IndexError: DataLoader worker(0) caught IndexError with message:
Traceback (most recent call last):
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/worker.py", line 336, in _worker_loop
    batch = fetcher.fetch(indices)
  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 134, in fetch
    data = self.collate_fn(data)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/data/__init__.py", line 110, in mix_collate_fn
    batch = transform(batch, batch_ops)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/data/preprocess/__init__.py", line 55, in transform
    data = op(data)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/data/preprocess/batch_ops/batch_operators.py", line 238, in __call__
    return op(batch) if op else batch
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/data/preprocess/batch_ops/batch_operators.py", line 157, in __call__
    targets = self._mix_target(labels, labels[idx], lam)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/data/preprocess/batch_ops/batch_operators.py", line 57, in _mix_target
    one_hots0 = self._one_hot(targets0)
  File "/media/dp504/36675aac-be99-45b0-abf0-9c74c037c1b7/PycharmProjects/swf/PaddleClas/ppcls/data/preprocess/batch_ops/batch_operators.py", line 53, in _one_hot
    return np.eye(self.class_num, dtype="float32")[targets]
IndexError: index 1262 is out of bounds for axis 0 with size 2

    for iter_id, batch in enumerate(engine.train_dataloader):

  File "/home/dp504/miniconda3/envs/paddle2/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 746, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

**Comment by zengshao0622** [comment]
建议检查一下类别数设置

**Comment by Bradly-s** [comment]
没问题呀，都是两类别呀
![image](https://user-images.githubusercontent.com/49717982/236212628-355ffca4-14f4-44fc-a238-75dd8d12c104.png)
![image](https://user-images.githubusercontent.com/49717982/236212798-e95254c3-e9cd-4bf8-ba56-209a377bc185.png)

**Comment by Bradly-s** [comment]
我大概知道了，是数据集格式的问题。我的是：
![image](https://user-images.githubusercontent.com/49717982/236219844-091f7112-fece-4675-8b43-8bb4ec07cc8f.png)


顺便请问有打电话的公开数据集吗？

**Comment by zengshao0622** [comment]
这种具体应用场景比较少大型的公开数据集，建议到一些比赛或者开源项目里找找

**Comment by Bradly-s** [comment]
好的，谢谢
