### ISSUE TITLE
ModuleNotFoundError: No module named 'PaddleClas'

### ISSUE THREAD

**Issue by Junxiang-Zeng8443** [PaddlePaddle/PaddleClas#2978]
### import paddleclas出现报错，如下

**from .ppcls.arch import backbone ImportError: attempted relative import with no known parent package**

然后将paddleclas.py文件改为绝对引用，如下：
..........
import sys
sys.path.append('D:/PaddleClass')

import cv2
import numpy as np
from tqdm import tqdm
from prettytable import PrettyTable
import paddle

from PaddleClas.ppcls.arch import backbone
from PaddleClas.ppcls.utils import logger

from PaddleClas.deploy.python.predict_cls import ClsPredictor
from PaddleClas.deploy.utils.get_image_list import get_image_list
from PaddleClas.deploy.utils import config
...........

再次 import paddleclas，再次报错：
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddleclas-0.0.0-py3.9.egg\paddleclas\__init__.py", line 16, in <module>
    from .paddleclas import PaddleClas
  File "C:\ProgramData\Anaconda3\envs\paddle_env\lib\site-packages\paddleclas-0.0.0-py3.9.egg\paddleclas\paddleclas.py", line 35, in <module>
    from PaddleClas.ppcls.arch import backbone
ModuleNotFoundError: No module named 'PaddleClas'

请问如何解决？

**Comment by cuicheng01** [comment]
1.这里拼写不对`sys.path.append('D:/PaddleClass')`；
2.如果import，需要准备`__init__.py`

**Comment by MathewsJosh** [comment]
**Problem:**
I am encountering the same issue while attempting to run the [2.2 Use by Python script](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.7/ppstructure/docs/quickstart_en.md#:~:text=2.2.1-,image%20orientation%20%2B%20layout%20analysis%20%2B%20table%20recognition%20-%20import%20os%0Aimport) on Windows.

**Environment:**
- `paddleocr`: 2.7.0.3
- `paddlepaddle`: 2.5.2
- `paddlepaddle-gpu`: 2.5.2

**Additional Information:**
I'm also encountering an issue while attempting to install `paddleclas`. The error message received is:

```
pip3 install paddleclas>=2.4.3
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting paddleclas>=2.4.3
  Downloading paddleclas-2.5.1-py3-none-any.whl (342 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 342.1/342.1 kB 7.1 MB/s eta 0:00:00
Requirement already satisfied: ujson in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (5.4.0)
Collecting prettytable
  Downloading prettytable-3.9.0-py3-none-any.whl (27 kB)
Requirement already satisfied: tqdm in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (4.65.0)
Requirement already satisfied: scikit-learn>=0.21.0 in c:\users\teued\appdata\roaming\python\python310\site-packages (from paddleclas>=2.4.3) (1.2.2)
Collecting easydict
  Downloading easydict-1.11.tar.gz (6.6 kB)
  Preparing metadata (setup.py) ... done
Collecting gast==0.3.3
  Downloading gast-0.3.3-py2.py3-none-any.whl (9.7 kB)
Requirement already satisfied: pillow in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (10.1.0)
Requirement already satisfied: visualdl>=2.2.0 in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (2.5.3)
Collecting faiss-cpu==1.7.1.post2
  Downloading faiss-cpu-1.7.1.post2.tar.gz (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB ? eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: PyYAML>=5.1 in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (5.3.1)
Requirement already satisfied: opencv-python in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (4.6.0.66)
Requirement already satisfied: scipy>=1.0.0 in f:\programdata\anaconda3\lib\site-packages (from paddleclas>=2.4.3) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\teued\appdata\roaming\python\python310\site-packages (from scikit-learn>=0.21.0->paddleclas>=2.4.3) (1.2.0)
Requirement already satisfied: numpy>=1.17.3 in f:\programdata\anaconda3\lib\site-packages (from scikit-learn>=0.21.0->paddleclas>=2.4.3) (1.23.5)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\teued\appdata\roaming\python\python310\site-packages (from scikit-learn>=0.21.0->paddleclas>=2.4.3) (3.1.0)      
Requirement already satisfied: protobuf>=3.20.0 in c:\users\teued\appdata\roaming\python\python310\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (3.20.0)
Requirement already satisfied: six>=1.14.0 in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (1.16.0)
Requirement already satisfied: pandas in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (2.0.1)
Requirement already satisfied: requests in c:\users\teued\appdata\roaming\python\python310\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (2.31.0)
Requirement already satisfied: matplotlib in f:\programdata\anaconda3\lib\site-packages\matplotlib-3.7.1-py3.10-win-amd64.egg (from visualdl>=2.2.0->paddleclas>=2.4.3) (3.7.1)  
Requirement already satisfied: packaging in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (23.0)
Requirement already satisfied: psutil in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (5.9.0)
Requirement already satisfied: bce-python-sdk in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (0.8.83)
Requirement already satisfied: flask>=1.1.1 in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (2.3.2)
Requirement already satisfied: rarfile in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (4.0)
Requirement already satisfied: Flask-Babel>=3.0.0 in f:\programdata\anaconda3\lib\site-packages (from visualdl>=2.2.0->paddleclas>=2.4.3) (3.1.0)
Requirement already satisfied: wcwidth in f:\programdata\anaconda3\lib\site-packages (from prettytable->paddleclas>=2.4.3) (0.2.5)
Requirement already satisfied: colorama in f:\programdata\anaconda3\lib\site-packages (from tqdm->paddleclas>=2.4.3) (0.4.3)
Requirement already satisfied: Jinja2>=3.1.2 in f:\programdata\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl>=2.2.0->paddleclas>=2.4.3) (3.1.2)
Requirement already satisfied: click>=8.1.3 in f:\programdata\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl>=2.2.0->paddleclas>=2.4.3) (8.1.3)
Requirement already satisfied: itsdangerous>=2.1.2 in f:\programdata\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl>=2.2.0->paddleclas>=2.4.3) (2.1.2)
Requirement already satisfied: blinker>=1.6.2 in f:\programdata\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl>=2.2.0->paddleclas>=2.4.3) (1.6.2)
Requirement already satisfied: Werkzeug>=2.3.3 in f:\programdata\anaconda3\lib\site-packages (from flask>=1.1.1->visualdl>=2.2.0->paddleclas>=2.4.3) (2.3.4)
Requirement already satisfied: pytz>=2022.7 in c:\users\teued\appdata\roaming\python\python310\site-packages (from Flask-Babel>=3.0.0->visualdl>=2.2.0->paddleclas>=2.4.3) (2023.3.post1)
Requirement already satisfied: Babel>=2.12 in f:\programdata\anaconda3\lib\site-packages (from Flask-Babel>=3.0.0->visualdl>=2.2.0->paddleclas>=2.4.3) (2.12.1)
Requirement already satisfied: future>=0.6.0 in f:\programdata\anaconda3\lib\site-packages (from bce-python-sdk->visualdl>=2.2.0->paddleclas>=2.4.3) (0.18.3)
Requirement already satisfied: pycryptodome>=3.8.0 in f:\programdata\anaconda3\lib\site-packages (from bce-python-sdk->visualdl>=2.2.0->paddleclas>=2.4.3) (3.18.0)
Requirement already satisfied: contourpy>=1.0.1 in f:\programdata\anaconda3\lib\site-packages (from matplotlib->visualdl>=2.2.0->paddleclas>=2.4.3) (1.0.7)
Requirement already satisfied: cycler>=0.10 in f:\programdata\anaconda3\lib\site-packages (from matplotlib->visualdl>=2.2.0->paddleclas>=2.4.3) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in f:\programdata\anaconda3\lib\site-packages (from matplotlib->visualdl>=2.2.0->paddleclas>=2.4.3) (4.39.3)
Requirement already satisfied: kiwisolver>=1.0.1 in f:\programdata\anaconda3\lib\site-packages (from matplotlib->visualdl>=2.2.0->paddleclas>=2.4.3) (1.4.4)
Requirement already satisfied: pyparsing>=2.3.1 in f:\programdata\anaconda3\lib\site-packages (from matplotlib->visualdl>=2.2.0->paddleclas>=2.4.3) (3.0.9)
Requirement already satisfied: python-dateutil>=2.7 in f:\programdata\anaconda3\lib\site-packages (from matplotlib->visualdl>=2.2.0->paddleclas>=2.4.3) (2.8.2)
Requirement already satisfied: tzdata>=2022.1 in f:\programdata\anaconda3\lib\site-packages (from pandas->visualdl>=2.2.0->paddleclas>=2.4.3) (2023.3)
Requirement already satisfied: idna<4,>=2.5 in f:\programdata\anaconda3\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas>=2.4.3) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in f:\programdata\anaconda3\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas>=2.4.3) (1.26.15)
Requirement already satisfied: charset-normalizer<4,>=2 in f:\programdata\anaconda3\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas>=2.4.3) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in f:\programdata\anaconda3\lib\site-packages (from requests->visualdl>=2.2.0->paddleclas>=2.4.3) (2022.12.7)
Requirement already satisfied: MarkupSafe>=2.0 in f:\programdata\anaconda3\lib\site-packages (from Jinja2>=3.1.2->flask>=1.1.1->visualdl>=2.2.0->paddleclas>=2.4.3) (2.1.1)
Building wheels for collected packages: faiss-cpu, easydict
  Building wheel for faiss-cpu (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      running bdist_wheel
      running build
      running build_py
      running build_ext
      building 'faiss._swigfaiss' extension
      swigging faiss\faiss\python\swigfaiss.i to faiss\faiss\python\swigfaiss_wrap.cpp
      swig.exe -python -c++ -Doverride= -I/usr/local/include -Ifaiss -DSWIGWIN -o faiss\faiss\python\swigfaiss_wrap.cpp faiss\faiss\python\swigfaiss.i
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for faiss-cpu
  Running setup.py clean for faiss-cpu
  Building wheel for easydict (setup.py) ... done
  Created wheel for easydict: filename=easydict-1.11-py3-none-any.whl size=6691 sha256=1f11eda989df8a6490462e38e8b63a3a0ee3a3fd7d361f1c8c89142a964826ad
  Stored in directory: C:\Users\teued\AppData\Local\Temp\pip-ephem-wheel-cache-np1ee_57\wheels\9a\28\0a\d1fe3ba15ef81a7d07ac5df61779adfccf2dbae63ee332e632
Successfully built easydict
Failed to build faiss-cpu
Installing collected packages: faiss-cpu, easydict, prettytable, gast, paddleclas
  Attempting uninstall: faiss-cpu
    Found existing installation: faiss-cpu 1.7.4
    Uninstalling faiss-cpu-1.7.4:
      Successfully uninstalled faiss-cpu-1.7.4
  Running setup.py install for faiss-cpu ... error
  error: subprocess-exited-with-error

  × Running setup.py install for faiss-cpu did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      running install
      F:\ProgramData\anaconda3\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running build_py
      running build_ext
      building 'faiss._swigfaiss' extension
      swigging faiss\faiss\python\swigfaiss.i to faiss\faiss\python\swigfaiss_wrap.cpp
      swig.exe -python -c++ -Doverride= -I/usr/local/include -Ifaiss -DSWIGWIN -o faiss\faiss\python\swigfaiss_wrap.cpp faiss\faiss\python\swigfaiss.i
      error: command 'swig.exe' failed: None
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of faiss-cpu
  Moving to f:\programdata\anaconda3\lib\site-packages\faiss\
   from F:\ProgramData\anaconda3\Lib\site-packages\~aiss
  Moving to f:\programdata\anaconda3\lib\site-packages\faiss_cpu-1.7.4.dist-info\
   from F:\ProgramData\anaconda3\Lib\site-packages\~aiss_cpu-1.7.4.dist-info
  Moving to f:\programdata\anaconda3\lib\site-packages\faiss_cpu.libs\
   from F:\ProgramData\anaconda3\Lib\site-packages\~aiss_cpu.libs
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> faiss-cpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```
