### ISSUE TITLE
Running check on Ubuntu 22.04: ImportError: libssl.so.1.1

### ISSUE THREAD

**Issue by ucsky** [PaddlePaddle/PaddleClas#3015]
Trying to install and import paddlecla under `Ubuntu 22.04` with `venv` I got the following error:
```bash
( \
. .local.env \
&& . venv/cpu/bin/activate \
&& python -c "import paddle; paddle.utils.run_check()" \
)
Error: Can not import paddle core while this file exists: /mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/fluid/libpaddle.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/__init__.py", line 31, in <module>
    from .framework import monkey_patch_variable
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/framework/__init__.py", line 17, in <module>
    from . import random  # noqa: F401
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/framework/random.py", line 17, in <module>
    from paddle import fluid
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/fluid/framework.py", line 35, in <module>
    from . import core
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/fluid/core.py", line 356, in <module>
    raise e
  File "/mnt/local/data02/home2/worker/project/PaddleClas/venv/cpu/lib/python3.10/site-packages/paddle/fluid/core.py", line 269, in <module>
    from . import libpaddle
ImportError: libssl.so.1.1: cannot open shared object file: No such file or directory
make: [Makefile:33: venv-test-cpu] Error 1 (ignored)
```
Please is somebody known how to fix this?

**Comment by ucsky** [comment]
Using python3.7 with conda solved the issu.
