### ISSUE TITLE
部分import语句可能造成循环引用错误

### ISSUE THREAD

**Issue by ziishuo** [PaddlePaddle/PaddleClas#3022]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux/Windows/MacOS
  b. Python版本号，如Python3.6/7/8
  c. CUDA/cuDNN版本， 如CUDA10.2/cuDNN 7.6.5等
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

**Comment by ziishuo** [comment]
我使用anaconda创建了一个python3.9的虚拟环境，该环境放置在名为env的文件夹中。另外GitHub上下载的PaddleClas代码文件与env文件夹同级，在参考链接https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PP-ShiTu/README.md的教程后创建了paddleclas库，该库与PaddleClas文件夹下paddleclas.py文件同名，在“执行命令体验索引库构建”的时候会造成“circular import”错误，建议修改一下paddleclas.py文件名（项目经验较少，想法如有错误请多多包含）。
(D:\Programme\Projects\pp_shitu\python) D:\Programme\Projects\pp_shitu\PaddleClas>python paddleclas.py --build_gallery=True --model_name="PP-ShiTuV2" -o IndexProcess.image_root=./drink_dataset_v2.0/gallery/ -o IndexProcess.index_dir=./drink_dataset_v2.0/index -o IndexProcess.data_file=./drink_dataset_v2.0/gallery/drink_label.txt
Traceback (most recent call last):
  File "D:\Programme\Projects\pp_shitu\PaddleClas\paddleclas.py", line 44, in <module>
    from deploy.python.predict_cls import ClsPredictor
  File "D:\Programme\Projects\pp_shitu\PaddleClas\deploy\python\predict_cls.py", line 20, in <module>
    from paddleclas.deploy.utils import logger, config
  File "D:\Programme\Projects\pp_shitu\PaddleClas\paddleclas.py", line 44, in <module>
    from deploy.python.predict_cls import ClsPredictor
ImportError: cannot import name 'ClsPredictor' from partially initialized module 'deploy.python.predict_cls' (most likely due to a circular import) (D:\Programme\Projects\pp_shitu\PaddleClas\deploy\python\predict_cls.py)

**Comment by cuicheng01** [comment]
您的经验我们会考虑采纳，感谢提问

**Comment by ericosmic** [comment]
这个问题解决了吗
