### ISSUE TITLE
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

### ISSUE THREAD

**Issue by Yukimini** [PaddlePaddle/PaddleClas#3051]
我在运行代码时遇到了这个问题，我不知道应该怎么解决。
我的版本是：PaddlePaddle==2.3.2；Python=3.7.4
我尝试在代码最开始添加“paddle.disable_static()”，但是也无济于事。
fail to perform transform [<paddle.vision.transforms.transforms.Normalize object at 0x7fcd13455150>] with error: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode. and stack:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 113, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 269, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 715, in _apply_image
    self.to_rgb)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/functional.py", line 674, in normalize
    return F_t.normalize(img, mean, std, data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/functional_tensor.py", line 105, in normalize
    mean = paddle.to_tensor(mean, place=img.place)
  File "<decorator-gen-163>", line 2, in to_tensor
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 433, in __impl__
    ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 218, in _thread_loop
    self._thread_done_event)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 121, in fetch
    data.append(self.dataset[idx])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/datasets/cifar.py", line 163, in __getitem__
    image = self.transform(image)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 118, in __call__
    raise e
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 113, in __call__
    data = f(data)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 269, in __call__
    outputs.append(apply_func(inputs[i]))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/transforms.py", line 715, in _apply_image
    self.to_rgb)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/functional.py", line 674, in normalize
    return F_t.normalize(img, mean, std, data_format)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/vision/transforms/functional_tensor.py", line 105, in normalize
    mean = paddle.to_tensor(mean, place=img.place)
  File "<decorator-gen-163>", line 2, in to_tensor
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 433, in __impl__
    ), "We only support '%s()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode." % func.__name__
AssertionError: We only support 'to_tensor()' in dynamic graph mode, please call 'paddle.disable_static()' to enter dynamic graph mode.

**Comment by cuicheng01** [comment]
建议使用最新的Paddle版本呢？

**Comment by Yukimini** [comment]
这是来自李佳颖的自动回复邮件。你好，我已收到你的邮件，祝好！

**Comment by Yukimini** [comment]
您好，这个问题我貌似解决了，我建议您看一下我的其他问题https://github.com/PaddlePaddle/PaddleClas/issues/3075

**Comment by cuicheng01** [comment]
好的，另一个问题已关注。这个问题怎么解决的呢？

**Comment by Yukimini** [comment]
这是来自李佳颖的自动回复邮件。你好，我已收到你的邮件，祝好！
