### ISSUE TITLE
GeneralRecognitionV2_PPLCNetV2_base.yaml", yaml.scanner.ScannerError: mapping values are not allowed here

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#3070]
paddleclas          0.0.0
paddlepaddle-gpu    2.5.2
python 3.8
win 11

` python tools/train.py  -c E:\PaddlePaddle\PaddleClas\ppcls\configs\GeneralRecognitionV2\GeneralRecognitionV2_PPLCNetV2_base.yaml`

```python
Traceback (most recent call last):
  File "tools/train.py", line 28, in <module>
    config = config.get_config(
  File "E:\PaddlePaddle\PaddleClas\ppcls\utils\config.py", line 184, in get_config
    config = parse_config(fname)
  File "E:\PaddlePaddle\PaddleClas\ppcls\utils\config.py", line 58, in parse_config
    yaml_config = AttrDict(yaml.load(fopen, Loader=yaml.SafeLoader))
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\parser.py", line 428, in parse_block_mapping_key
    if self.check_token(KeyToken):
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\scanner.py", line 223, in fetch_more_tokens
    return self.fetch_value()
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\yaml\scanner.py", line 577, in fetch_value
    raise ScannerError(None, None,
yaml.scanner.ScannerError: mapping values are not allowed here
  in "E:\PaddlePaddle\PaddleClas\ppcls\configs\GeneralRecognitionV2\GeneralRecognitionV2_PPLCNetV2_base.yaml", line 150, column 22
```

官方数据集示例:
https://ai.baidu.com/ai-doc/AISTUDIO/Clkg7m4y9#%E7%89%B9%E5%BE%81%E6%A3%80%E7%B4%A2%E4%BB%BB%E5%8A%A1
https://paddle-model-ecology.bj.bcebos.com/paddlex/data/shitu_rec_dataset_examples.tar

```
images
train.txt
val.txt
```

```yaml
# global configs
Global:
  checkpoints: null
  pretrained_model: null
  output_dir: ./outputREC
  device: gpu
  save_interval: 1
  eval_during_train: True
  eval_interval: 1
  epochs: 100
  print_batch_step: 20
  use_visualdl: False
  eval_mode: retrieval
  retrieval_feature_from: features # 'backbone' or 'features'
  re_ranking: False
  use_dali: False
  # used for static mode and model export
  image_shape: [3, 224, 224]
  save_inference_dir: ./inference

AMP:
  scale_loss: 65536
  use_dynamic_loss_scaling: True
  # O1: mixed fp16
  level: O1

# model architecture
Arch:
  name: RecModel
  infer_output_key: features
  infer_add_softmax: False

  Backbone:
    name: PPLCNetV2_base_ShiTu
    pretrained: True
    use_ssld: True
    class_expand: &feat_dim 512
  BackboneStopLayer:
    name: flatten
  Neck:
    name: BNNeck
    num_features: *feat_dim
    weight_attr:
      initializer:
        name: Constant
        value: 1.0
    bias_attr:
      initializer:
        name: Constant
        value: 0.0
      learning_rate: 1.0e-20 # NOTE: Temporarily set lr small enough to freeze the bias to zero
  Head:
    name: FC
    embedding_size: *feat_dim
    class_num: 9
    weight_attr:
      initializer:
        name: Normal
        std: 0.001
    bias_attr: False

# loss function config for traing/eval process
Loss:
  Train:
    - CELoss:
        weight: 1.0
        epsilon: 0.1
    - TripletAngularMarginLoss:
        weight: 1.0
        feature_from: features
        margin: 0.5
        reduction: mean
        add_absolute: True
        absolute_loss_weight: 0.1
        normalize_feature: True
        ap_value: 0.8
        an_value: 0.4
  Eval:
    - CELoss:
        weight: 1.0

Optimizer:
  name: Momentum
  momentum: 0.9
  lr:
    name: Cosine
    learning_rate: 0.06 # for 8gpu x 256bs
    warmup_epoch: 5
  regularizer:
    name: L2
    coeff: 0.00001

# data loader for train and eval
DataLoader:
  Train:
    dataset:
      name: ImageNetDataset
      image_root: E:/shitu_rec_dataset_examples/
      cls_label_path: E:/shitu_rec_dataset_examples/train.txt
      relabel: True
      transform_ops:
        - DecodeImage:
            to_rgb: True
            channel_first: False
        - ResizeImage:
            size: [224, 224]
            return_numpy: False
            interpolation: bilinear
            backend: cv2
        - RandFlipImage:
            flip_code: 1
        - Pad:
            padding: 10
            backend: cv2
        - RandCropImageV2:
            size: [224, 224]
        - RandomRotation:
            prob: 0.5
            degrees: 90
            interpolation: bilinear
        - ResizeImage:
            size: [224, 224]
            return_numpy: False
            interpolation: bilinear
            backend: cv2
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: hwc
    sampler:
      name: PKSampler
      batch_size: 8
      sample_per_id: 4
      drop_last: False
      shuffle: True
      sample_method: "id_avg_prob"
      id_list: [50030, 80700, 92019, 96015] # be careful when set relabel=True
      ratio: [4, 4]
    loader:
      num_workers: 4
      use_shared_memory: True

  Eval:
    Query:
      dataset:
        name: VeriWild
      image_root: E:/shitu_rec_dataset_examples/
      cls_label_path: E:/shitu_rec_dataset_examples/val.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [224, 224]
              return_numpy: False
              interpolation: bilinear
              backend: cv2
          - NormalizeImage:
              scale: 1.0/255.0
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: hwc
      sampler:
        name: DistributedBatchSampler
        batch_size: 8
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

    Gallery:
      dataset:
        name: VeriWild
      image_root: E:/shitu_rec_dataset_examples/
      cls_label_path: E:/shitu_rec_dataset_examples/val.txt
        transform_ops:
          - DecodeImage:
              to_rgb: True
              channel_first: False
          - ResizeImage:
              size: [224, 224]
              return_numpy: False
              interpolation: bilinear
              backend: cv2
          - NormalizeImage:
              scale: 1.0/255.0
              mean: [0.485, 0.456, 0.406]
              std: [0.229, 0.224, 0.225]
              order: hwc
      sampler:
        name: DistributedBatchSampler
        batch_size: 8
        drop_last: False
        shuffle: False
      loader:
        num_workers: 4
        use_shared_memory: True

Metric:
  Eval:
    - Recallk:
        topk: [1, 5]
    - mAP: {}

```

**Comment by monkeycc** [comment]
image_root
cls_label_path
yaml格式化
