### ISSUE TITLE
RuntimeError: (NotFound) The kernel with key (GPU, Undefined(AnyLayout), int32) of kernel `label_smooth` is not registered and fail to fallback to CPU one. Selected wrong DataType `int32`.

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/PaddleClas#3071]
paddleclas          0.0.0
paddlepaddle-gpu    2.5.2
python 3.8
win 11

特征提取模型训练报错

`python tools/train.py  -c E:\PaddlePaddle\PaddleClas\ppcls\configs\GeneralRecognitionV2\GeneralRecognitionV2_PPLCNetV2_base_LL.yaml`

```python
[2023/12/21 23:40:16] ppcls INFO:
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

[2023/12/21 23:40:16] ppcls INFO: AMP :
[2023/12/21 23:40:16] ppcls INFO:     level : O1
[2023/12/21 23:40:16] ppcls INFO:     scale_loss : 65536
[2023/12/21 23:40:16] ppcls INFO:     use_dynamic_loss_scaling : True
[2023/12/21 23:40:16] ppcls INFO: ------------------------------------------------------------
[2023/12/21 23:40:16] ppcls INFO: Arch :
[2023/12/21 23:40:16] ppcls INFO:     Backbone :
[2023/12/21 23:40:16] ppcls INFO:         class_expand : 512
[2023/12/21 23:40:16] ppcls INFO:         name : PPLCNetV2_base_ShiTu
[2023/12/21 23:40:16] ppcls INFO:         pretrained : True
[2023/12/21 23:40:16] ppcls INFO:         use_ssld : True
[2023/12/21 23:40:16] ppcls INFO:     BackboneStopLayer :
[2023/12/21 23:40:16] ppcls INFO:         name : flatten
[2023/12/21 23:40:16] ppcls INFO:     Head :
[2023/12/21 23:40:16] ppcls INFO:         bias_attr : False
[2023/12/21 23:40:16] ppcls INFO:         class_num : 1
[2023/12/21 23:40:16] ppcls INFO:         embedding_size : 512
[2023/12/21 23:40:16] ppcls INFO:         name : FC
[2023/12/21 23:40:16] ppcls INFO:         weight_attr :
[2023/12/21 23:40:16] ppcls INFO:             initializer :
[2023/12/21 23:40:16] ppcls INFO:                 name : Normal
[2023/12/21 23:40:16] ppcls INFO:                 std : 0.001
[2023/12/21 23:40:16] ppcls INFO:     Neck :
[2023/12/21 23:40:16] ppcls INFO:         bias_attr :
[2023/12/21 23:40:16] ppcls INFO:             initializer :
[2023/12/21 23:40:16] ppcls INFO:                 name : Constant
[2023/12/21 23:40:16] ppcls INFO:                 value : 0.0
[2023/12/21 23:40:16] ppcls INFO:             learning_rate : 1e-20
[2023/12/21 23:40:16] ppcls INFO:         name : BNNeck
[2023/12/21 23:40:16] ppcls INFO:         num_features : 512
[2023/12/21 23:40:16] ppcls INFO:         weight_attr :
[2023/12/21 23:40:16] ppcls INFO:             initializer :
[2023/12/21 23:40:16] ppcls INFO:                 name : Constant
[2023/12/21 23:40:16] ppcls INFO:                 value : 1.0
[2023/12/21 23:40:16] ppcls INFO:     infer_add_softmax : False
[2023/12/21 23:40:16] ppcls INFO:     infer_output_key : features
[2023/12/21 23:40:16] ppcls INFO:     name : RecModel
[2023/12/21 23:40:16] ppcls INFO: DataLoader :
[2023/12/21 23:40:16] ppcls INFO:     Eval :
[2023/12/21 23:40:16] ppcls INFO:         Gallery :
[2023/12/21 23:40:16] ppcls INFO:             dataset :
[2023/12/21 23:40:16] ppcls INFO:                 cls_label_path : E:/LL_REC/test.txt
[2023/12/21 23:40:16] ppcls INFO:                 image_root : E:/LL_REC/
[2023/12/21 23:40:16] ppcls INFO:                 name : VeriWild
[2023/12/21 23:40:16] ppcls INFO:                 transform_ops :
[2023/12/21 23:40:16] ppcls INFO:                     DecodeImage :
[2023/12/21 23:40:16] ppcls INFO:                         channel_first : False
[2023/12/21 23:40:16] ppcls INFO:                         to_rgb : True
[2023/12/21 23:40:16] ppcls INFO:                     ResizeImage :
[2023/12/21 23:40:16] ppcls INFO:                         backend : cv2
[2023/12/21 23:40:16] ppcls INFO:                         interpolation : bilinear
[2023/12/21 23:40:16] ppcls INFO:                         return_numpy : False
[2023/12/21 23:40:16] ppcls INFO:                         size : [224, 224]
[2023/12/21 23:40:16] ppcls INFO:                     NormalizeImage :
[2023/12/21 23:40:16] ppcls INFO:                         mean : [0.485, 0.456, 0.406]
[2023/12/21 23:40:16] ppcls INFO:                         order : hwc
[2023/12/21 23:40:16] ppcls INFO:                         scale : 1.0/255.0
[2023/12/21 23:40:16] ppcls INFO:                         std : [0.229, 0.224, 0.225]
[2023/12/21 23:40:16] ppcls INFO:             loader :
[2023/12/21 23:40:16] ppcls INFO:                 num_workers : 4
[2023/12/21 23:40:16] ppcls INFO:                 use_shared_memory : True
[2023/12/21 23:40:16] ppcls INFO:             sampler :
[2023/12/21 23:40:16] ppcls INFO:                 batch_size : 2
[2023/12/21 23:40:16] ppcls INFO:                 drop_last : False
[2023/12/21 23:40:16] ppcls INFO:                 name : DistributedBatchSampler
[2023/12/21 23:40:16] ppcls INFO:                 shuffle : False
[2023/12/21 23:40:16] ppcls INFO:         Query :
[2023/12/21 23:40:16] ppcls INFO:             dataset :
[2023/12/21 23:40:16] ppcls INFO:                 cls_label_path : E:/LL_REC/val.txt
[2023/12/21 23:40:16] ppcls INFO:                 image_root : E:/LL_REC/
[2023/12/21 23:40:16] ppcls INFO:                 name : VeriWild
[2023/12/21 23:40:16] ppcls INFO:                 transform_ops :
[2023/12/21 23:40:16] ppcls INFO:                     DecodeImage :
[2023/12/21 23:40:16] ppcls INFO:                         channel_first : False
[2023/12/21 23:40:16] ppcls INFO:                         to_rgb : True
[2023/12/21 23:40:16] ppcls INFO:                     ResizeImage :
[2023/12/21 23:40:16] ppcls INFO:                         backend : cv2
[2023/12/21 23:40:16] ppcls INFO:                         interpolation : bilinear
[2023/12/21 23:40:16] ppcls INFO:                         return_numpy : False
[2023/12/21 23:40:16] ppcls INFO:                         size : [224, 224]
[2023/12/21 23:40:16] ppcls INFO:                     NormalizeImage :
[2023/12/21 23:40:16] ppcls INFO:                         mean : [0.485, 0.456, 0.406]
[2023/12/21 23:40:16] ppcls INFO:                         order : hwc
[2023/12/21 23:40:16] ppcls INFO:                         scale : 1.0/255.0
[2023/12/21 23:40:16] ppcls INFO:                         std : [0.229, 0.224, 0.225]
[2023/12/21 23:40:16] ppcls INFO:             loader :
[2023/12/21 23:40:16] ppcls INFO:                 num_workers : 4
[2023/12/21 23:40:16] ppcls INFO:                 use_shared_memory : True
[2023/12/21 23:40:16] ppcls INFO:             sampler :
[2023/12/21 23:40:16] ppcls INFO:                 batch_size : 2
[2023/12/21 23:40:16] ppcls INFO:                 drop_last : False
[2023/12/21 23:40:16] ppcls INFO:                 name : DistributedBatchSampler
[2023/12/21 23:40:16] ppcls INFO:                 shuffle : False
[2023/12/21 23:40:16] ppcls INFO:     Train :
[2023/12/21 23:40:16] ppcls INFO:         dataset :
[2023/12/21 23:40:16] ppcls INFO:             cls_label_path : E:/LL_REC/train.txt
[2023/12/21 23:40:16] ppcls INFO:             image_root : E:/LL_REC/
[2023/12/21 23:40:16] ppcls INFO:             name : ImageNetDataset
[2023/12/21 23:40:16] ppcls INFO:             relabel : True
[2023/12/21 23:40:16] ppcls INFO:             transform_ops :
[2023/12/21 23:40:16] ppcls INFO:                 DecodeImage :
[2023/12/21 23:40:16] ppcls INFO:                     channel_first : False
[2023/12/21 23:40:16] ppcls INFO:                     to_rgb : True
[2023/12/21 23:40:16] ppcls INFO:                 ResizeImage :
[2023/12/21 23:40:16] ppcls INFO:                     backend : cv2
[2023/12/21 23:40:16] ppcls INFO:                     interpolation : bilinear
[2023/12/21 23:40:16] ppcls INFO:                     return_numpy : False
[2023/12/21 23:40:16] ppcls INFO:                     size : [224, 224]
[2023/12/21 23:40:16] ppcls INFO:                 RandFlipImage :
[2023/12/21 23:40:16] ppcls INFO:                     flip_code : 1
[2023/12/21 23:40:16] ppcls INFO:                 Pad :
[2023/12/21 23:40:16] ppcls INFO:                     backend : cv2
[2023/12/21 23:40:16] ppcls INFO:                     padding : 10
[2023/12/21 23:40:16] ppcls INFO:                 RandCropImageV2 :
[2023/12/21 23:40:16] ppcls INFO:                     size : [224, 224]
[2023/12/21 23:40:16] ppcls INFO:                 RandomRotation :
[2023/12/21 23:40:16] ppcls INFO:                     degrees : 90
[2023/12/21 23:40:16] ppcls INFO:                     interpolation : bilinear
[2023/12/21 23:40:16] ppcls INFO:                     prob : 0.5
[2023/12/21 23:40:16] ppcls INFO:                 ResizeImage :
[2023/12/21 23:40:16] ppcls INFO:                     backend : cv2
[2023/12/21 23:40:16] ppcls INFO:                     interpolation : bilinear
[2023/12/21 23:40:16] ppcls INFO:                     return_numpy : False
[2023/12/21 23:40:16] ppcls INFO:                     size : [224, 224]
[2023/12/21 23:40:16] ppcls INFO:                 NormalizeImage :
[2023/12/21 23:40:16] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2023/12/21 23:40:16] ppcls INFO:                     order : hwc
[2023/12/21 23:40:16] ppcls INFO:                     scale : 1.0/255.0
[2023/12/21 23:40:16] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2023/12/21 23:40:16] ppcls INFO:         loader :
[2023/12/21 23:40:16] ppcls INFO:             num_workers : 4
[2023/12/21 23:40:16] ppcls INFO:             use_shared_memory : True
[2023/12/21 23:40:16] ppcls INFO:         sampler :
[2023/12/21 23:40:16] ppcls INFO:             batch_size : 2
[2023/12/21 23:40:16] ppcls INFO:             drop_last : False
[2023/12/21 23:40:16] ppcls INFO:             id_list : [50030, 80700, 92019, 96015]
[2023/12/21 23:40:16] ppcls INFO:             name : PKSampler
[2023/12/21 23:40:16] ppcls INFO:             ratio : [4, 4]
[2023/12/21 23:40:16] ppcls INFO:             sample_method : id_avg_prob
[2023/12/21 23:40:16] ppcls INFO:             sample_per_id : 2
[2023/12/21 23:40:16] ppcls INFO:             shuffle : True
[2023/12/21 23:40:16] ppcls INFO: Global :
[2023/12/21 23:40:16] ppcls INFO:     checkpoints : None
[2023/12/21 23:40:16] ppcls INFO:     device : gpu
[2023/12/21 23:40:16] ppcls INFO:     epochs : 100
[2023/12/21 23:40:16] ppcls INFO:     eval_during_train : True
[2023/12/21 23:40:16] ppcls INFO:     eval_interval : 1
[2023/12/21 23:40:16] ppcls INFO:     eval_mode : retrieval
[2023/12/21 23:40:16] ppcls INFO:     image_shape : [3, 224, 224]
[2023/12/21 23:40:16] ppcls INFO:     output_dir : ./output
[2023/12/21 23:40:16] ppcls INFO:     pretrained_model : None
[2023/12/21 23:40:16] ppcls INFO:     print_batch_step : 20
[2023/12/21 23:40:16] ppcls INFO:     re_ranking : False
[2023/12/21 23:40:16] ppcls INFO:     retrieval_feature_from : features
[2023/12/21 23:40:16] ppcls INFO:     save_inference_dir : ./inference
[2023/12/21 23:40:16] ppcls INFO:     save_interval : 1
[2023/12/21 23:40:16] ppcls INFO:     use_dali : False
[2023/12/21 23:40:16] ppcls INFO:     use_visualdl : False
[2023/12/21 23:40:16] ppcls INFO: Loss :
[2023/12/21 23:40:16] ppcls INFO:     Eval :
[2023/12/21 23:40:16] ppcls INFO:         CELoss :
[2023/12/21 23:40:16] ppcls INFO:             weight : 1.0
[2023/12/21 23:40:16] ppcls INFO:     Train :
[2023/12/21 23:40:16] ppcls INFO:         CELoss :
[2023/12/21 23:40:16] ppcls INFO:             epsilon : 0.1
[2023/12/21 23:40:16] ppcls INFO:             weight : 1.0
[2023/12/21 23:40:16] ppcls INFO:         TripletAngularMarginLoss :
[2023/12/21 23:40:16] ppcls INFO:             absolute_loss_weight : 0.1
[2023/12/21 23:40:16] ppcls INFO:             add_absolute : True
[2023/12/21 23:40:16] ppcls INFO:             an_value : 0.4
[2023/12/21 23:40:16] ppcls INFO:             ap_value : 0.8
[2023/12/21 23:40:16] ppcls INFO:             feature_from : features
[2023/12/21 23:40:16] ppcls INFO:             margin : 0.5
[2023/12/21 23:40:16] ppcls INFO:             normalize_feature : True
[2023/12/21 23:40:16] ppcls INFO:             reduction : mean
[2023/12/21 23:40:16] ppcls INFO:             weight : 1.0
[2023/12/21 23:40:16] ppcls INFO: Metric :
[2023/12/21 23:40:16] ppcls INFO:     Eval :
[2023/12/21 23:40:16] ppcls INFO:         Recallk :
[2023/12/21 23:40:16] ppcls INFO:             topk : [1, 5]
[2023/12/21 23:40:16] ppcls INFO:         mAP :
[2023/12/21 23:40:16] ppcls INFO: Optimizer :
[2023/12/21 23:40:16] ppcls INFO:     lr :
[2023/12/21 23:40:16] ppcls INFO:         learning_rate : 0.06
[2023/12/21 23:40:16] ppcls INFO:         name : Cosine
[2023/12/21 23:40:16] ppcls INFO:         warmup_epoch : 5
[2023/12/21 23:40:16] ppcls INFO:     momentum : 0.9
[2023/12/21 23:40:16] ppcls INFO:     name : Momentum
[2023/12/21 23:40:16] ppcls INFO:     regularizer :
[2023/12/21 23:40:16] ppcls INFO:         coeff : 1e-05
[2023/12/21 23:40:16] ppcls INFO:         name : L2
[2023/12/21 23:40:16] ppcls INFO: profiler_options : None
[2023/12/21 23:40:16] ppcls INFO: train with paddle 2.5.2 and device Place(gpu:0)
W1221 23:40:16.366072 17124 gpu_resources.cc:119] Please NOTE: device: 0, GPU Compute Capability: 8.6, Driver API Version: 12.3, Runtime API Version: 11.8
W1221 23:40:16.369956 17124 gpu_resources.cc:149] device: 0, cuDNN Version: 8.6.
[2023/12/21 23:40:16] ppcls INFO: Found C:\Users\monke/.paddleclas/weights\PPLCNetV2_base_ssld_pretrained.pdparams
[2023/12/21 23:40:16] ppcls WARNING: The training strategy provided by PaddleClas is based on 4 gpus. But the number of gpu is 1 in current training. Please modify the stategy (learning rate, batch size and so on) if use this config to train.
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "E:\PaddlePaddle\PaddleClas\ppcls\engine\engine.py", line 356, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "E:\PaddlePaddle\PaddleClas\ppcls\engine\train\train.py", line 51, in train_epoch
    loss_dict = engine.train_loss_func(out, batch[1])
  File "E:\PaddlePaddle\PaddleClas\ppcls\loss\__init__.py", line 68, in __call__
    loss = loss_func(input, batch)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\paddle\nn\layer\layers.py", line 1254, in __call__
    return self.forward(*inputs, **kwargs)
  File "E:\PaddlePaddle\PaddleClas\ppcls\loss\celoss.py", line 49, in forward
    label = self._labelsmoothing(label, class_num)
  File "E:\PaddlePaddle\PaddleClas\ppcls\loss\celoss.py", line 40, in _labelsmoothing
    soft_target = F.label_smooth(one_hot_target, epsilon=self.epsilon)
  File "E:\anaconda3\envs\PaddleClas\lib\site-packages\paddle\nn\functional\common.py", line 1939, in label_smooth
    return _C_ops.label_smooth(label, prior_dist, float(epsilon))
RuntimeError: (NotFound) The kernel with key (GPU, Undefined(AnyLayout), int32) of kernel `label_smooth` is not registered and fail to fallback to CPU one. Selected wrong DataType `int32`. Paddle support following DataTypes: float16, bfloat16, float32, float64.
  [Hint: Expected kernel_iter != iter->second.end(), but received kernel_iter == iter->second.end().] (at ..\paddle\phi\core\kernel_factory.cc:259)
```

**Comment by cuicheng01** [comment]
现在这个问题解决了吗
