### ISSUE TITLE
PaddleClas量化离线训练无法正常训练

### ISSUE THREAD

**Issue by Zheng-Bicheng** [PaddlePaddle/PaddleClas#3084]
# 运行环境

* PaddlePaddle 2.6.0
* PaddleClas 2.5

# 问题排查

## 文件出现原因排查
按照文档运行后，死在[PaddleClas quant_post_static.py文件第65行](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/deploy/slim/quant_post_static.py#L65)

该行调用了**paddleslim.quant.quant_post_static**函数，找到这个函数在[PaddleSlim quanter.py 第508行](https://github.com/PaddlePaddle/PaddleSlim/blob/develop/paddleslim/quant/quanter.py#L508)

该函数调用**PostTrainingQuantization**函数，**PostTrainingQuantization**函数为Paddle框架函数在[Paddle post_training_quantization.py文件第113行](https://github.com/PaddlePaddle/Paddle/blob/1b8710a23ce628f103ec98eda70e397cc806d744/python/paddle/static/quantization/post_training_quantization.py#L113)

继续往下排查发现错误出现在[Paddle post_training_quantization.py 第313行](https://github.com/PaddlePaddle/Paddle/blob/release/2.6/python/paddle/static/quantization/post_training_quantization.py#L313)，意思为必须传入**data_loader**参数

## 尝试解决

修改[PaddleClas quant_post_static.py文件](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/deploy/slim/quant_post_static.py#L65)，将PaddleClas构造的dataloader传入

```python
    paddleslim.quant.quant_post_static(
        executor=exe,
        data_loader=train_dataloader,
        model_dir=config["Global"]["save_inference_dir"],
        model_filename='inference.pdmodel',
        params_filename='inference.pdiparams',
        quantize_model_path=os.path.join(
            config["Global"]["save_inference_dir"], "quant_post_static_model"),
        sample_generator=sample_generator(train_dataloader),
        batch_size=config["DataLoader"]["Eval"]["sampler"]["batch_size"],
        batch_nums=10)
```

报错如下：

```text
Traceback (most recent call last):
  File "/home/aistudio/PaddleClas/deploy/slim/quant_post_static.py", line 93, in <module>
    main()
  File "/home/aistudio/PaddleClas/deploy/slim/quant_post_static.py", line 79, in main
    paddleslim.quant.quant_post_static(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddleslim-0.0.0.dev0-py3.10.egg/paddleslim/quant/quanter.py", line 669, in quant_post_static
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/static/quantization/post_training_quantization.py", line 452, in quantize
    self._executor.run(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/base/executor.py", line 1742, in run
    res = self._run_impl(
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/base/executor.py", line 1881, in _run_impl
    assert len(feed) == 1, "Not compiled with data parallel"
AssertionError: Not compiled with data parallel
```

**Comment by Zheng-Bicheng** [comment]
@cuicheng01 有办法修复吗？如果有思路，我可以提交PR修复这个问题。

**Comment by cuicheng01** [comment]
您好，在PaddlePaddle2.6版本上确实还没有广泛测试过slim相关的能力，这块建议先会退到2.5版本试下呢？2.6我们也会随时跟进和修复哈
