### ISSUE TITLE
Paddle Classification training issue - stuck

### ISSUE THREAD

**Issue by lokeycookie** [PaddlePaddle/PaddleClas#3085]
Hi there,

I was trying to train a classification model using my own dataset and I referenced from this: https://github.com/PaddlePaddle/PaddleClas/blob/release/2.3/docs/zh_CN/quick_start/quick_start_classification_new_user.md

However, when I tried to run tools/train.py, it does not seem to be training and my terminal is stuck at this page referenced below. How do I solve this issue?

Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    engine = Engine(config, mode="train")
  File "/home/PaddleClas/ppcls/engine/engine.py", line 210, in __init__
    self.model = build_model(self.config)
  File "/home/PaddleClas/ppcls/arch/__init__.py", line 38, in build_model
    arch = getattr(mod, model_type)(**arch_config)
  File "/home/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 494, in ResNet50_vd
    **kwargs)
  File "/home/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 321, in __init__
    for in_c, out_c, k, s in self.stem_cfg[version]
  File "/home/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 321, in <listcomp>
    for in_c, out_c, k, s in self.stem_cfg[version]
  File "/home/PaddleClas/ppcls/arch/backbone/legendary_models/resnet.py", line 132, in __init__
    data_format=data_format)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 646, in __init__
    data_format=data_format)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/nn/layer/conv.py", line 135, in __init__
    default_initializer=_get_default_param_initializer())
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 412, in create_parameter
    default_initializer)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/layer_helper_base.py", line 374, in create_parameter
    **attr._to_kwargs(with_initializer=True))
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3193, in create_parameter
    initializer(param, self)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/initializer.py", line 364, in __call__
    stop_gradient=True)
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 3223, in append_op
    kwargs.get("stop_gradient", False))
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/dygraph/tracer.py", line 45, in trace_op
    not stop_gradient)
SystemError: (Fatal) Operator gaussian_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorNoKernelImageForDevice: no kernel image is available for execution on the device. (at /paddle/paddle/fluid/imperative/tracer.cc:192)

**Comment by lokeycookie** [comment]
fixed while using another docker image
