### ISSUE TITLE
在训练过程中报drop_last相关的错误

### ISSUE THREAD

**Issue by yeyupiaoling** [PaddlePaddle/PaddleClas#311]
- PaddlePaddle 1.8.4.post107
 - Python 3.7
 - Ubuntu 16.04

在训练过程一开始我是正常的，后面换到量化训练之后就报错了，我看PaddleCls中的数据读取源码，drop_last=True的 。
```
    return_merged=return_merged)
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/executor.py", line 876, in _run_parallel
    exe.feed_tensors_into_local_scopes(res)
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::ParallelExecutor::FeedTensorsIntoLocalScopes(std::vector<std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > >, std::allocator<std::unordered_map<std::string, paddle::framework::LoDTensor, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, paddle::framework::LoDTensor> > > > > const&)

----------------------
Error Message Summary:
----------------------
UnimplementedError: The feed data number 2 does not match the device number 1. If you are using DataLoader to feed data, this may be because you set drop_last=False in training network. Currently, drop_last=False for DataLoader is not supported for training network. Please set drop_last=True when defining DataLoader.
  [Hint: Expected tensors.size() == member_->local_scopes_.size(), but received tensors.size():2 != member_->local_scopes_.size():1.] at (/paddle/paddle/fluid/framework/parallel_executor.cc:852)
```

量化训练代码如下：
```python
        # 执行量化训练
        quant_program = slim.quant.quant_aware(train_prog, exe.place, for_test=False)
        # 评估量化的结果
        val_quant_program = slim.quant.quant_aware(valid_prog, exe.place, for_test=True)

        fetch_list = [f[0] for f in train_fetchs.values()]
        metric_list = [f[1] for f in train_fetchs.values()]
        for i in range(5):
            for idx, batch in enumerate(train_dataloader()):
                metrics = exe.run(program=quant_program, feed=batch, fetch_list=fetch_list)
                for i, m in enumerate(metrics):
                    metric_list[i].update(np.mean(m), len(batch[0]))
                fetchs_str = ''.join([str(m.value) + ' ' for m in metric_list])

                if idx % 10 == 0:
                    logger.info("quant train : " + fetchs_str)

        fetch_list = [f[0] for f in valid_fetchs.values()]
        metric_list = [f[1] for f in valid_fetchs.values()]
        for idx, batch in enumerate(valid_dataloader()):
            metrics = exe.run(program=val_quant_program, feed=batch, fetch_list=fetch_list)
            for i, m in enumerate(metrics):
                metric_list[i].update(np.mean(m), len(batch[0]))
            fetchs_str = ''.join([str(m.value) + ' ' for m in metric_list])

            if idx % 10 == 0:
                logger.info("quant valid: " + fetchs_str)

        # 保存量化训练模型
        float_prog, int8_prog = slim.quant.convert(val_quant_program, exe.place, save_int8=True)
        fluid.io.save_inference_model(dirname=args.output_path,
                                      feeded_var_names=['feed_image'],
                                      target_vars=out,
                                      executor=exe,
                                      main_program=float_prog,
                                      model_filename='__model__',
                                      params_filename='__params__')
```

如果是使用单卡训练，正常训练没多久就报错了
```
   partial_reader(params, full_lines, part_id, part_num, batch_size))
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/ppcls/data/reader.py", line 188, in partial_reader
    raise SampleNumException('', len(full_lines), batch_size)
ppcls.data.reader.SampleNumException: 
Error: The number of the whole data (18) is smaller than the batch_size (64), and drop_last is turnning on, so nothing  will feed in program, Terminated now. Please reset batch_size to a smaller number or feed more data!

Traceback (most recent call last):
  File "train.py", line 181, in <module>
    main(args)
  File "train.py", line 122, in main
    top1_acc = program.run(valid_dataloader, exe, compiled_valid_prog, valid_fetchs, epoch_id, 'valid', config)
  File "/home/test/yeyupiaoling/TablewareDetection/utils/program.py", line 384, in run
    for idx, batch in enumerate(dataloader()):
  File "/home/test/anaconda3/envs/PaddlePaddle/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1104, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   std::_Function_handler<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> (), std::__future_base::_Task_setter<std::unique_ptr<std::__future_base::_Result<unsigned long>, std::__future_base::_Result_base::_Deleter>, unsigned long> >::_M_invoke(std::_Any_data const&)
5   std::__future_base::_State_base::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>&, bool&)
6   ThreadPool::ThreadPool(unsigned long)::{lambda()#1}::operator()() const

----------------------
Error Message Summary:
----------------------
Error: Blocking queue is killed because the data reader raises an exception
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] at (/paddle/paddle/fluid/operators/reader/blocking_queue.h:141)
```

**Comment by littletomatodonkey** [comment]
需要保证`数据量>= batch_size`

**Comment by yeyupiaoling** [comment]
@littletomatodonkey 是大于的，当我使用单卡训练，并把num_workers设置为1，就可以正常训练了
