### ISSUE TITLE
PaddleClas,图像识别部署，根据2.5文档服务化部署预测过程中出现报错

### ISSUE THREAD

**Issue by liangasheng** [PaddlePaddle/PaddleClas#3119]
1. PaddleClas版本:2.5
2. 操作系统：Linux
3. Python版本：Python3.7
4. CUDA/cuDNN版本：CUDA11.2

不知道是哪里出现了问题..........

Log_id: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_server/pipeline/error_catch.py", line 97, in wrapper
    res = func(*args, **kw)
  File "/usr/local/lib/python3.7/dist-packages/paddle_serving_server/pipeline/error_catch.py", line 160, in wrapper
    raise CustomException(CustomExceptionCode.INPUT_PARAMS_ERROR, "invalid arg list: {}".format(invalid_argument_list), True)
paddle_serving_server.pipeline.error_catch.CustomException:
 exception_code: 5000
 exception_type: INPUT_PARAMS_ERROR
 error_msg: invalid arg list: ['feed_batch']
 is_send_to_user: True
Classname: Op.process.<locals>.feed_fetch_list_check_helper
FunctionName: feed_fetch_list_check_helper
Args: ([{'image': array([[[[ 1.7552555e+00, 1.8148961e+00, 1.7683716e+00, ...,
           2.1792855e+00, 2.1337092e+00, 2.1557925e+00],
         [ 1.7678281e+00, 1.7241918e+00, 1.7089617e+00, ...,
           2.1481514e+00, 2.1290350e+00, 2.1594498e+00],
         [ 1.4959710e+00, 1.3775693e+00, 1.3104501e+00, ...,
           2.1353230e+00, 2.1290350e+00, 2.1593294e+00],
         ...,
         [ 1.4529668e+00, 1.2177272e+00, 7.6402998e-01, ...,
           1.0114311e-02, 5.0559867e-02, 5.0877661e-02],
         [ 1.4787341e+00, 1.2957535e+00, 8.5338312e-01, ...,
          -1.3550961e-02, 4.0748253e-02, -7.0087714e-03],
         [ 1.4572664e+00, 1.3168416e+00, 1.0689977e+00, ...,
          -5.6837790e-02, 3.0182380e-02, 2.0347409e-02]],
        [[ 1.9443148e+00, 2.0044556e+00, 1.9560620e+00, ...,
           2.3223805e+00, 2.3108013e+00, 2.3333771e+00],
         [ 1.9876240e+00, 1.9372795e+00, 1.9159753e+00, ...,
           2.2905517e+00, 2.3060226e+00, 2.3371162e+00],
         [ 1.7488244e+00, 1.6234032e+00, 1.5504090e+00, ...,
           2.2774370e+00, 2.3060226e+00, 2.3369932e+00],
         ...,
         [ 1.6323705e+00, 1.4378358e+00, 1.0506046e+00, ...,
           1.0479035e-01, 1.2421219e-01, 1.1144952e-01],
         [ 1.6403871e+00, 1.5176039e+00, 1.1419522e+00, ...,
           6.8877219e-02, 8.0772944e-02, 1.9691624e-02],
         [ 1.5986216e+00, 1.5334285e+00, 1.3375313e+00, ...,
           1.3297900e-03, 3.9848611e-02, 2.7716808e-02]],
        [[ 2.2278881e+00, 2.2883132e+00, 2.2406859e+00, ...,
           2.5865686e+00, 2.5227530e+00, 2.5103703e+00],
         [ 2.2832479e+00, 2.2383115e+00, 2.2222865e+00, ...,
           2.5548813e+00, 2.5179956e+00, 2.5273280e+00],
         [ 2.0658493e+00, 1.9433855e+00, 1.8731155e+00, ...,
           2.5418246e+00, 2.5179956e+00, 2.5488286e+00],
         ...,
         [ 1.5464119e+00, 1.3130666e+00, 8.6728597e-01, ...,
           1.1739653e-01, 1.8901964e-01, 1.7631368e-01],
         [ 1.6102378e+00, 1.3673422e+00, 9.4741601e-01, ...,
           8.2498997e-02, 1.5320638e-01, 1.1739823e-01],
         [ 1.6150274e+00, 1.3576574e+00, 1.1107703e+00, ...,
           3.1824980e-02, 1.2177086e-01, 1.4524069e-01]]]],
      dtype=float32), 'im_shape': array([[640, 640]]), 'scale_factor': array([[0.79800499, 0.53333333]])}], ['save_infer_model/scale_0.tmp_1'])
ERROR 2024-04-10 08:46:57,437 [operator.py:1101] [det] failed to predict. Log_id: 0 Raise_msg: invalid arg list ClassName: Op.process.<locals>.feed_fetch_list_check_helper FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.
INFO 2024-04-10 08:46:57,438 [operator.py:1488] prometheus inf count +1
ERROR 2024-04-10 08:46:57,441 [dag.py:420] (data_id=0 log_id=0) Failed to predict: [det] failed to predict. Log_id: 0 Raise_msg: invalid arg list ClassName: Op.process.<locals>.feed_fetch_list_check_helper FunctionName: feed_fetch_list_check_helper. Please check the input dict and checkout PipelineServingLogs/pipeline.log for more details.

**Comment by cuicheng01** [comment]
您好，执行的是什么命令呢

**Comment by liangasheng** [comment]
> 您好，执行的是什么命令呢
就是图像识别的串联部署，检测模型和识别模型，服务启动之后
执行 python pipeline_http_client.py,使用官方的drink_dataset数据集的数据发送预测请求

**Comment by ericosmic** [comment]
> 您好，执行的是什么命令呢
就是图像识别的串联部署，检测模型和识别模型，服务启动之后
执行 python pipeline_http_client.py,使用官方的drink_dataset数据集的数据发送预测请求

**Comment by ericosmic** [comment]
@cuicheng01  就是图像识别的串联部署，检测模型和识别模型，服务启动之后, 执行 python pipeline_http_client.py,使用官方的drink_dataset数据集的数据发送预测请求

**Comment by changdazhou** [comment]
应该是组batch出了问题，建议看下paddle_serving_server中的feed_batch是否是更新为其他了，或者版本不适配哈
