### ISSUE TITLE
训练报错

### ISSUE THREAD

**Issue by q465414859** [PaddlePaddle/PaddleClas#3143]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：paddlepaddle-gpu 2.5.2    paddleclas 2.4.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，Windows
  b. Python版本号，Python 3.8.19
  c. CUDA/cuDNN版本， Version: 12.2, Runtime API Version: 11.8
 4. 完整的代码(相比于repo中代码，有改动的地方)、详细的错误信息及相关log

Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine.train()
  File "F:\code\PaddleClas\ppcls\engine\engine.py", line 339, in train
    self.train_epoch_func(self, epoch_id, print_batch_step)
  File "F:\code\PaddleClas\ppcls\engine\train\train.py", line 78, in train_epoch
    update_metric(engine, out, batch, batch_size)
  File "F:\code\PaddleClas\ppcls\engine\train\utils.py", line 28, in update_metric
    trainer.output_info[key].update(metric_dict[key].numpy()[0],
IndexError: too many indices for array: array is 0-dimensional, but 1 were indexed

(PaddleClas) F:\code\PaddleClas>pip list
Package               Version
--------------------- -----------
anyio                 4.3.0
astor                 0.8.1
Babel                 2.14.0
bce-python-sdk        0.9.7
blinker               1.8.1
cachetools            5.3.3
certifi               2024.2.2
charset-normalizer    3.3.2
click                 8.1.7
colorama              0.4.6
contourpy             1.1.1
cssselect             1.2.0
cssutils              2.10.2
cycler                0.12.1
Cython                3.0.10
decorator             5.1.1
easydict              1.13
et-xmlfile            1.1.0
exceptiongroup        1.2.1
faiss-cpu             1.7.1.post2
Flask                 3.0.3
flask-babel           4.0.0
fonttools             4.51.0
future                1.0.0
gast                  0.3.3
h11                   0.14.0
httpcore              1.0.5
httpx                 0.27.0
idna                  3.7
imageio               2.34.1
imgaug                0.4.0
importlib_metadata    7.1.0
importlib_resources   6.4.0
itsdangerous          2.2.0
Jinja2                3.1.3
joblib                1.4.2
kiwisolver            1.4.5
lazy_loader           0.4
Levenshtein           0.25.1
lmdb                  1.4.1
lxml                  5.2.1
MarkupSafe            2.1.5
matplotlib            3.7.5
networkx              3.1
numpy                 1.24.4
opencv-contrib-python 4.4.0.46
opencv-python         4.4.0.46
openpyxl              3.1.2
opt-einsum            3.3.0
packaging             24.0
paddleclas            2.4.0
paddlepaddle-gpu      2.5.2
pandas                2.0.3
pillow                10.3.0
pip                   24.0
premailer             3.10.0
prettytable           3.10.0
protobuf              3.20.2
psutil                5.9.8
pyclipper             1.3.0.post5
pycryptodome          3.20.0
pyparsing             3.1.2
python-dateutil       2.9.0.post0
python-Levenshtein    0.25.1
pytz                  2024.1
PyWavelets            1.4.1
PyYAML                6.0.1
rapidfuzz             3.9.0
rarfile               4.2
requests              2.31.0
scikit-image          0.21.0
scikit-learn          1.3.2
scipy                 1.10.1
setuptools            69.5.1
shapely               2.0.4
six                   1.16.0
sniffio               1.3.1
threadpoolctl         3.5.0
tifffile              2023.7.10
tqdm                  4.66.4
typing_extensions     4.11.0
tzdata                2024.1
ujson                 5.9.0
urllib3               2.2.1
visualdl              2.5.3
wcwidth               0.2.13
Werkzeug              3.0.2
wheel                 0.43.0
zipp                  3.18.1

用的Flowers102测试数据 https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/training/single_label_classification/dataset.md#1-%E6%95%B0%E6%8D%AE%E9%9B%86%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E 
![image](https://github.com/PaddlePaddle/PaddleClas/assets/26251132/96df4d06-fd1f-424b-b9cf-2355be8d497d)

执行后报错！

**Comment by q465414859** [comment]
@TingquanGao

**Comment by kaikaizhu** [comment]
trainer.output_info[key].update(metric_dict[key].numpy()[0]  改为  trainer.output_info[key].update(metric_dict[key].numpy() 即可
