### ISSUE TITLE
paddlecls特征提取模型微调

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleClas#3170]
1. 相关版本如下: 
paddleclas           2.5.1
paddlepaddle         2.5.2
paddlepaddle-gpu     2.5.2.post112
2.python版本号: Python 3.7.13
3. cuda/cudnn版本 cuda11.2/cudnn8.1
文档链接: https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/training/metric_learning/training.md
在运行命令之后python3.7 tools/train.py \
-c ./ppcls/configs/quick_start/MobileNetV1_retrieval.yaml \
-o Arch.Backbone.pretrained=True \
-o Global.device=gpu  报如下问题:
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine = Engine(config, mode="train")
  File "/mnt/project/PaddleClas/ppcls/engine/engine.py", line 99, in __init__
    self.device = paddle.set_device(self.config["Global"]["device"])
  File "/usr/local/lib/python3.7/dist-packages/paddle/device/__init__.py", line 266, in set_device
    place = _convert_to_place(device)
  File "/usr/local/lib/python3.7/dist-packages/paddle/device/__init__.py", line 181, in _convert_to_place
    "The device should not be 'gpu', "
ValueError: The device should not be 'gpu', since PaddlePaddle is not compiled with CUDA
请问这个bug是因为版本不匹配还是其他问题?

**Comment by cuicheng01** [comment]
请问您装的是Paddle的GPU版本吗？建议重新uninstall后再装下GPU版的Paddle呢

**Comment by chinesejunzai12** [comment]
是paddle的GPU版本, 已经解决了, 是版本的问题
