### ISSUE TITLE
GeneralRecognitionV2_PPLCNetV2_base.yaml微调特征提取模型报错

### ISSUE THREAD

**Issue by chinesejunzai12** [PaddlePaddle/PaddleClas#3171]
库对应的版本如下:
paddleclas==2.5.2
paddlepaddle==2.5.2
paddlepaddle-gpt==2.5.2

运行命令报错如下:
python3.7 tools/train.py \
> -c ./ppcls/configs/GeneralRecognitionV2/CUB_GeneralRecognitionV2_PPLCNetV2_base.yaml
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[2024/06/26 17:17:35] ppcls INFO:
===========================================================
==        PaddleClas is powered by PaddlePaddle !        ==
===========================================================
==                                                       ==
==   For more info please go to the following website.   ==
==                                                       ==
==       https://github.com/PaddlePaddle/PaddleClas      ==
===========================================================

[2024/06/26 17:17:35] ppcls INFO: AMP :
[2024/06/26 17:17:35] ppcls INFO:     level : O1
[2024/06/26 17:17:35] ppcls INFO:     scale_loss : 65536
[2024/06/26 17:17:35] ppcls INFO:     use_dynamic_loss_scaling : True
[2024/06/26 17:17:35] ppcls INFO: ------------------------------------------------------------
[2024/06/26 17:17:35] ppcls INFO: Arch :
[2024/06/26 17:17:35] ppcls INFO:     Backbone :
[2024/06/26 17:17:35] ppcls INFO:         class_expand : 512
[2024/06/26 17:17:35] ppcls INFO:         name : PPLCNetV2_base_ShiTu
[2024/06/26 17:17:35] ppcls INFO:         pretrained : True
[2024/06/26 17:17:35] ppcls INFO:         use_ssld : True
[2024/06/26 17:17:35] ppcls INFO:     BackboneStopLayer :
[2024/06/26 17:17:35] ppcls INFO:         name : flatten
[2024/06/26 17:17:35] ppcls INFO:     Head :
[2024/06/26 17:17:35] ppcls INFO:         bias_attr : False
[2024/06/26 17:17:35] ppcls INFO:         class_num : 101
[2024/06/26 17:17:35] ppcls INFO:         embedding_size : 512
[2024/06/26 17:17:35] ppcls INFO:         name : FC
[2024/06/26 17:17:35] ppcls INFO:         weight_attr :
[2024/06/26 17:17:35] ppcls INFO:             initializer :
[2024/06/26 17:17:35] ppcls INFO:                 name : Normal
[2024/06/26 17:17:35] ppcls INFO:                 std : 0.001
[2024/06/26 17:17:35] ppcls INFO:     Neck :
[2024/06/26 17:17:35] ppcls INFO:         bias_attr :
[2024/06/26 17:17:35] ppcls INFO:             initializer :
[2024/06/26 17:17:35] ppcls INFO:                 name : Constant
[2024/06/26 17:17:35] ppcls INFO:                 value : 0.0
[2024/06/26 17:17:35] ppcls INFO:             learning_rate : 1e-20
[2024/06/26 17:17:35] ppcls INFO:         name : BNNeck
[2024/06/26 17:17:35] ppcls INFO:         num_features : 512
[2024/06/26 17:17:35] ppcls INFO:         weight_attr :
[2024/06/26 17:17:35] ppcls INFO:             initializer :
[2024/06/26 17:17:35] ppcls INFO:                 name : Constant
[2024/06/26 17:17:35] ppcls INFO:                 value : 1.0
[2024/06/26 17:17:35] ppcls INFO:     infer_add_softmax : False
[2024/06/26 17:17:35] ppcls INFO:     infer_output_key : features
[2024/06/26 17:17:35] ppcls INFO:     name : RecModel
[2024/06/26 17:17:35] ppcls INFO: DataLoader :
[2024/06/26 17:17:35] ppcls INFO:     Eval :
[2024/06/26 17:17:35] ppcls INFO:         Gallery :
[2024/06/26 17:17:35] ppcls INFO:             dataset :
[2024/06/26 17:17:35] ppcls INFO:                 cls_label_path : ./dataset/CUB_200_2011/test_list.txt
[2024/06/26 17:17:35] ppcls INFO:                 image_root : ./dataset/CUB_200_2011/
[2024/06/26 17:17:35] ppcls INFO:                 name : VeriWild
[2024/06/26 17:17:35] ppcls INFO:                 transform_ops :
[2024/06/26 17:17:35] ppcls INFO:                     DecodeImage :
[2024/06/26 17:17:35] ppcls INFO:                         channel_first : False
[2024/06/26 17:17:35] ppcls INFO:                         to_rgb : True
[2024/06/26 17:17:35] ppcls INFO:                     ResizeImage :
[2024/06/26 17:17:35] ppcls INFO:                         backend : cv2
[2024/06/26 17:17:35] ppcls INFO:                         interpolation : bilinear
[2024/06/26 17:17:35] ppcls INFO:                         return_numpy : False
[2024/06/26 17:17:35] ppcls INFO:                         size : [224, 224]
[2024/06/26 17:17:35] ppcls INFO:                     NormalizeImage :
[2024/06/26 17:17:35] ppcls INFO:                         mean : [0.485, 0.456, 0.406]
[2024/06/26 17:17:35] ppcls INFO:                         order : hwc
[2024/06/26 17:17:35] ppcls INFO:                         scale : 1.0/255.0
[2024/06/26 17:17:35] ppcls INFO:                         std : [0.229, 0.224, 0.225]
[2024/06/26 17:17:35] ppcls INFO:             loader :
[2024/06/26 17:17:35] ppcls INFO:                 num_workers : 4
[2024/06/26 17:17:35] ppcls INFO:                 use_shared_memory : True
[2024/06/26 17:17:35] ppcls INFO:             sampler :
[2024/06/26 17:17:35] ppcls INFO:                 batch_size : 64
[2024/06/26 17:17:35] ppcls INFO:                 drop_last : False
[2024/06/26 17:17:35] ppcls INFO:                 name : DistributedBatchSampler
[2024/06/26 17:17:35] ppcls INFO:                 shuffle : False
[2024/06/26 17:17:35] ppcls INFO:         Query :
[2024/06/26 17:17:35] ppcls INFO:             dataset :
[2024/06/26 17:17:35] ppcls INFO:                 cls_label_path : ./dataset/CUB_200_2011/test_list.txt
[2024/06/26 17:17:35] ppcls INFO:                 image_root : ./dataset/CUB_200_2011/
[2024/06/26 17:17:35] ppcls INFO:                 name : VeriWild
[2024/06/26 17:17:35] ppcls INFO:                 transform_ops :
[2024/06/26 17:17:35] ppcls INFO:                     DecodeImage :
[2024/06/26 17:17:35] ppcls INFO:                         channel_first : False
[2024/06/26 17:17:35] ppcls INFO:                         to_rgb : True
[2024/06/26 17:17:35] ppcls INFO:                     ResizeImage :
[2024/06/26 17:17:35] ppcls INFO:                         backend : cv2
[2024/06/26 17:17:35] ppcls INFO:                         interpolation : bilinear
[2024/06/26 17:17:35] ppcls INFO:                         return_numpy : False
[2024/06/26 17:17:35] ppcls INFO:                         size : [224, 224]
[2024/06/26 17:17:35] ppcls INFO:                     NormalizeImage :
[2024/06/26 17:17:35] ppcls INFO:                         mean : [0.485, 0.456, 0.406]
[2024/06/26 17:17:35] ppcls INFO:                         order : hwc
[2024/06/26 17:17:35] ppcls INFO:                         scale : 1.0/255.0
[2024/06/26 17:17:35] ppcls INFO:                         std : [0.229, 0.224, 0.225]
[2024/06/26 17:17:35] ppcls INFO:             loader :
[2024/06/26 17:17:35] ppcls INFO:                 num_workers : 4
[2024/06/26 17:17:35] ppcls INFO:                 use_shared_memory : True
[2024/06/26 17:17:35] ppcls INFO:             sampler :
[2024/06/26 17:17:35] ppcls INFO:                 batch_size : 64
[2024/06/26 17:17:35] ppcls INFO:                 drop_last : False
[2024/06/26 17:17:35] ppcls INFO:                 name : DistributedBatchSampler
[2024/06/26 17:17:35] ppcls INFO:                 shuffle : False
[2024/06/26 17:17:35] ppcls INFO:     Train :
[2024/06/26 17:17:35] ppcls INFO:         dataset :
[2024/06/26 17:17:35] ppcls INFO:             cls_label_path : ./dataset/CUB_200_2011/train_list.txt
[2024/06/26 17:17:35] ppcls INFO:             image_root : ./dataset/CUB_200_2011/
[2024/06/26 17:17:35] ppcls INFO:             name : VeriWild
[2024/06/26 17:17:35] ppcls INFO:             relabel : True
[2024/06/26 17:17:35] ppcls INFO:             transform_ops :
[2024/06/26 17:17:35] ppcls INFO:                 DecodeImage :
[2024/06/26 17:17:35] ppcls INFO:                     channel_first : False
[2024/06/26 17:17:35] ppcls INFO:                     to_rgb : True
[2024/06/26 17:17:35] ppcls INFO:                 ResizeImage :
[2024/06/26 17:17:35] ppcls INFO:                     backend : cv2
[2024/06/26 17:17:35] ppcls INFO:                     interpolation : bilinear
[2024/06/26 17:17:35] ppcls INFO:                     return_numpy : False
[2024/06/26 17:17:35] ppcls INFO:                     size : [224, 224]
[2024/06/26 17:17:35] ppcls INFO:                 RandFlipImage :
[2024/06/26 17:17:35] ppcls INFO:                     flip_code : 1
[2024/06/26 17:17:35] ppcls INFO:                 Pad :
[2024/06/26 17:17:35] ppcls INFO:                     backend : cv2
[2024/06/26 17:17:35] ppcls INFO:                     padding : 10
[2024/06/26 17:17:35] ppcls INFO:                 RandCropImageV2 :
[2024/06/26 17:17:35] ppcls INFO:                     size : [224, 224]
[2024/06/26 17:17:35] ppcls INFO:                 RandomRotation :
[2024/06/26 17:17:35] ppcls INFO:                     degrees : 90
[2024/06/26 17:17:35] ppcls INFO:                     interpolation : bilinear
[2024/06/26 17:17:35] ppcls INFO:                     prob : 0.5
[2024/06/26 17:17:35] ppcls INFO:                 ResizeImage :
[2024/06/26 17:17:35] ppcls INFO:                     backend : cv2
[2024/06/26 17:17:35] ppcls INFO:                     interpolation : bilinear
[2024/06/26 17:17:35] ppcls INFO:                     return_numpy : False
[2024/06/26 17:17:35] ppcls INFO:                     size : [224, 224]
[2024/06/26 17:17:35] ppcls INFO:                 NormalizeImage :
[2024/06/26 17:17:35] ppcls INFO:                     mean : [0.485, 0.456, 0.406]
[2024/06/26 17:17:35] ppcls INFO:                     order : hwc
[2024/06/26 17:17:35] ppcls INFO:                     scale : 1.0/255.0
[2024/06/26 17:17:35] ppcls INFO:                     std : [0.229, 0.224, 0.225]
[2024/06/26 17:17:35] ppcls INFO:         loader :
[2024/06/26 17:17:35] ppcls INFO:             num_workers : 4
[2024/06/26 17:17:35] ppcls INFO:             use_shared_memory : True
[2024/06/26 17:17:35] ppcls INFO:         sampler :
[2024/06/26 17:17:35] ppcls INFO:             batch_size : 256
[2024/06/26 17:17:35] ppcls INFO:             drop_last : False
[2024/06/26 17:17:35] ppcls INFO:             id_list : [50030, 80700, 92019, 96015]
[2024/06/26 17:17:35] ppcls INFO:             name : PKSampler
[2024/06/26 17:17:35] ppcls INFO:             ratio : [4, 4]
[2024/06/26 17:17:35] ppcls INFO:             sample_method : id_avg_prob
[2024/06/26 17:17:35] ppcls INFO:             sample_per_id : 4
[2024/06/26 17:17:35] ppcls INFO:             shuffle : True
[2024/06/26 17:17:35] ppcls INFO: Global :
[2024/06/26 17:17:35] ppcls INFO:     checkpoints : None
[2024/06/26 17:17:35] ppcls INFO:     device : gpu
[2024/06/26 17:17:35] ppcls INFO:     epochs : 100
[2024/06/26 17:17:35] ppcls INFO:     eval_during_train : True
[2024/06/26 17:17:35] ppcls INFO:     eval_interval : 1
[2024/06/26 17:17:35] ppcls INFO:     eval_mode : retrieval
[2024/06/26 17:17:35] ppcls INFO:     image_shape : [3, 224, 224]
[2024/06/26 17:17:35] ppcls INFO:     output_dir : ./output
[2024/06/26 17:17:35] ppcls INFO:     pretrained_model : None
[2024/06/26 17:17:35] ppcls INFO:     print_batch_step : 20
[2024/06/26 17:17:35] ppcls INFO:     re_ranking : False
[2024/06/26 17:17:35] ppcls INFO:     retrieval_feature_from : features
[2024/06/26 17:17:35] ppcls INFO:     save_inference_dir : ./inference
[2024/06/26 17:17:35] ppcls INFO:     save_interval : 10
[2024/06/26 17:17:35] ppcls INFO:     use_dali : False
[2024/06/26 17:17:35] ppcls INFO:     use_visualdl : False
[2024/06/26 17:17:35] ppcls INFO: Loss :
[2024/06/26 17:17:35] ppcls INFO:     Eval :
[2024/06/26 17:17:35] ppcls INFO:         CELoss :
[2024/06/26 17:17:35] ppcls INFO:             weight : 1.0
[2024/06/26 17:17:35] ppcls INFO:     Train :
[2024/06/26 17:17:35] ppcls INFO:         CELoss :
[2024/06/26 17:17:35] ppcls INFO:             epsilon : 0.1
[2024/06/26 17:17:35] ppcls INFO:             weight : 1.0
[2024/06/26 17:17:35] ppcls INFO:         TripletAngularMarginLoss :
[2024/06/26 17:17:35] ppcls INFO:             absolute_loss_weight : 0.1
[2024/06/26 17:17:35] ppcls INFO:             add_absolute : True
[2024/06/26 17:17:35] ppcls INFO:             an_value : 0.4
[2024/06/26 17:17:35] ppcls INFO:             ap_value : 0.8
[2024/06/26 17:17:35] ppcls INFO:             feature_from : features
[2024/06/26 17:17:35] ppcls INFO:             margin : 0.5
[2024/06/26 17:17:35] ppcls INFO:             normalize_feature : True
[2024/06/26 17:17:35] ppcls INFO:             reduction : mean
[2024/06/26 17:17:35] ppcls INFO:             weight : 1.0
[2024/06/26 17:17:35] ppcls INFO: Metric :
[2024/06/26 17:17:35] ppcls INFO:     Eval :
[2024/06/26 17:17:35] ppcls INFO:         Recallk :
[2024/06/26 17:17:35] ppcls INFO:             topk : [1, 5]
[2024/06/26 17:17:35] ppcls INFO:         mAP :
[2024/06/26 17:17:35] ppcls INFO: Optimizer :
[2024/06/26 17:17:35] ppcls INFO:     lr :
[2024/06/26 17:17:35] ppcls INFO:         learning_rate : 0.06
[2024/06/26 17:17:35] ppcls INFO:         name : Cosine
[2024/06/26 17:17:35] ppcls INFO:         warmup_epoch : 5
[2024/06/26 17:17:35] ppcls INFO:     momentum : 0.9
[2024/06/26 17:17:35] ppcls INFO:     name : Momentum
[2024/06/26 17:17:35] ppcls INFO:     regularizer :
[2024/06/26 17:17:35] ppcls INFO:         coeff : 1e-05
[2024/06/26 17:17:35] ppcls INFO:         name : L2
[2024/06/26 17:17:35] ppcls INFO: profiler_options : None
[2024/06/26 17:17:35] ppcls INFO: train with paddle 2.5.2 and device Place(gpu:0)
Traceback (most recent call last):
  File "tools/train.py", line 32, in <module>
    engine = Engine(config, mode="train")
  File "/mnt/ppcls/engine/engine.py", line 121, in __init__
    self.config["DataLoader"], "Train", self.device, self.use_dali)
  File "/mnt/ppcls/data/__init__.py", line 91, in build_dataloader
    dataset = eval(dataset_name)(**config_dataset)
TypeError: __init__() got an unexpected keyword argument 'relabel'

**Comment by cuicheng01** [comment]
请问您有改过默认的config吗

**Comment by cuicheng01** [comment]
问题我们没有复现，您可以尝试用干净的代码再试试呢？

**Comment by chinesejunzai12** [comment]
这个是在2.3版本出现的, 升级到2.5后没有了, 因为当时看文档的时候指定的是2.3版本
