### ISSUE TITLE
RuntimeError: (NotFound) Cannot open file 

### ISSUE THREAD

**Issue by zgyj4532** [PaddlePaddle/PaddleClas#3299]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，Windows11
  b. Python版本号，Python3.10.15
  c. CUDA/cuDNN版本， CUDA12.2/cuDNN 8.9.7
 4. 完整的代码
输入https://github.com/PaddlePaddle/PaddleClas/blob/release/2.6/docs/zh_CN/models/PULC/PULC_person_attribute.md 中的快速预测代码
  paddleclas --model_name=person_attribute --infer_imgs=pulc_demo_imgs/person_attribute/090004.jpg
出现报错：
Traceback (most recent call last):
  File "C:\Users\ll\AppData\Roaming\uv\python\cpython-3.10.15-windows-x86_64-none\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\ll\AppData\Roaming\uv\python\cpython-3.10.15-windows-x86_64-none\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "E:\AI\paddle\.venv\Scripts\paddleclas.exe\__main__.py", line 8, in <module>
    sys.exit(main())
  File "E:\AI\paddle\.venv\lib\site-packages\paddleclas\paddleclas.py", line 818, in main
    clas_engine = PaddleClas(**cfg)
  File "E:\AI\paddle\.venv\lib\site-packages\paddleclas\paddleclas.py", line 610, in __init__
    self.predictor = ClsPredictor(self._config)
  File "E:\AI\paddle\.venv\lib\site-packages\paddleclas\deploy\python\predict_cls.py", line 28, in __init__
    super().__init__(config["Global"])
  File "E:\AI\paddle\.venv\lib\site-packages\paddleclas\deploy\utils\predictor.py", line 37, in __init__
    self.predictor, self.config = self.create_paddle_predictor(
  File "E:\AI\paddle\.venv\lib\site-packages\paddleclas\deploy\utils\predictor.py", line 108, in create_paddle_predictor
    predictor = create_predictor(config)
RuntimeError: (NotFound) Cannot open file C:\Users\ll/.paddleclas/inference_model\PULC\person_attribute, please confirm whether the file is normal.
  [Hint: Expected static_cast<bool>(fin.is_open()) == true, but received static_cast<bool>(fin.is_open()):0 != true:1.] (at ..\paddle\fluid\inference\api\analysis_predictor.cc:2578)
如图文件已经在该目录中，但是依然打不开
![error](https://github.com/user-attachments/assets/e104b918-fccc-419c-b31f-a6cbfe117451)

**Comment by zgyj4532** [comment]
将paddlepaddle更新至develop版即可解决
