### ISSUE TITLE
含文字图像方向识别，报错：basic_string::at: __n (which is 0) >= this->size() (which is 0)

### ISSUE THREAD

**Issue by sxk000** [PaddlePaddle/PaddleClas#3305]
首先，感谢模型、框架、代码的分享！

最近在使用PaddleClas   做含文字图像方向识别时，报错：basic_string::at: __n (which is 0) >= this->size() (which is 0)
 
操作系统，centos7
PaddleClas   2.6.0
paddlepaddle   2.6.2
python 3.11
cpu环境

按照：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_text_image_orientation.md

上介绍的运行命令：
paddleclas --model_name=text_image_orientation --infer_imgs=pulc_demo_imgs/text_image_orientation/img_rot0_demo.jpg

报如下错误：

```
[2024/11/18 17:12:04] ppcls WARNING: The current running environment does not support the use of GPU. CPU has been used instead.
---1 <paddle.base.libpaddle.AnalysisConfig object at 0x7fbec19ea030>
Traceback (most recent call last):
  File "/apply/miniconda3/envs/p311invoice/bin/paddleclas", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/apply/miniconda3/envs/p311invoice/lib/python3.11/site-packages/paddleclas/paddleclas.py", line 818, in main
    clas_engine = PaddleClas(**cfg)
                  ^^^^^^^^^^^^^^^^^
  File "/apply/miniconda3/envs/p311invoice/lib/python3.11/site-packages/paddleclas/paddleclas.py", line 610, in __init__
    self.predictor = ClsPredictor(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apply/miniconda3/envs/p311invoice/lib/python3.11/site-packages/paddleclas/deploy/python/predict_cls.py", line 28, in __init__
    super().__init__(config["Global"])
  File "/apply/miniconda3/envs/p311invoice/lib/python3.11/site-packages/paddleclas/deploy/utils/predictor.py", line 37, in __init__
    self.predictor, self.config = self.create_paddle_predictor(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/apply/miniconda3/envs/p311invoice/lib/python3.11/site-packages/paddleclas/deploy/utils/predictor.py", line 109, in create_paddle_predictor
    predictor = create_predictor(config)
                ^^^^^^^^^^^^^^^^^^^^^^^^
IndexError: basic_string::at: __n (which is 0) >= this->size() (which is 0)
```

请问改怎么解决呢？谢谢！

**Comment by liuhongen1234567** [comment]
您好，这个问题不是很好解决，我们正在排查中

**Comment by TingquanGao** [comment]
我在Linux环境python 3.10环境下，使用相同的paddle版本 paddleclas版本，未能复现该问题。可以使用以下代码初步检查一下paddle是否安装成功：
```python
import paddle
paddle.utils.install_check.run_check()
```

**Comment by cly234** [comment]
我也发现有这个问题

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by qybing** [comment]
我也遇到了同样的问题，paddle正常运行，版本2.6.2，paddleclas版本2.6.0，paddleclas没有版本2.6.2的，请问如何解决
