### ISSUE TITLE
paddleclas使用table_attribute_infer模型推理，一直提示NameError: name 'beta2' is not defined

### ISSUE THREAD

**Issue by lyl0809** [PaddlePaddle/PaddleClas#3316]
Traceback (most recent call last):
  File "E:\ANACONDA\envs\paddle_env\table_atti\table_atti_p.py", line 9, in <module>
    model = paddleclas.PaddleClas(build_gallery=False,model_name='table_attribute',inference_model_dir='table_attribute_infer')
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\paddle_env\.venv\Lib\site-packages\paddleclas\paddleclas.py", line 610, in __init__
    self.predictor = ClsPredictor(self._config)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\paddle_env\.venv\Lib\site-packages\paddleclas\deploy\python\predict_cls.py", line 28, in __init__
    super().__init__(config["Global"])
  File "E:\ANACONDA\envs\paddle_env\.venv\Lib\site-packages\paddleclas\deploy\utils\predictor.py", line 37, in __init__
    self.predictor, self.config = self.create_paddle_predictor(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ANACONDA\envs\paddle_env\.venv\Lib\site-packages\paddleclas\deploy\utils\predictor.py", line 60, in create_paddle_predictor
    pd_version = 10 * pd_version + eval(v)
                                   ^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'beta2' is not defined

**Comment by liu-jiaxuan** [comment]
Hi，请试下[PaddleX](https://github.com/PaddlePaddle/PaddleX)，在PaddleX中可能会修复套件的潜在问题

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by git9875** [comment]
Similar error:
  File "C:\Users\searo\miniconda3\envs\paddle_env_312\Lib\site-packages\paddleclas\deploy\utils\predictor.py", line 61, in create_paddle_predictor
    pd_version = 10 * pd_version + eval(v)
                                   ^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'rc1' is not defined

I tested the for the pd_version:
```# NOTE: paddle support to PIR mode after v2.6.0
pd_version = 0
for v in paddle.__version__.split(".")[:3]:
    print('v=', v)
    pd_version = 10 * pd_version + eval(v)
```
v= 3
v= 0
v= 0-rc1

So I commented out these lines and added this line.
pd_version = 300


At first it didn't work because I got this error (unrelated to this issue):
RuntimeError: (NotFound) Cannot open file C:\Users\searo/.paddleclas/inference_model\PULC\text_image_orientation/inference.json, please confirm whether the file is normal.

I searched for this error, and the solution was:
export FLAGS_enable_pir_api=0
However, I'm using Windows Terminal with PowerShell as default, so the solution for me is:
$Env:FLAGS_enable_pir_api=0

After that, it worked!
