### ISSUE TITLE
RuntimeError: (NotFound) Cannot open file /home/tcenteryn/.paddleclas/inference_model/PULC/text_image_orientation/inference.json, please confirm whether the file is normal.

### ISSUE THREAD

**Issue by yangqiheng2019** [PaddlePaddle/PaddleClas#3329]
欢迎您使用PaddleClas并反馈相关问题，非常感谢您对PaddleClas的贡献！
提出issue时，辛苦您提供以下信息，方便我们快速定位问题并及时有效地解决您的问题：
 1. PaddleClas版本以及PaddlePaddle版本：请您提供您使用的版本号或分支信息，如PaddleClas release/2.2和PaddlePaddle 2.1.0
 2. 涉及的其他产品使用的版本号：如您在使用PaddleClas的同时还在使用其他产品，如PaddleServing、PaddleInference等，请您提供其版本号
 3. 训练环境信息：
  a. 具体操作系统，如Linux
  b. Python版本号，Python3.10.16
  c. CUDA/cuDNN版本， 如CUDA 11.8
 4. 完整的代码
 import paddleclas
model = paddleclas.PaddleClas(model_name="text_image_orientation")
result = model.predict(input_data="/home/tcenteryn/Direction_program/dataest/chailvfei/20241127100942.jpg")
print(next(result))
5. 问题：
/opt/anaconda3/envs/paddleclas/lib/python3.10/site-packages/paddle/utils/cpp_extension/extension_utils.py:686: UserWarning: No ccache found. Please be aware that recompiling all source files may be required. You can download and install ccache from: https://github.com/ccache/ccache/blob/master/doc/INSTALL.md
  warnings.warn(warning_message)
Traceback (most recent call last):
  File "/home/tcenteryn/Direction_program/PaddleClas/test.py", line 14, in <module>
    model = paddleclas.PaddleClas(model_name="text_image_orientation")
  File "/home/tcenteryn/Direction_program/PaddleClas/paddleclas.py", line 609, in __init__
    self.predictor = ClsPredictor(self._config)
  File "/home/tcenteryn/Direction_program/PaddleClas/deploy/python/predict_cls.py", line 28, in __init__
    super().__init__(config["Global"])
  File "/home/tcenteryn/Direction_program/PaddleClas/deploy/utils/predictor.py", line 37, in __init__
    self.predictor, self.config = self.create_paddle_predictor(
  File "/home/tcenteryn/Direction_program/PaddleClas/deploy/utils/predictor.py", line 65, in create_paddle_predictor
    config = Config(inference_model_dir, model_prefix)
RuntimeError: (NotFound) Cannot open file /home/tcenteryn/.paddleclas/inference_model/PULC/text_image_orientation/inference.json, please confirm whether the file is normal.
  [Hint: Expected paddle::inference::IsFileExists(prog_file_) == true, but received paddle::inference::IsFileExists(prog_file_):0 != true:1.] (at ../paddle/fluid/inference/api/analysis_config.cc:106)

**Comment by cou920** [comment]
paddlecls=2.6.0
训练环境windows 也存在相同的问题

**Comment by Arylu** [comment]
我也遇到了

**Comment by liuhongen1234567** [comment]
inference.json 是 paddle3.0 新lr的模型格式，可以使用 export FLAGS_enable_pir_api=0 导出pdmodel 试试

**Comment by TingquanGao** [comment]
The issue has no response for a long time and will be closed. You can reopen or new another issue if are still confused.

---
_From Bot_

**Comment by Shantanu-Parmar** [comment]
Yes this wortked 
export FLAGS_enable_pir_api=0  # or =1 depending on your case
python tools/export_model.py \
  -c configs/ppyoloe/ppyoloe_plus_crn_l_80e_coco.yml \
  --output_dir=./inference_model \
  -o weights=configs/outputtrain/best_model/model.pdparams

**Comment by Mishatopkek** [comment]
I have the same problem with mot_ppyoloe_l_36e_ppvehicle and mot_ppyoloe_l_36e_pipeline. Howt o export these models if they aren't provided with pdparams. Only pdiparams and pdmodel

**Comment by liuhongen1234567** [comment]
Hello, since pdiparams and pdmodel are already exported models and cannot be exported as JSON, you might consider using a lower version of the PaddleClas wheel package.

**Comment by Mishatopkek** [comment]
@liuhongen1234567 
> Hello, since pdiparams and pdmodel are already exported models and cannot be exported as JSON, you might consider using a lower version of the PaddleClas wheel package.

Are there plans to update the pipelines where you don't need .jsons?
