### ISSUE TITLE
Cuda error(719)

### ISSUE THREAD

**Issue by prj-jxust** [PaddlePaddle/PaddleClas#397]
`Traceback (most recent call last):
  File "tools/train_multi_platform.py", line 169, in <module>
    main(args)
  File "tools/train_multi_platform.py", line 133, in main
    epoch_id, 'train', config, vdl_writer)
  File "E:\PaddleClas-master\tools\program.py", line 435, in run
    metrics = exe.run(program=program, feed=batch, fetch_list=fetch_list)
  File "E:\anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\executor.py", line 1107, in run
    six.reraise(*sys.exc_info())
  File "E:\anaconda\envs\paddle2.0\lib\site-packages\six.py", line 703, in reraise
    raise value
  File "E:\anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\executor.py", line 1105, in run
    return_merged=return_merged)
  File "E:\anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\executor.py", line 1242, in _run_impl
    return_merged=return_merged)
  File "E:\anaconda\envs\paddle2.0\lib\site-packages\paddle\fluid\executor.py", line 910, in _run_parallel
    tensors = exe.run(fetch_var_names, return_merged)._move_to_list()
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
Not support stack backtrace yet.

----------------------
Error Message Summary:
----------------------
ExternalError:  Cuda error(719), unspecified launch failure.
  [Advise: Please search for the error code(719) on website( https://docs.nvidia.com/cuda/archive/10.0/cuda-runtime-api/group__CUDART__TYPES.html#group__CUDART__TYPES_1g3f51e3575c2178246db0a94a430e0038 ) to get Nvidia's official soluti
on about CUDA Error.] (at D:\2.0.0-rc0\paddle\paddle\fluid\platform\stream\cuda_stream.cc:65)
`
训练过程中会随机中止报错，用的paddle2.0rc

**Comment by littletomatodonkey** [comment]
你好，如果是master分支的话，目前建议使用Paddle2.0-beta或者之前的版本哈
