### ISSUE TITLE
dygraph分支下动态图eval出错

### ISSUE THREAD

**Issue by wanghaoshuang** [PaddlePaddle/PaddleClas#443]
PaddlePaddle版本：develop分支
在PaddleClas  dygraph分支下，执行：

```
export CUDA_VISIBLE_DEVICES=0
python tools/eval.py -c ./configs/eval.yaml
```

eval.yaml内容见error log.

error log:
```
2020-12-03 03:42:55 INFO: ARCHITECTURE :
2020-12-03 03:42:55 INFO:     name : MobileNetV1
2020-12-03 03:42:55 INFO: ------------------------------------------------------------
2020-12-03 03:42:55 INFO: VALID :
2020-12-03 03:42:55 INFO:     batch_size : 256
2020-12-03 03:42:55 INFO:     data_dir : ./dataset/ILSVRC2012/
2020-12-03 03:42:55 INFO:     file_list : ./dataset/ILSVRC2012/val_list.txt
2020-12-03 03:42:55 INFO:     num_workers : 4
2020-12-03 03:42:55 INFO:     shuffle_seed : 0
2020-12-03 03:42:55 INFO:     transforms :
2020-12-03 03:42:55 INFO:         DecodeImage :
2020-12-03 03:42:55 INFO:             channel_first : False
2020-12-03 03:42:55 INFO:             to_np : False
2020-12-03 03:42:55 INFO:             to_rgb : True
2020-12-03 03:42:55 INFO:         ResizeImage :
2020-12-03 03:42:55 INFO:             resize_short : 256
2020-12-03 03:42:55 INFO:         CropImage :
2020-12-03 03:42:55 INFO:             size : 224
2020-12-03 03:42:55 INFO:         NormalizeImage :
2020-12-03 03:42:55 INFO:             mean : [0.485, 0.456, 0.406]
2020-12-03 03:42:55 INFO:             order :
2020-12-03 03:42:55 INFO:             scale : 1.0/255.0
2020-12-03 03:42:55 INFO:             std : [0.229, 0.224, 0.225]
2020-12-03 03:42:55 INFO:         ToCHWImage : None
2020-12-03 03:42:55 INFO: ------------------------------------------------------------
2020-12-03 03:42:55 INFO: classes_num : 1000
2020-12-03 03:42:55 INFO: image_shape : [3, 224, 224]
2020-12-03 03:42:55 INFO: mode : valid
2020-12-03 03:42:55 INFO: pretrained_model : /root/PaddleSlim/demo/dygraph/pruning/PaddleClas/MobileNetV1/best_model/ppcls
2020-12-03 03:42:55 INFO: topk : 5
2020-12-03 03:42:55 INFO: total_images : 1281167
W1203 03:42:55.997026 82034 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 11.0, Runtime API Version: 10.0
W1203 03:42:56.003563 82034 device_context.cc:346] device: 0, cuDNN Version: 7.5.
2020-12-03 03:43:01 INFO: Finish initing model from /root/PaddleSlim/demo/dygraph/pruning/PaddleClas/MobileNetV1/best_model/ppcls
2020-12-03 03:43:16 ERROR: DataLoader reader thread raised an exception!
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 674, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/root/miniconda3/lib/python3.8/multiprocessing/queues.py", line 108, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 606, in _thread_loop
    batch = self._get_data()
  File "/root/miniconda3/lib/python3.8/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 689, in _get_data
    raise RuntimeError("DataLoader {} workers exit unexpectedly, " \
RuntimeError: DataLoader 3 workers exit unexpectedly, pids: 82046, 82047, 82048
Traceback (most recent call last):
  File "tools/eval.py", line 79, in <module>
    main(args)
  File "tools/eval.py", line 71, in main
    top1_acc = program.run(valid_dataloader, config, net, None, None, 0,
  File "/root/PaddleSlim/demo/dygraph/pruning/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
```

**Comment by littletomatodonkey** [comment]
/dev/shm 需要设置的再大一些，否则共享内存可能不足，dataloader可能会有异常
