### ISSUE TITLE
使用自己的数据对模型进行微调报错

### ISSUE THREAD

**Issue by Maxhyl** [PaddlePaddle/PaddleClas#449]
2020-12-04 16:52:25 INFO: ARCHITECTURE : 
2020-12-04 16:52:25 INFO:     name : ResNet50_vd
2020-12-04 16:52:25 INFO: ------------------------------------------------------------
2020-12-04 16:52:25 INFO: LEARNING_RATE : 
2020-12-04 16:52:25 INFO:     function : Cosine
2020-12-04 16:52:25 INFO:     params : 
2020-12-04 16:52:25 INFO:         lr : 0.00375
2020-12-04 16:52:25 INFO: ------------------------------------------------------------
2020-12-04 16:52:25 INFO: OPTIMIZER : 
2020-12-04 16:52:25 INFO:     function : Momentum
2020-12-04 16:52:25 INFO:     params : 
2020-12-04 16:52:25 INFO:         momentum : 0.9
2020-12-04 16:52:25 INFO:     regularizer : 
2020-12-04 16:52:25 INFO:         factor : 1e-06
2020-12-04 16:52:25 INFO:         function : L2
2020-12-04 16:52:25 INFO: ------------------------------------------------------------
2020-12-04 16:52:25 INFO: TRAIN : 
2020-12-04 16:52:25 INFO:     batch_size : 32
2020-12-04 16:52:25 INFO:     data_dir : ./dataset/safety_data/
2020-12-04 16:52:25 INFO:     file_list : ./dataset/safety_data/train_list.txt
2020-12-04 16:52:25 INFO:     num_workers : 4
2020-12-04 16:52:25 INFO:     shuffle_seed : 0
2020-12-04 16:52:25 INFO:     transforms : 
2020-12-04 16:52:25 INFO:         DecodeImage : 
2020-12-04 16:52:25 INFO:             channel_first : False
2020-12-04 16:52:25 INFO:             to_np : False
2020-12-04 16:52:25 INFO:             to_rgb : True
2020-12-04 16:52:25 INFO:         RandCropImage : 
2020-12-04 16:52:25 INFO:             size : 224
2020-12-04 16:52:25 INFO:         RandFlipImage : 
2020-12-04 16:52:25 INFO:             flip_code : 1
2020-12-04 16:52:25 INFO:         NormalizeImage : 
2020-12-04 16:52:25 INFO:             mean : [0.485, 0.456, 0.406]
2020-12-04 16:52:25 INFO:             order : 
2020-12-04 16:52:25 INFO:             scale : 1./255.
2020-12-04 16:52:25 INFO:             std : [0.229, 0.224, 0.225]
2020-12-04 16:52:25 INFO:         ToCHWImage : None
2020-12-04 16:52:25 INFO: ------------------------------------------------------------
2020-12-04 16:52:25 INFO: VALID : 
2020-12-04 16:52:25 INFO:     batch_size : 20
2020-12-04 16:52:25 INFO:     data_dir : ./dataset/safety_data/
2020-12-04 16:52:25 INFO:     file_list : ./dataset/safety_data/val_list.txt
2020-12-04 16:52:25 INFO:     num_workers : 4
2020-12-04 16:52:25 INFO:     shuffle_seed : 0
2020-12-04 16:52:25 INFO:     transforms : 
2020-12-04 16:52:25 INFO:         DecodeImage : 
2020-12-04 16:52:25 INFO:             channel_first : False
2020-12-04 16:52:25 INFO:             to_np : False
2020-12-04 16:52:25 INFO:             to_rgb : True
2020-12-04 16:52:25 INFO:         ResizeImage : 
2020-12-04 16:52:25 INFO:             resize_short : 256
2020-12-04 16:52:25 INFO:         CropImage : 
2020-12-04 16:52:25 INFO:             size : 224
2020-12-04 16:52:25 INFO:         NormalizeImage : 
2020-12-04 16:52:25 INFO:             mean : [0.485, 0.456, 0.406]
2020-12-04 16:52:25 INFO:             order : 
2020-12-04 16:52:25 INFO:             scale : 1.0/255.0
2020-12-04 16:52:25 INFO:             std : [0.229, 0.224, 0.225]
2020-12-04 16:52:25 INFO:         ToCHWImage : None
2020-12-04 16:52:25 INFO: ------------------------------------------------------------
2020-12-04 16:52:25 INFO: classes_num : 3
2020-12-04 16:52:25 INFO: epochs : 20
2020-12-04 16:52:25 INFO: image_shape : [3, 224, 224]
2020-12-04 16:52:25 INFO: mode : train
2020-12-04 16:52:25 INFO: model_save_dir : ./output/
2020-12-04 16:52:25 INFO: pretrained_model : ./pretrained/ResNet50_vd_pretrained
2020-12-04 16:52:25 INFO: save_interval : 1
2020-12-04 16:52:25 INFO: topk : 5
2020-12-04 16:52:25 INFO: total_images : 4194
2020-12-04 16:52:25 INFO: valid_interval : 1
2020-12-04 16:52:25 INFO: validate : True

API is deprecated since 2.0.0 Please use FleetAPI instead.
WIKI: https://github.com/PaddlePaddle/Fleet/blob/develop/markdown_doc/transpiler

        
W1204 16:52:26.768529  9462 device_context.cc:338] Please NOTE: device: 0, CUDA Capability: 70, Driver API Version: 10.1, Runtime API Version: 10.1
W1204 16:52:26.773313  9462 device_context.cc:346] device: 0, cuDNN Version: 7.6.
2020-12-04 16:52:30 INFO: Loading parameters from ./pretrained/ResNet50_vd_pretrained...
2020-12-04 16:52:30 WARNING: variable fc_0.w_0 is already excluded automatically
2020-12-04 16:52:30 WARNING: variable fc_0.b_0 is already excluded automatically
2020-12-04 16:52:30 INFO: Finish initing model from ['./pretrained/ResNet50_vd_pretrained']
2020-12-04 16:52:31 INFO: epoch:0   train step:0    loss:  1.1006 top1: 0.2812 top3: 1.0000 lr: 0.003750 elapse: 0.92643s ips: 34.54110 images/sec.
2020-12-04 16:52:33 INFO: epoch:0   train step:10   loss:  0.9748 top1: 0.4375 top3: 1.0000 lr: 0.003750 elapse: 0.24814s ips: 128.95966 images/sec.
Process Process-2:
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py:1188: DeprecationWarning: The 'warn' function is deprecated, use 'warning' instead
  logging.warn('Your reader has raised an exception!')
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
2020-12-04 16:52:34 WARNING: Your reader has raised an exception!
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 607, in _read_into_queue
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 600, in _read_into_queue
    for sample in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 198, in reader
    yield (transform(img, ops), int(label))
  File "/home/aistudio/PaddleClas/ppcls/data/imaug/__init__.py", line 43, in transform
    data = op(data)
  File "/home/aistudio/PaddleClas/ppcls/data/imaug/operators.py", line 51, in __call__
    img) > 0, "invalid input 'img' in DecodeImage"
AssertionError: invalid input 'img' in DecodeImage
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1189, in __thread_main__
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1169, in __thread_main__
    for tensors in self._tensor_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1239, in __tensor_reader_impl__
    for slots in paddle_reader():
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/data_feeder.py", line 546, in __reader_creator__
    for item in reader():
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 281, in wrapper
    for idx, sample in enumerate(reader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/reader/decorator.py", line 623, in queue_reader
    raise ValueError("multiprocess reader raises an exception")
ValueError: multiprocess reader raises an exception

Traceback (most recent call last):
  File "tools/train.py", line 178, in <module>
    main(args)
  File "tools/train.py", line 142, in main
    epoch_id, 'train', config, vdl_writer)
  File "/home/aistudio/PaddleClas/tools/program.py", line 485, in run
    for idx, batch in enumerate(dataloader):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/reader.py", line 1148, in __next__
    return self._reader.read_next()
paddle.fluid.core_avx.EnforceNotMet: 

--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   std::thread::_State_impl<std::thread::_Invoker<std::tuple<ThreadPool::ThreadPool(unsigned long)::{lambda()#1}> > >::_M_run()
1   std::__future_base::_State_baseV2::_M_do_set(std::function<std::unique_ptr<std::__future_base::_Result_base, std::__future_base::_Result_base::_Deleter> ()>*, bool*)
2   paddle::operators::reader::PyReader::ReadNext(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
3   paddle::operators::reader::BlockingQueue<std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> > >::Receive(std::vector<paddle::framework::LoDTensor, std::allocator<paddle::framework::LoDTensor> >*)
4   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
5   paddle::platform::GetCurrentTraceBackString[abi:cxx11]()

----------------------
Error Message Summary:
----------------------
FatalError: Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)

数据一共有三个分类，但是只跑了10个step就报错了，请问是什么问题？

**Comment by thomas-yanxin** [comment]
请问这个问题您是怎么解决的呢？我这边也出现了相同的问题

**Comment by Maxhyl** [comment]
> 请问这个问题您是怎么解决的呢？我这边也出现了相同的问题

图片的命名方式改成和示例一样的就可以了
