### ISSUE TITLE
灰度图训练

### ISSUE THREAD

**Issue by Qggg** [PaddlePaddle/PaddleClas#520]
你好
训练样本为低分辨率灰度图，我将配置文件调整为image_shape: [1, 160, 160]，batch_size为64。
将图片转为灰度图方法为
    im_gray = cv2.imread(srcImg, cv2.IMREAD_GRAYSCALE)
    cv2.imwrite(dstImg, im_gray)
但训练时候报错
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "tools/train.py", line 158, in <module>
    main(args)
  File "tools/train.py", line 123, in main
    epoch_id, 'train', config, vdl_writer)
  File "/home/path_to_clone_PaddleClas/PaddleClas/tools/program.py", line 435, in run
    metrics = exe.run(program=program, feed=batch, fetch_list=fetch_list)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/executor.py", line 1167, in _run_impl
    return_merged=return_merged)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/executor.py", line 873, in _run_parallel
    check_feed_shape_type(var, tensor)
  File "/usr/local/python3.5.1/lib/python3.5/site-packages/paddle/fluid/executor.py", line 225, in check_feed_shape_type
    (var.name, len(var.shape), var.shape, diff_shape))
ValueError: The fed Variable 'feed_image' should have dimensions = 4, shape = (-1, 1, 160, 160), but received fed shape [64, 3, 160, 160] on each device
是否为paddle读取图片时默认是3通道的？

**Comment by TingquanGao** [comment]
你是用`cv2.imwrite(dstImg, im_gray)`保存的图像文件后缀名是啥呢？

**Comment by Qggg** [comment]
> 可以排查一下图像文件读取进来后的shape，或许需要这样：
> 
> ```python
> gray = cv2.imreade("img.png", cv2.IMREAD_GRAYSCALE)
> ```

底层是用read的后用numpy进行处理的，不是直接imread的。最好是由baidu的官方来修正。

**Comment by littletomatodonkey** [comment]
这块建议用三通道模式训练吧，单通道的复制三份即可
