### ISSUE TITLE
paddleclas训练出错

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleClas#533]
W0104 11:15:21.373939  3389 device_context.cc:320] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 10.1, Runtime API Version: 10.1
W0104 11:15:21.378572  3389 device_context.cc:330] device: 0, cuDNN Version: 7.6.
2021-01-04 11:15:26 INFO: If regularizer of a Parameter has been set by 'paddle.ParamAttr' or 'static.WeightNormParamAttr' already. The weight_decay[L2Decay, regularization_coeff=0.000001] in Optimizer will not take effect, and it will only be applied to other Parameters!
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1245: UserWarning: Skip loading for out.weight. out.weight receives a shape [1280, 1000], but the expected shape is [1280, 6].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1245: UserWarning: Skip loading for out.bias. out.bias receives a shape [1000], but the expected shape is [6].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
2021-01-04 11:15:26 INFO: Finish initing model from ./pretrained/MobileNetV3_large_x1_0_pretrained
2021-01-04 11:15:26 ERROR: DataLoader reader thread raised an exception!
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/aistudio/work/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 771, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:154)
  [Hint: If you need C++ stacktraces for debugging, please set `FLAGS_call_stack_level=2`.]

**Comment by littletomatodonkey** [comment]
看着是数据路径有问题，先看下数据是否配置正确吧

**Comment by wa3926** [comment]
@littletomatodonkey  请问下 有检查数据以及配置是否正确的代码吗   所有的图片都能正常 imread 也不是 None   没发现哪里错了
