### ISSUE TITLE
模型用inter/predict推理,批量预测，输入为文件夹，出错

### ISSUE THREAD

**Issue by yy11223** [PaddlePaddle/PaddleClas#534]
trainers_endpoints: 127.0.0.1:6170 , node_id: 0 , current_node_ip: 127.0.0.1 , num_nodes: 1 , node_ips: ['127.0.0.1'] , nranks: 1
Traceback (most recent call last):
  File "tools/infer/predict.py", line 160, in <module>
    main()
  File "tools/infer/predict.py", line 121, in main
    inputs = preprocess(args.image_file, operators)
  File "tools/infer/predict.py", line 88, in preprocess
    data = open(fname, 'rb').read()
IsADirectoryError: [Errno 21] Is a directory: './dataset/test/by'
2021-01-04 11:34:19,144-ERROR: ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
ERROR 2021-01-04 11:34:19,144 launch.py:284] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.

**Comment by littletomatodonkey** [comment]
你好，麻烦拉取下最新的代码吧，目前已经支持文件夹中所有图片的预测了

https://github.com/PaddlePaddle/PaddleClas/blob/5f6992d9a87ee290ca74c43983b143509c179a06/tools/infer/predict.py#L40
