### ISSUE TITLE
训练到validate出错KeyError: 'top2'

### ISSUE THREAD

**Issue by abanger** [PaddlePaddle/PaddleClas#554]
训练到validate出错
模型为ResNet101_vd，paddledetection版本是直接从库clone,配置文件是参考默认配置ResNet101_vd.yaml

2021-01-10 03:01:54 INFO: END epoch:0 train loss: 0.46529, batch_cost: 0.27681 s, reader_cost: 0.00457 s, batch_cost_sum: 287.04682 s, ips: 115.60483 images/sec.
Traceback (most recent call last):
File "tools/train.py", line 118, in
main(args)
File "tools/train.py", line 97, in main
None, epoch_id, 'valid')
File "/home/2Nbeta/PaddleClas/tools/program.py", line 331, in run
metric_list[name].update(fetch.numpy()[0], batch_size)
KeyError: 'top2'

**Comment by CZH-TOP** [comment]
您好！测试了您提出的疑问，没有出现这个错误。建议您下载一下最新的dygraph分支代码。

**Comment by enteguo** [comment]
问题解决了吗，我也出现了同样问题

**Comment by abanger** [comment]
> 问题解决了吗，我也出现了同样问题

后来使用paddlex

**Comment by huangch1024** [comment]
我也出现了同样的问题
