### ISSUE TITLE
The setting of Parameter-Server must has server_num or servers.

### ISSUE THREAD

**Issue by Mr-Zhange** [PaddlePaddle/PaddleClas#562]
PS D:\Code\PaddleClas> D:\Code\PaddleClas\venv\Scripts\python.exe -m paddle.distributed.launch .\tools\train.py -c .\configs\quick_start\ResNet50_vd.yaml
-----------  Configuration Arguments -----------
gpus: None
heter_worker_num: None
heter_workers:
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers:
training_script: .\tools\train.py
training_script_args: ['-c', '.\\configs\\quick_start\\ResNet50_vd.yaml']
worker_num: None
workers:
------------------------------------------------
WARNING 2021-01-15 22:09:04,270 launch.py:308] Not found distinct arguments and not compiled with cuda. Default use ps mode
Traceback (most recent call last):
  File "D:\Program Files\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\Code\PaddleClas\venv\lib\site-packages\paddle\distributed\launch.py", line 16, in <module>
    launch.launch()
  File "D:\Code\PaddleClas\venv\lib\site-packages\paddle\distributed\fleet\launch.py", line 328, in launch
    launch_ps(args, distribute_mode)
  File "D:\Code\PaddleClas\venv\lib\site-packages\paddle\distributed\fleet\launch.py", line 261, in launch_ps
    ps_launcher = ParameterServerLauncher(args, distribute_mode)
  File "D:\Code\PaddleClas\venv\lib\site-packages\paddle\distributed\fleet\launch_utils.py", line 717, in __init__
    self.get_role_endpoints(args)
  File "D:\Code\PaddleClas\venv\lib\site-packages\paddle\distributed\fleet\launch_utils.py", line 734, in get_role_endpoints
    assert args.servers != "", "The setting of Parameter-Server must has server_num or servers."
AssertionError: The setting of Parameter-Server must has server_num or servers.

**Comment by CZH-TOP** [comment]
您好！distribute.launch是分布式启动方式，需要安装nccl，windows目前还不能够支持分布式。敬请期待。
目前可以在windows上使用python .\tools\train.py -c .\configs\quick_start\ResNet50_vd.yaml 直接启动。
