### ISSUE TITLE
tools/export_serving_model.py文件不能导出模型

### ISSUE THREAD

**Issue by Reatris** [PaddlePaddle/PaddleClas#602]
paddle2.0
应该是最新的分支
导出模型的时候报错如下
Traceback (most recent call last):
  File "tools/export_serving_model.py", line 80, in <module>
    main()
  File "tools/export_serving_model.py", line 67, in main
    out = create_model(args, model, image, class_dim=args.class_dim)
  File "tools/export_serving_model.py", line 48, in create_model
    out = model.net(input=input, class_dim=class_dim)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py", line 1039, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'MobileNet' object has no attribute 'net'

看了下确实没.net这个函数

**Comment by littletomatodonkey** [comment]
你好，PaddleServing目前还在适配中哈，敬请期待~服务化部署的话，可以先使用hubserving进行部署：

https://github.com/PaddlePaddle/PaddleClas/blob/dygraph/deploy/hubserving/readme.md
