### ISSUE TITLE
paddleclas做模型评估的时候一直报错怎么解决？

### ISSUE THREAD

**Issue by zhugailin** [PaddlePaddle/PaddleClas#610]
```
Traceback (most recent call last):
  File "tools/eval.py", line 90, in <module>
    main(args)
  File "tools/eval.py", line 62, in main
    fleet.init(role)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/incubate/fleet/base/fleet_base.py", line 219, in init
    self._role_maker.generate_role()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/incubate/fleet/base/role_maker.py", line 539, in generate_role
    assert self._worker_endpoints is not None, "can't find PADDLE_TRAINER_ENDPOINTS"
AssertionError: can't find PADDLE_TRAINER_ENDPOINTS
```
另外想问下，paddlecls不能像PaddleX一样读取模型然后进行批量测试图片进行输出么？像召回率以及F1这些指标是否有api可以调用？

**Comment by littletomatodonkey** [comment]
你好，你的代码分支和运行命令是什么呢？
1. 建议使用`release/2.0`的动态图分支哈，命令直接使用python tools/eval.py -c xxx.yaml即可
2. 召回率和准确率可以使用paddle.metric.Recall和paddle.metric.Precision进行计算，F1可以用这两个指标计算出来

**Comment by littletomatodonkey** [comment]
你好，如果暂时没有其他问题，我们就先关闭该issue了，如果上面的命令还有问题，麻烦重新打开该issue或者新建issue哈，感谢关注~
