### ISSUE TITLE
paddleclas训练过程中报错

### ISSUE THREAD

**Issue by thomas-yanxin** [PaddlePaddle/PaddleClas#626]
WARNING: DataLoader reader thread raised an exception.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 347, in _thread_loop
    six.reraise(*sys.exc_info())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 317, in _thread_loop
    batch = self._dataset_fetcher.fetch(indices)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 60, in fetch
    data = [self.dataset[idx] for idx in batch_indices]
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/fetcher.py", line 60, in <listcomp>
    data = [self.dataset[idx] for idx in batch_indices]
  File "/home/aistudio/PaddleClas/ppcls/data/reader.py", line 190, in __getitem__
    return (transform(img, self.ops), int(label))
  File "/home/aistudio/PaddleClas/ppcls/data/imaug/__init__.py", line 43, in transform
    data = op(data)
  File "/home/aistudio/PaddleClas/ppcls/data/imaug/operators.py", line 157, in __call__
    return cv2.resize(img, size)
cv2.error: OpenCV(4.1.1) /io/opencv/modules/imgproc/src/resize.cpp:3720: error: (-215:Assertion failed) !ssize.empty() in function 'resize'

Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/aistudio/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 365, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

INFO 2021-03-06 11:57:14,108 launch_utils.py:307] terminate all the procs
ERROR 2021-03-06 11:57:14,108 launch_utils.py:545] ABORT!!! Out of all 1 trainers, the trainer process with rank=[0] was aborted. Please check its log.
INFO 2021-03-06 11:57:17,111 launch_utils.py:307] terminate all the procs

**Comment by thomas-yanxin** [comment]
使用paddle clas已经在进行过程中了，它突然报错，使用的数据集较大，约4w张图片

**Comment by littletomatodonkey** [comment]
这个看着是img为空导致的，需要检查下列表里的每张图片是否可以正常读入，以及img不为空哈

**Comment by littletomatodonkey** [comment]
这个pr中也对reader这块的报错信息做了下优化，可以看下：#628
