### ISSUE TITLE
导出inference模型出错

### ISSUE THREAD

**Issue by syyxsxx** [PaddlePaddle/PaddleClas#635]
Paddleclas:release/2.0
PaddlePaddle:Version: 2.0.1
模型通过是通过教程训练的MobileNetV3_large_x1_0
运行命令：
python tools/export_model.py --model MobileNetV3_large_x1_0 --pretrained_model ./output/MobileNetV3_large_x1_0/best_model/ppcls --output_path ./inference
错误提示：
/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.weight. out.weight receives a shape [1280, 102], but the expected shape is [1280, 1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.bias. out.bias receives a shape [102], but the expected shape is [1000].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:77: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return (isinstance(seq, collections.Sequence) and
Traceback (most recent call last):
  File "tools/export_model.py", line 79, in <module>
    main()
  File "tools/export_model.py", line 75, in main
    paddle.jit.save(model, os.path.join(args.output_path, "inference"))
  File "<decorator-gen-60>", line 2, in save
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/jit.py", line 681, in save
    inner_input_spec)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 488, in concrete_program_specify_input_spec
    *desired_input_spec)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 402, in get_concrete_program
    concrete_program, partial_program_layer = self._program_cache[cache_key]
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 711, in __getitem__
    self._caches[item] = self._build_once(item)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 702, in _build_once
    class_instance=cache_key.class_instance)
  File "<decorator-gen-58>", line 2, in from_func_spec
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/base.py", line 39, in __impl__
    return func(*args, **kwargs)
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 658, in from_func_spec
    error_data.raise_new_exception()
  File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/error.py", line 189, in raise_new_exception
    six.exec_("raise new_exception from None")
  File "<string>", line 1, in <module>
AttributeError: In transformed code:

    File "tools/export_model.py", line 51, in forward (* user code *)
	x = self.pre_net(inputs)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/convert_call_func.py", line 220, in convert_call
	forward_func = convert_to_static(forward_func)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 141, in convert_to_static
	static_func = _FUNCTION_CACHE.convert_with_cache(function)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 78, in convert_with_cache
	static_func = self._convert(func)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/program_translator.py", line 116, in _convert
	root_wrapper = self._dygraph_to_static.get_static_ast(root)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 61, in get_static_ast
	self.transfer_from_node_type(self.static_analysis_root)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 92, in transfer_from_node_type
	self._apply(transformer, node_wrapper, log_level=index + 1)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/ast_transformer.py", line 65, in _apply
	transformer(node_wrapper).transform()
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 435, in transform
	self.visit(self.root)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 438, in visit
	self.generic_visit(node)
    File "/root/anaconda3/envs/wsy/lib/python3.7/ast.py", line 326, in generic_visit
	value = self.visit(value)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 441, in visit
	self.replace_stmt_list(node.body)
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 457, in replace_stmt_list
	new_stmts = self.get_for_stmt_nodes(body_list[i])
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/loop_transformer.py", line 479, in get_for_stmt_nodes
	stmts_tuple = current_for_node_parser.parse()
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1030, in parse
	return self._parse_for_stmts()
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1094, in _parse_for_stmts
	target_node, assign_node = self._build_assign_var_slice_node()
    File "/root/anaconda3/envs/wsy/lib/python3.7/site-packages/paddle/fluid/dygraph/dygraph_to_static/utils.py", line 1245, in _build_assign_var_slice_node
	slice=gast.Index(value=gast.Name(
    AttributeError: module 'gast' has no attribute 'Index'

**Comment by littletomatodonkey** [comment]
在cpu和gpu上军没有复现该问题，初步怀疑是环境问题，可以试着在docker里直接使用python看下

**Comment by syyxsxx** [comment]
确认是环境问题，多谢
