### ISSUE TITLE
训练开始正常，训练过程中程序运行报错

### ISSUE THREAD

**Issue by gaorui999** [PaddlePaddle/PaddleClas#649]
程序一开始是正常出ACC和loSS的，但训练一会后就报错，显示无法进行训练，请帮忙找下原因

运行代码
    !python tools/train.py \
    -c configs/quick_start/MobileNetV3_large_x1_0_finetune.yaml \
    -o pretrained_model="" \
    -o use_gpu=True

报错命令
2021-03-20 20:49:54,224 - INFO - epoch:0  , train step:130 , top1: 0.34375, top5: 0.78125, loss: 2.11844, lr: 0.003358, batch_cost: 1.77810 s, reader_cost: 1.71894 s, ips: 17.99676 images/sec.
2021-03-20 20:50:01,444 - WARNING - DataLoader reader thread raised an exception. 
Traceback (most recent call last):
  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/home/aistudio/PaddleClas/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 351, in __next__
    return self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)

**Comment by TingquanGao** [comment]
您好，请问数据集是哪个呢？是从教程中的地址下载的吗？以及您使用的Paddle版本和PaddleClas分支是哪个呢？

**Comment by gaorui999** [comment]
> 您好，请问数据集是哪个呢？是从教程中的地址下载的吗？以及您使用的Paddle版本和PaddleClas分支是哪个呢？

使用的数据集是自定义数据集，IMAGENET格式的，使用的方法是文档中的，利用PaddleX划分的数据集。
paddle版本是2.0.1，PaddleClas分支是快速教程上的MobileNet的那个分支，把train.py文件和yaml文件改成自己数据集的路径和参数了

**Comment by TingquanGao** [comment]
您好，怀疑是数据集存在不合法数据，`release/2.0`分支的代码在读取不合法数据时无法有效处理，建议您使用`develop`分支。通过以下命令获取PaddleClas。
```shell
git clone -b develop https://github.com/PaddlePaddle/PaddleClas.git
```
