### ISSUE TITLE
infer.py  预测和训练结果不一样问题

### ISSUE THREAD

**Issue by wa3926** [PaddlePaddle/PaddleClas#664]
2021-04-02 07:09:10,228 - INFO - epoch:44 , train step:0   , top1: 1.00000, loss: 0.00012, lr: 0.002103, batch_cost: 11.17914 s, reader_cost: 10.22869 s, ips: 11.44990 images/sec, eta: 17:54:41
2021-04-02 07:10:53,871 - INFO - epoch:44 , train step:10  , top1: 1.00000, loss: 0.00003, lr: 0.002079, batch_cost: 9.13114 s, reader_cost: 8.18014 s, ips: 14.01796 images/sec, eta: 14:36:17
2021-04-02 07:12:29,053 - INFO - epoch:44 , train step:20  , top1: 1.00000, loss: 0.00001, lr: 0.002055, batch_cost: 9.48291 s, reader_cost: 8.53153 s, ips: 13.49797 images/sec, eta: 15:08:27
2021-04-02 07:14:07,158 - INFO - epoch:44 , train step:30  , top1: 1.00000, loss: 0.00008, lr: 0.002032, batch_cost: 9.63895 s, reader_cost: 8.68856 s, ips: 13.27946 images/sec, eta: 15:21:48
2021-04-02 07:15:45,892 - INFO - epoch:44 , train step:40  , top1: 1.00000, loss: 0.00010, lr: 0.002009, batch_cost: 9.71460 s, reader_cost: 8.76402 s, ips: 13.17604 images/sec, eta: 15:27:25
2021-04-02 07:17:24,538 - INFO - epoch:44 , train step:50  , top1: 1.00000, loss: 0.00005, lr: 0.001985, batch_cost: 9.75117 s, reader_cost: 8.80034 s, ips: 13.12663 images/sec, eta: 15:29:17
2021-04-02 07:19:01,436 - INFO - epoch:44 , train step:60  , top1: 1.00000, loss: 0.00021, lr: 0.001962, batch_cost: 9.73914 s, reader_cost: 8.78844 s, ips: 13.14285 images/sec, eta: 15:26:30
2021-04-02 07:20:38,974 - INFO - epoch:44 , train step:70  , top1: 1.00000, loss: 0.00005, lr: 0.001939, batch_cost: 9.74155 s, reader_cost: 8.79094 s, ips: 13.13959 images/sec, eta: 15:25:07
2021-04-02 07:22:21,764 - INFO - epoch:44 , train step:80  , top1: 1.00000, loss: 0.00002, lr: 0.001916, batch_cost: 9.81724 s, reader_cost: 8.86651 s, ips: 13.03828 images/sec, eta: 15:30:40
2021-04-02 07:24:00,480 - INFO - epoch:44 , train step:90  , top1: 1.00000, loss: 0.00005, lr: 0.001894, batch_cost: 9.82395 s, reader_cost: 8.87337 s, ips: 13.02939 images/sec, eta: 15:29:40
2021-04-02 07:25:49,189 - INFO - epoch:44 , train step:100 , top1: 1.00000, loss: 0.00008, lr: 0.001871, batch_cost: 9.93901 s, reader_cost: 8.98842 s, ips: 12.87855 images/sec, eta: 15:38:54
2021-04-02 07:26:08,800 - INFO - END epoch:44  train top1: 1.00000, loss: 0.00007,  batch_cost: 9.93613 s, reader_cost: 8.98555 s, batch_cost_sum: 924.06009 s, ips: 12.88228 images/sec.
2021-04-02 07:26:15,886 - INFO - valid step:0   , top1: 1.00000, loss: 0.00011, lr: 0.000000, batch_cost: 7.07814 s, reader_cost: 6.87662 s, ips: 12.43265 images/sec
2021-04-02 07:27:18,965 - INFO - valid step:10  , top1: 0.98864, loss: 0.02296, lr: 0.000000, batch_cost: 5.47337 s, reader_cost: 5.27298 s, ips: 16.07785 images/sec
2021-04-02 07:27:53,850 - INFO - END epoch:44  valid top1: 0.99249, loss: 0.04832,  batch_cost: 5.76542 s, reader_cost: 5.57323 s, batch_cost_sum: 40.35792 s, ips: 9.71309 images/sec.
2021-04-02 07:27:56,176 - INFO - Already save model in ./output/ocrcls2/ResNet50_vd/best_model
2021-04-02 07:27:56,177 - INFO - The best top1 acc 0.99249, in epoch: 44
2021-04-02 07:27:57,860 - INFO - Already save model in ./output/ocrcls2/ResNet50_vd/44

**上面是训练时候打印的  最后使用 tools/infer/infer.py 进行预测  就使用了 训练集里面的一些图片  结果发现有不对的  按理说都100%   后来发现  issue里面我看有人遇到类似问题  但那个是c++的 配置文件不太一样**   

TRAIN:
    batch_size: 128
    num_workers: 0
    file_list: "./dataset/ocrcls/train.txt"
    data_dir: "./dataset/ocrcls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            size: 224
        - NormalizeImage:
            scale: 1./255.
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage:

VALID:
    batch_size: 88
    num_workers: 0
    file_list: "./dataset/ocrcls/test.txt"
    data_dir: "./dataset/ocrcls/"
    shuffle_seed: 0
    transforms:
        - DecodeImage:
            to_rgb: True
            to_np: False
            channel_first: False
        - ResizeImage:
            size: 224
        - NormalizeImage:
            scale: 1.0/255.0
            mean: [0.485, 0.456, 0.406]
            std: [0.229, 0.224, 0.225]
            order: ''
        - ToCHWImage: 
上面是我配置文件  主要改动 就是去掉了 随机剪裁和翻转  验证和训练都换成了 ResizeImage 直接224      

我觉得可能和我改动有关 看了下 inter 调了一个配置      # parser.add_argument("--resize_short", type=int, default=256)
    parser.add_argument("--resize", type=int, default=224)  我就把resize_short  一行注释了   结果就报错了

Traceback (most recent call last):
  File "tools/infer/infer.py", line 87, in <module>
    main()
  File "tools/infer/infer.py", line 58, in main
    data = utils.preprocess(img, args)
  File "/paddle/PaddleClas/tools/infer/utils.py", line 106, in preprocess
    resize_op = ResizeImage(resize_short=args.resize_short)
AttributeError: 'Namespace' object has no attribute 'resize_short'

刚入门新手 问题有点多！  求大佬指点  预测这边应该怎么改参数

**Comment by TingquanGao** [comment]
这一行不要注释掉。按照你的想法，可以这样做：
将该函数：
https://github.com/PaddlePaddle/PaddleClas/blob/725a8ffda618eb8da16171a6b2006f6ab85e9928/tools/infer/utils.py#L105-L119
修改为：
```python
def preprocess(img, args):
    img = cv2.resize(img, (args.resize, args.resize))
    if args.normalize:
        img_mean = [0.485, 0.456, 0.406]
        img_std = [0.229, 0.224, 0.225]
        img_scale = 1.0 / 255.0
        normalize_op = NormalizeImage(
            scale=img_scale, mean=img_mean, std=img_std)
        img = normalize_op(img)
    tensor_op = ToTensor()
    img = tensor_op(img)
    return img
```
然后使用`tools/infer/infer.py`进行预测即可。

**Comment by wa3926** [comment]
@TingquanGao  按你说的改完之后 完美预测   感谢指导！
