### ISSUE TITLE
(Fatal) Blocking queue is killed because the data reader raises an exception

### ISSUE THREAD

**Issue by IamMegatron2025** [PaddlePaddle/PaddleClas#673]
hello, 我使用paddle2.0.1 和paddleClas-release-2.0，报错：
```
2021-04-09 11:54:48,699 - INFO - Load weight: bn5c_branch2c_variance, shape: (2048,)
2021-04-09 11:54:48,699 - INFO - Load weight: fc_weights, shape: (2048, 1000)
2021-04-09 11:54:48,700 - INFO - Load weight: fc_offset, shape: (1000,)
/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 1000], but the expected shape is [2048, 7979].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.bias. out.bias receives a shape [1000], but the expected shape is [7979].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
2021-04-09 11:54:48,983 - INFO - Finish initing model from /root/gongzhenting/work/clas/PaddleClas/pretrained/Res2Net101_vd_26w_4s_pretrained
2021-04-09 11:54:56,779 - ERROR - DataLoader reader thread raised an exception!Traceback (most recent call last):
INFO 2021-04-09 11:55:03,379 launch_utils.py:307] terminate all the procs
ERROR 2021-04-09 11:55:03,379 launch_utils.py:545] ABORT!!! Out of all 4 trainers, the trainer process with rank=[0, 1, 2, 3] was aborted. Please check its log.
INFO 2021-04-09 11:55:06,382 launch_utils.py:307] terminate all the procs

  File "tools/train.py", line 118, in <module>
    main(args)
  File "tools/train.py", line 90, in main
    epoch_id, 'train')
  File "/root/gongzhenting/work/clas/PaddleClas/PaddleClas-release-2.0/tools/program.py", line 300, in run
    for idx, batch in enumerate(dataloader()):
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 684, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/usr/local/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 616, in _thread_loop
    batch = self._get_data()
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 700, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 4 workers exit unexpectedly, pids: 6073, 6074, 6075, 6077
  File "/usr/local/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 779, in __next__

    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
```
我怀疑可能是我的数据有一部分是损坏的，所以修改了[这里](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.0/ppcls/data/reader.py#L188)的代码为：
```
        try:
            with open(img_path, 'rb') as f:
                img = f.read()
            return (transform(img, self.ops), int(label))
        except:
            pass
```
但是还是报同样的错误，该怎么解决呢？

**Comment by TingquanGao** [comment]
develop分支对可以异常数据进行处理：

https://github.com/PaddlePaddle/PaddleClas/blob/97f4f557e575b7cbd343c16e41ecaad123eb189b/ppcls/data/reader.py#L185-L196

**Comment by IamMegatron2025** [comment]
@TingquanGao  谢谢回复，但是好像还是不行，用develop分支，报错：

```
2021-04-09 12:40:11,159 - INFO - Load weight: fc_weights, shape: (2048, 1000)
2021-04-09 12:40:11,159 - INFO - Load weight: fc_offset, shape: (1000,)
/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.weight. out.weight receives a shape [2048, 1000], but the expected shape is [2048, 7979].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
/usr/local/lib/python3.7/site-packages/paddle/fluid/dygraph/layers.py:1303: UserWarning: Skip loading for out.bias. out.bias receives a shape [1000], but the expected shape is [7979].
  warnings.warn(("Skip loading for {}. ".format(key) + str(err)))
2021-04-09 12:40:11,476 - INFO - Finish load pretrained model from /root/gongzhenting/work/clas/PaddleClas/pretrained/Res2Net101_vd_26w_4s_pretrained
2021-04-09 12:40:16,751 - ERROR - DataLoader reader thread raised an exception!
INFO 2021-04-09 12:40:19,072 launch.py:240] Local processes completed.
2021-04-09 12:40:16,751 - ERROR - (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:158)
```
 
镜像：paddlepaddle/paddle:latest-dev-cuda10.2-cudnn7-gcc82
paddle版本：在上面镜像创建的容器中安装：python3.7 -m pip install paddlepaddle-gpu==2.0.1 -i https://mirror.baidu.com/pypi/simple

执行训练时使用的是python3.7

**Comment by littletomatodonkey** [comment]
你好，动态图dataloader使用docker的话，shm-size需要设置的大一些，建议至少大于4g

https://github.com/PaddlePaddle/PaddleClas/blob/release%2F2.0/docs/zh_CN/faq_series/faq_2021_s1.md#q13-%E5%9C%A8docker%E4%B8%AD%E8%AE%AD%E7%BB%83%E7%9A%84%E6%97%B6%E5%80%99%E6%95%B0%E6%8D%AE%E8%B7%AF%E5%BE%84%E5%92%8C%E9%85%8D%E7%BD%AE%E5%9D%87%E6%B2%A1%E9%97%AE%E9%A2%98%E4%BD%86%E6%98%AF%E4%B8%80%E7%9B%B4%E6%8A%A5%E9%94%99systemerror-fatal-blocking-queue-is-killed-because-the-data-reader-raises-an-exception%E8%BF%99%E6%98%AF%E4%B8%BA%E4%BB%80%E4%B9%88%E5%91%A2

![image](https://user-images.githubusercontent.com/14270174/114256920-33c95c80-99ef-11eb-9d1e-211f6cb2aee8.png)
