### ISSUE TITLE
随机裁剪如何不使用方形裁剪

### ISSUE THREAD

**Issue by ActonMartin** [PaddlePaddle/PaddleClas#781]
想裁剪不是方形的图片，但是在传入一个元组，报错。

```
Traceback (most recent call last):
  File "D:\PaddleClas-release-2.1\ppcls\data\reader.py", line 192, in __getitem__
    return (transform(img, self.ops), int(label))
  File "D:\PaddleClas-release-2.1\ppcls\data\imaug\__init__.py", line 43, in transform
    data = op(data)
  File "D:\PaddleClas-release-2.1\ppcls\data\imaug\operators.py", line 157, in __call__
    return cv2.resize(img, size)
SystemError: new style getargs format but argument is not a tuple
```
![image](https://user-images.githubusercontent.com/28743875/120739459-1a8ee900-c524-11eb-9802-f4314f347916.png)

**Comment by weisy11** [comment]
这个是yaml文件解析的问题，这样传进去是不能解析成tuple的。
可以用yaml.dump()的方式来看一下要改的内容的格式。
例如yaml.dump((1, 2)) 会得到：
'!!python/tuple\n- 1\n- 2\n'

**Comment by lazyn1997** [comment]
请问一下这个应该怎么写呢，我尝试了列表也不对
