### ISSUE TITLE
Apple M1 芯片 docker 版本无法使用

### ISSUE THREAD

**Issue by zhangfelix** [PaddlePaddle/PaddleClas#959]
## 异常说明

参照该[安装说明](https://github.com/PaddlePaddle/PaddleClas/blob/release/2.2/docs/zh_CN/tutorials/install.md)准备docker环境后，参照1.4节验证`PaddlePaddle`的安装时，出现问题。

## 复现路径

执行`docker run --name ppcls -v $PWD:/paddle --shm-size=8G --network=host -it paddlepaddle/paddle:2.1.0 /bin/bash`遇到以下警告信息：
```
Digest: sha256:d430d36217f32c74db9991396003f252e4bc91d891d8193bc24bea5943a848f3
Status: Downloaded newer image for paddlepaddle/paddle:2.1.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
```
在容器内验证`PaddlePaddle`安装情况时，出现如下错误信息：
```py
λ docker-desktop /home python
Python 3.7.0 (default, May  9 2021, 21:14:18)
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import paddle
/bin/grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
WARNING: AVX is not support on your machine. Hence, no_avx core will be imported, It has much worse preformance than avx core.
/bin/grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Error: AVX is not support on your machine, but you have installed paddlepaddle without no_avx core, you should reinstall paddlepaddle by 'python -m pip install --force-reinstall paddlepaddle-gpu[==version] -f https://paddlepaddle.org.cn/whl/mkl/stable/noavx.html or https://paddlepaddle.org.cn/whl/openblas/stable/noavx.html
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/__init__.py", line 26, in <module>
    from .fluid import monkey_patch_variable
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/__init__.py", line 36, in <module>
    from . import framework
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/framework.py", line 37, in <module>
    from . import core
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core.py", line 369, in <module>
    raise e
  File "/usr/local/python3.7.0/lib/python3.7/site-packages/paddle/fluid/core.py", line 316, in <module>
    from .core_noavx import *
ModuleNotFoundError: No module named 'paddle.fluid.core_noavx'
```

## 系统信息
macOS Big Sur 11.4
MacBook Pro (13-inch, M1, 2020)
芯片 Apple M1

## docker 版本信息
```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:23 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by weisy11** [comment]
是的，目前M1芯片还存在许多问题，从docker安装，到检索系统的编译。我们会尽快给出一个M1的解决方案。感谢关注。
