### ISSUE TITLE
运行swin-transformer报错，

### ISSUE THREAD

**Issue by Williamlizl** [PaddlePaddle/PaddleClas#991]
`Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    trainer.train()
  File "/home/lbc/PaddleClas/ppcls/engine/trainer.py", line 171, in train
    out = self.model(batch[0])
  File "/home/lbc/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lbc/PaddleClas/ppcls/arch/backbone/model_zoo/swin_transformer.py", line 718, in forward
    x = self.forward_features(x)
  File "/home/lbc/PaddleClas/ppcls/arch/backbone/model_zoo/swin_transformer.py", line 710, in forward_features
    x = layer(x)
  File "/home/lbc/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lbc/PaddleClas/ppcls/arch/backbone/model_zoo/swin_transformer.py", line 508, in forward
    x = blk(x)
  File "/home/lbc/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lbc/PaddleClas/ppcls/arch/backbone/model_zoo/swin_transformer.py", line 363, in forward
    x = shortcut + self.drop_path(x)
  File "/home/lbc/.local/lib/python3.6/site-packages/paddle/fluid/dygraph/layers.py", line 898, in __call__
    outputs = self.forward(*inputs, **kwargs)
  File "/home/lbc/PaddleClas/ppcls/arch/backbone/model_zoo/vision_transformer.py", line 81, in forward
    return drop_path(x, self.drop_prob, self.training)
  File "/home/lbc/PaddleClas/ppcls/arch/backbone/model_zoo/vision_transformer.py", line 66, in drop_path
    random_tensor = keep_prob + paddle.rand(shape, dtype=x.dtype)
  File "/home/lbc/.local/lib/python3.6/site-packages/paddle/tensor/random.py", line 722, in rand
    return uniform(shape, dtype, min=0.0, max=1.0, name=name)
  File "/home/lbc/.local/lib/python3.6/site-packages/paddle/tensor/random.py", line 502, in uniform
    float(max), 'seed', seed, 'dtype', dtype)
SystemError: (Fatal) Operator uniform_random raises an thrust::system::system_error exception.
The exception content is
:parallel_for failed: cudaErrorInvalidConfiguration: invalid configuration argument. (at /paddle/paddle/fluid/imperative/tracer.cc:192)`

**Comment by cuicheng01** [comment]
在https://www.paddlepaddle.org.cn/install/quick?docurl=/documentation/docs/zh/develop/install/pip/linux-pip.html，安装develop版本的paddlepaddle试一下~

**Comment by Chen-Song** [comment]
@Williamlizl 你好，请问你找到出现这个问题的原因了吗？我也遇到了相同的问题
