### ISSUE TITLE
训练自定义数据集总是报错：BUS error

### ISSUE THREAD

**Issue by huilin16** [PaddlePaddle/PaddleClas#999]
ERROR: Unexpected BUS error encountered in DataLoader worker. This might be caused by insufficient shared memory (shm), please check whether use_shared_memory is set and storage space in /dev/shm is enough
ERROR:root:DataLoader reader thread raised an exception!
Exception in thread Thread-11:
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 482, in _get_data
    data = self._data_queue.get(timeout=self._timeout)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/multiprocessing/queues.py", line 105, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 411, in _thread_loop
    batch = self._get_data()
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 498, in _get_data
    "pids: {}".format(len(failed_workers), pids))
RuntimeError: DataLoader 1 workers exit unexpectedly, pids: 2642

Traceback (most recent call last):
  File "tools/train.py", line 31, in <module>
    trainer.train()
  File "/home/aistudio/PaddleClas/ppcls/engine/trainer.py", line 160, in train
    for iter_id, batch in enumerate(self.train_dataloader()):
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py", line 585, in __next__
    data = self._reader.read_next_var_list()
SystemError: (Fatal) Blocking queue is killed because the data reader raises an exception.
  [Hint: Expected killed_ != true, but received killed_:1 == true:1.] (at /paddle/paddle/fluid/operators/reader/blocking_queue.h:166)

我在训练自定义图像分类数据集的时候总是出现上述问题，我使用模型的是ResNet101_vd，batchsize设置过2、8、16，numwork设置过1、4，图像大小224，总是会出现上述问题

请问应该如何解决

**Comment by RainFrost1** [comment]
可能是`shared memory`太小导致。建议
- 增大`shared memory`
- 或者先减小`dataloader`的`number_worker`数量

**Comment by huilin16** [comment]
> 可能是`shared memory`太小导致。建议
> 
> * 增大`shared memory`
> * 或者先减小`dataloader`的`number_worker`数量

请问shared memory应该怎么增大呢，我使用过的aistudio上的16g v100，运行时显存占用不大呀

**Comment by RainFrost1** [comment]
shared memory是不同进程间通信的一种方式，跟显存没有关系。增大的话，可以询问先aistuido的支持同学。减少dataloader的number woker数量，还报错吗？

**Comment by wangping6688** [comment]
我也遇到过同样问题，请问你现在解决了吗

**Comment by wangping6688** [comment]
我是在训练途中出现这个问题的，大概在第10-12个epoch时候

**Comment by chenzhaoqiJM** [comment]
我是把训练.yaml文件中的DataLoader: 下的 use_shared_memory: True 改成 use_shared_memory: False就解决了这个问题。在官方提供的训练环境下，使用free -h命令发现没有开启交换内存，所以只要物理内存足够应该就可以关闭这个选项
